[build]
command = "node scripts/build.mjs && node scripts/after-build.mjs"
publish = "site"

[[redirects]]
  from = "/check"
  to = "/assets/check/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr/check"
  to = "/assets/check/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/masterclass"
  to = "/assets/masterclass/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/fr/masterclass"
  to = "/assets/masterclass/index.html"
  status = 200
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/check"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fr/check"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/masterclass"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fr/masterclass"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
