export const LIFE_PRODUCTS = [
  {
    sku: 'KL-VARSITY-001',
    slug: 'founding-varsity-jacket',
    name: 'Founding Varsity Jacket',
    category: 'Wear',
    collection: 'Collection 001',
    price: 295,
    currency: 'EUR',
    badge: 'Founding Piece',
    tone: 'Midnight / Bone',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A structured varsity jacket designed as the emblem of the first KŌMØ Life collection. Heritage proportions, restrained marks, made to move beyond seasons.',
    detail: 'Midweight construction · embroidered KŌMØ Life marks · ribbed collar and cuffs · unisex fit.',
    image: 'assets/product-varsity.svg'
  },
  {
    sku: 'KL-QZIP-001',
    slug: 'life-quarter-zip',
    name: 'Life Quarter Zip',
    category: 'Wear',
    collection: 'Collection 001',
    price: 165,
    currency: 'EUR',
    badge: 'Core',
    tone: 'Midnight Navy',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A clean quarter zip with a soft architectural collar and discreet KŌMØ Life embroidery. Designed for travel, recovery and everyday movement.',
    detail: 'Dense cotton knit · metal zip · tonal embroidery · relaxed unisex fit.',
    image: 'assets/product-quarterzip.svg'
  },
  {
    sku: 'KL-KNIT-001',
    slug: 'club-cable-knit',
    name: 'Club Cable Knit',
    category: 'Wear',
    collection: 'Collection 001',
    price: 185,
    currency: 'EUR',
    badge: 'Limited',
    tone: 'Bone',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A tactile cable knit balancing old-world club references with a modern silhouette. Quietly branded, intentionally substantial.',
    detail: 'Cable structure · soft-touch yarn · chest mark · relaxed fit.',
    image: 'assets/product-knit.svg'
  },
  {
    sku: 'KL-TEE-001',
    slug: 'longevity-heavyweight-tee',
    name: 'Longevity Heavyweight Tee',
    category: 'Wear',
    collection: 'Collection 001',
    price: 85,
    currency: 'EUR',
    badge: 'Core',
    tone: 'Natural',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'A heavyweight everyday tee carrying the KŌMØ Life signature and the founding line: Longevity in Motion.',
    detail: 'Heavy cotton jersey · bound neck · soft hand feel · unisex fit.',
    image: 'assets/product-tee.svg'
  },
  {
    sku: 'KL-HOOD-001',
    slug: 'motion-hoodie',
    name: 'Motion Hoodie',
    category: 'Wear',
    collection: 'Collection 001',
    price: 155,
    currency: 'EUR',
    badge: 'Core',
    tone: 'Forest',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A dense hoodie for cool starts, long travel days and quiet recovery. Minimal outside, considered in every proportion.',
    detail: 'Heavy brushed cotton · double-layer hood · tonal mark · relaxed fit.',
    image: 'assets/product-hoodie.svg'
  },
  {
    sku: 'KL-CAP-001',
    slug: 'life-club-cap',
    name: 'Life Club Cap',
    category: 'Objects',
    collection: 'Collection 001',
    price: 65,
    currency: 'EUR',
    badge: 'Accessory',
    tone: 'Forest / Bone',
    sizes: ['One size'],
    description: 'A six-panel cap carrying the understated KŌMØ Life club mark. Built as a daily object rather than seasonal merchandise.',
    detail: 'Six-panel construction · embroidered crest · adjustable closure.',
    image: 'assets/product-cap.svg'
  },
  {
    sku: 'KL-TOTE-001',
    slug: 'founding-canvas-tote',
    name: 'Founding Canvas Tote',
    category: 'Objects',
    collection: 'Collection 001',
    price: 55,
    currency: 'EUR',
    badge: 'Accessory',
    tone: 'Natural / Midnight',
    sizes: ['One size'],
    description: 'A structured canvas carryall for studio, travel and daily life, finished with the secondary KŌMØ Life crest.',
    detail: 'Heavy canvas · reinforced handles · internal pocket · embroidered crest.',
    image: 'assets/product-tote.svg'
  },
  {
    sku: 'KL-SWEAT-001',
    slug: 'life-is-health-sweatshirt',
    name: 'Life Is Health Sweatshirt',
    category: 'Wear',
    collection: 'Collection 001',
    price: 145,
    currency: 'EUR',
    badge: 'Founding Piece',
    tone: 'Oat',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The founding statement piece. A quiet front and a typographic back built around the original KŌMØ Life language.',
    detail: 'Loopback cotton · back typography · clean rib · relaxed unisex fit.',
    image: 'assets/product-sweatshirt.svg'
  }
];

export const formatLifePrice = (amount, currency = 'EUR') =>
  new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0
  }).format(amount);
