import './tokens.css';
import './check-v2.css';

const hero = () => `<div class="kc-page"><section class="kc-hero"><div class="kc-shell kc-hero__grid"><div><p class="kc-eyebrow">KŌMØ CHECK · PRÉVENTION LOCOMOTRICE</p><h1>Testez votre mobilité locomotrice.<br><em>En quelques minutes.</em></h1></div><div class="kc-hero__aside"><p>Trois repères complémentaires — questionnaire, fonction des membres inférieurs et longueur fonctionnelle du pas — réunis dans une expérience simple, privée et lisible.</p><div class="kc-actions"><a class="kc-btn">Commencer le KŌMØ Check →</a><a class="kc-btn kc-btn--quiet">Comprendre le test ↓</a></div><ul class="kc-meta"><li>Gratuit</li><li>Sans compte</li><li>≈ 8 minutes</li><li>Calcul sur votre appareil</li></ul></div></div></section></div>`;

const question = () => `<div class="kc-page"><section class="kc-app"><div class="kc-reading"><div class="kc-progress"><div class="kc-progress__top"><span>Progression</span><strong>08 / 27</strong></div><div class="kc-progress__bar"><i style="width:29.6%"></i></div></div><div class="kc-card"><div class="kc-card__inner"><p class="kc-eyebrow">GLFS-25 · QUESTION 08</p><p class="kc-count">Question 8 sur 25</p><h2 class="kc-question">Dans quelle mesure a-t-il été difficile d’enfiler et de retirer une chemise ou un haut&nbsp;?</h2><p class="kc-hint">Choisissez la réponse qui correspond le mieux au mois écoulé.</p><div class="kc-answers">${['Pas difficile','Légèrement difficile','Modérément difficile','Très difficile','Extrêmement difficile'].map((x,i)=>`<button class="kc-answer" aria-pressed="${i===1}"><b>${i}</b><span>${x}</span></button>`).join('')}</div><div class="kc-nav"><button>← Retour</button><button>Continuer →</button></div></div></div></div></section></div>`;

const result = () => `<div class="kc-page"><section class="kc-result"><div class="kc-shell kc-result__grid"><div><p class="kc-eyebrow">VOTRE REPÈRE LOCOMOTEUR</p><h2>Votre résultat est prêt.</h2><p class="kc-stage">LS Stage 1</p><p class="kc-result__lead">Au moins l’un des trois tests atteint le seuil JOA du LS Stage 1. Ce résultat peut servir de signal pour porter davantage d’attention à la mobilité et à la prévention.</p><div class="kc-result__actions"><a class="kc-btn">Découvrir KŌMØ Clinical →</a><a class="kc-btn kc-btn--quiet">Lire KŌMØ Library ↗</a></div><p class="kc-boundary">KŌMØ Check est une expérience de dépistage fonctionnel à visée éducative et préventive. Il ne pose pas de diagnostic.</p></div><div class="kc-result__metrics"><div class="kc-metric"><span>Repère global</span><strong>LS Stage 1</strong></div><div class="kc-metric"><span>GLFS-25</span><strong>8/100 · LS Stage 1</strong></div><div class="kc-metric"><span>Lever</span><strong>Sous le seuil LS Stage 1</strong></div><div class="kc-metric"><span>Deux pas</span><strong>1.34 · Sous le seuil LS Stage 1</strong></div></div></div></section></div>`;

export default { title:'Pages / KŌMØ Check V2', parameters:{ layout:'fullscreen' } };
export const Hero = { render: hero };
export const Question = { render: question };
export const Result = { render: result };
