import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ORIGINS=new Set(["https://pulse.komolongevity.com","https://komolongevity.com"]),MANAGER=new Set(["owner","clinical_admin"]);
function cors(req:Request){const o=req.headers.get("origin")??"";return{"Access-Control-Allow-Origin":ORIGINS.has(o)?o:"https://pulse.komolongevity.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function out(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,{error:"method_not_allowed"},405);const token=(req.headers.get("Authorization")??"").replace(/^Bearer\s+/i,"");if(!token)return out(req,{error:"unauthorized"},401);const uc=createClient(U,A,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}),svc=createClient(U,S,{auth:{persistSession:false}});const ur=await uc.auth.getUser(token),actor=ur.data?.user;if(ur.error||!actor)return out(req,{error:"unauthorized"},401);
const rr=await svc.from("account_roles").select("role").eq("user_id",actor.id).maybeSingle();const role=rr.data?.role??"member",isAdmin=role==="admin";if(!["professional","admin"].includes(role))return out(req,{error:"professional_required"},403);
const mq0=await svc.from("organization_members").select("organization_id,role,status,access_scope,organizations(id,name,slug,city,address_line,postal_code,country_code,timezone,status,clinical_data_status,booking_published,contact_email)").eq("user_id",actor.id).eq("status","active");if(mq0.error)return out(req,{error:"memberships_failed",detail:mq0.error.message},500);const ms=mq0.data??[],managerIds=new Set(ms.filter((m:any)=>MANAGER.has(m.role)).map((m:any)=>m.organization_id));let centers:any[]=[];
if(isAdmin){const q=await svc.from("organizations").select("id,name,slug,city,address_line,postal_code,country_code,timezone,status,clinical_data_status,booking_published,contact_email,created_at").order("name");if(q.error)return out(req,{error:"centers_failed",detail:q.error.message},500);centers=q.data??[]}else centers=ms.map((m:any)=>({...m.organizations,membership_role:m.role,access_scope:m.access_scope})).filter(Boolean);
const ids=centers.map((x:any)=>x.id);if(!ids.length)return out(req,{centers:[],requests:[],patients:[],appointments:[],members:[],account_role:role});
const [rq,pq,aq,mq,asq]=await Promise.all([
svc.from("patient_service_requests").select("*").in("assigned_organization_id",ids).order("submitted_at",{ascending:false}).limit(300),
svc.from("patients").select("id,organization_id,patient_user_id,external_reference,first_name,last_name,preferred_name,birth_date,email,status,created_at,data_classification").in("organization_id",ids).order("created_at",{ascending:false}).limit(500),
svc.from("organization_appointments").select("id,organization_id,patient_id,assigned_user_id,appointment_type,scheduled_start,scheduled_end,status,booking_source").in("organization_id",ids).gte("scheduled_start",new Date(Date.now()-86400000).toISOString()).order("scheduled_start").limit(500),
svc.from("organization_members").select("organization_id,user_id,role,status,access_scope").in("organization_id",ids).eq("status","active"),
svc.from("patient_care_assignments").select("organization_id,patient_id,professional_user_id,status").in("organization_id",ids).eq("professional_user_id",actor.id).eq("status","active")]);
if(rq.error||pq.error||aq.error||mq.error||asq.error)return out(req,{error:"overview_failed",detail:rq.error?.message||pq.error?.message||aq.error?.message||mq.error?.message||asq.error?.message},500);
const visibleReq=(rq.data??[]).filter((r:any)=>isAdmin||managerIds.has(r.assigned_organization_id)||r.assigned_professional_user_id===actor.id),visibleAppts=(aq.data??[]).filter((a:any)=>isAdmin||managerIds.has(a.organization_id)||a.assigned_user_id===actor.id),durable=new Set((asq.data??[]).map((x:any)=>x.patient_id));for(const r of visibleReq)if(r.patient_id)durable.add(r.patient_id);for(const a of visibleAppts)if(a.patient_id)durable.add(a.patient_id);const visiblePatients=(pq.data??[]).filter((p:any)=>isAdmin||managerIds.has(p.organization_id)||durable.has(p.id)),visibleMembers=(mq.data??[]).filter((m:any)=>isAdmin||managerIds.has(m.organization_id)||m.user_id===actor.id);
const userIds=[...new Set([...visibleReq.map((r:any)=>r.user_id),...visibleMembers.map((m:any)=>m.user_id)].filter(Boolean))];let profileMap=new Map<string,any>();if(userIds.length){const pr=await svc.from("profiles").select("id,display_name,first_name,last_name,city,country,phone").in("id",userIds);if(pr.error)return out(req,{error:"profiles_failed",detail:pr.error.message},500);profileMap=new Map((pr.data??[]).map((p:any)=>[p.id,p]))}
const requests=visibleReq.map((r:any)=>({...r,profile:profileMap.get(r.user_id)??null})),members=visibleMembers.map((m:any)=>({...m,profile:profileMap.get(m.user_id)??null}));return out(req,{centers,requests,patients:visiblePatients,appointments:visibleAppts,members,account_role:role});});