import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const siteDir = join(root, 'site');
const original = await readFile(join(siteDir, 'assets/check/index.html'), 'utf8');
const tokens = await readFile(join(root, 'src/design-system/tokens.css'), 'utf8');
const styles = await readFile(join(root, 'src/design-system/check-v2.css'), 'utf8');
const match = original.match(/const DATA = (\{[\s\S]*?\});\nconst path/);
if (!match) throw new Error('KŌMØ Check: unable to extract GLFS-25 source data');
const sourceData = JSON.parse(match[1]);

const esQuestions = [
  '¿Ha tenido dolor, incluido entumecimiento, en el cuello, los hombros, los brazos o las manos?',
  '¿Ha tenido dolor en la espalda, la zona lumbar o los glúteos?',
  '¿Ha tenido dolor, incluido entumecimiento, en la parte inferior del cuerpo (pelvis, muslos, rodillas, pantorrillas, espinillas, tobillos o pies)?',
  '¿Hasta qué punto le ha resultado doloroso mover el cuerpo en la vida cotidiana?',
  '¿Hasta qué punto le ha resultado difícil levantarse de la cama o acostarse?',
  '¿Hasta qué punto le ha resultado difícil levantarse desde una posición sentada?',
  '¿Hasta qué punto le ha resultado difícil caminar dentro de su domicilio?',
  '¿Hasta qué punto le ha resultado difícil ponerse y quitarse una camisa o una prenda superior?',
  '¿Hasta qué punto le ha resultado difícil ponerse y quitarse pantalones y ropa interior?',
  '¿Hasta qué punto le ha resultado difícil utilizar el baño?',
  '¿Hasta qué punto le ha resultado difícil lavarse el cuerpo en el baño o la ducha?',
  '¿Hasta qué punto le ha resultado difícil subir y bajar escaleras?',
  '¿Hasta qué punto le ha resultado difícil caminar deprisa?',
  'Al salir de casa, ¿hasta qué punto le ha resultado difícil mantener una apariencia cuidada?',
  '¿Qué distancia puede caminar sin descansar? Elija la respuesta más cercana.',
  '¿Hasta qué punto le ha resultado difícil ir a casa de un vecino o desplazarse por su barrio?',
  '¿Hasta qué punto le ha resultado difícil transportar objetos de unos dos kilogramos?',
  '¿Hasta qué punto le ha resultado difícil salir utilizando tren o autobús?',
  '¿Hasta qué punto le ha resultado difícil realizar tareas domésticas ligeras?',
  '¿Hasta qué punto le ha resultado difícil realizar tareas domésticas algo más pesadas?',
  '¿Hasta qué punto le ha resultado difícil participar en actividades deportivas o de baile?',
  '¿Ha tenido que evitar reunirse con amigos cercanos o conocidos?',
  '¿Ha tenido que evitar actividades o eventos de su comunidad?',
  '¿Ha sentido preocupación por caerse dentro de su domicilio?',
  '¿Ha sentido preocupación por no poder caminar en el futuro?'
];
const esSets = {
  pain: ['Sin dolor','Dolor leve','Dolor moderado','Dolor considerable','Dolor extremo'],
  painful: ['Nada doloroso','Ligeramente doloroso','Moderadamente doloroso','Muy doloroso','Extremadamente doloroso'],
  difficult: ['Nada difícil','Ligeramente difícil','Moderadamente difícil','Muy difícil','Extremadamente difícil'],
  distance: ['2 km o más','Aproximadamente 1 km','Aproximadamente 300 m','Aproximadamente 100 m','Aproximadamente 10 m'],
  refrain: ['No tuve que evitarlo','Lo evité un poco','Lo evité moderadamente','Lo evité bastante','Lo evité por completo'],
  anxious: ['Nada preocupado/a','Ligeramente preocupado/a','Moderadamente preocupado/a','Muy preocupado/a','Extremadamente preocupado/a']
};
const esQuestionsData = esQuestions.map((q, i) => {
  const opts = i <= 2 ? esSets.pain : i === 3 ? esSets.painful : i === 14 ? esSets.distance : i === 21 || i === 22 ? esSets.refrain : i >= 23 ? esSets.anxious : esSets.difficult;
  return [q, opts];
});

const COPY = {
  en: {
    lang:'en', locale:'en_US', title:'KŌMØ Check — Free Locomotor Mobility Test', description:'Assess locomotor mobility with GLFS-25, Stand-Up and Two-Step tests. Free, no sign-up, with an immediate educational result.',
    home:'/', check:'/check/', clinical:'/clinical/', science:'/science/', library:'/en/media', locomotor:'/locomotor/', contact:'/contact/',
    navBack:'KŌMØ', eyebrow:'KŌMØ CHECK · LOCOMOTOR PREVENTION', hero:'Test your locomotor mobility.<br><em>In a few minutes.</em>', lead:'Three complementary references — questionnaire, lower-limb function and functional stride — brought together in one calm, private experience.',
    start:'Start the KŌMØ Check →', method:'See how it works ↓', facts:['Free','No account','≈ 8 minutes','Calculated on your device'],
    methodEyebrow:'THREE COMPLEMENTARY REFERENCES', methodTitle:'A questionnaire.<br><em>Two functional tests.</em>', methodBody:'KŌMØ Check follows the three elements used by the Japanese Orthopaedic Association for the Locomotive Syndrome Risk Test. The overall LS stage is the most advanced stage reached by any one of the three tests; the results are not added together.',
    methods:[['GLFS-25','25 questions about pain, daily activities, mobility and participation during the past month.'],['Stand-Up Test','A simple lower-limb functional task using defined seat heights.'],['Two-Step Test','Two controlled large steps, expressed relative to height as a functional stride reference.']],
    privacy:'Your answers stay in this browser and are not sent to KŌMØ by this page.', progress:'Progress', question:'Question', of:'of', hint:'Choose the response that best reflects the past month.', back:'Back', continue:'Continue →',
    standEyebrow:'TEST 02 · LOWER-LIMB FUNCTION', standTitle:'Stand-Up Test', standHint:'Fold your arms, stand without momentum and hold the position for 3 seconds. Select the highest level you can complete safely.', standSafety:'Only perform this test if you feel stable and safe. Use a caregiver when appropriate, use a non-slip surface, and stop with pain, dizziness or loss of balance.',
    standOptions:['I can stand on one leg from 40 cm on both the right and left.','I cannot do that, but I can stand with both legs from 20 cm.','I cannot stand with both legs from 20 cm, but I can from 30 cm.','I cannot stand with both legs from 30 cm.'],
    twoEyebrow:'TEST 03 · FUNCTIONAL STRIDE', twoTitle:'Two-Step Test', twoHint:'After a brief warm-up, take two large controlled steps without jumping. Perform two attempts and keep the better distance.', height:'Your height', distance:'Best two-step distance', ratio:'Two-step value', show:'See my result →', invalid:'Enter a height from 120 to 230 cm and a distance from 40 to 500 cm.',
    resultEyebrow:'YOUR LOCOMOTOR REFERENCE', resultReady:'Your result is ready.', stage0:'Below LS Stage 1 threshold', stage1:'LS Stage 1', stage2:'LS Stage 2', stage3:'LS Stage 3',
    resultBodies:['None of the three tests reaches the current JOA threshold for LS Stage 1. This is a reference point, not a guarantee about future mobility.','At least one of the three tests reaches the JOA threshold for LS Stage 1. This can be used as a prompt to pay attention to mobility and prevention.','At least one test reaches the JOA threshold for LS Stage 2. A professional assessment can help put the result in context and identify contributing factors.','At least one test reaches the JOA threshold for LS Stage 3. A professional clinical assessment is particularly appropriate when daily activities, walking or participation are limited.'],
    glfs:'GLFS-25', stand:'Stand-Up', two:'Two-Step', overall:'Overall reference', clinicalCta:'Explore KŌMØ Clinical →', libraryCta:'Read KŌMØ Library ↗', download:'Download result card', share:'Share', restart:'Restart', boundary:'KŌMØ Check is an educational functional screening experience. It does not diagnose a disease, predict an individual outcome or replace examination by a healthcare professional. Seek prompt professional advice for a new or rapidly worsening limitation, repeated falls, marked weakness, significant pain or neurological symptoms.',
    faqEyebrow:'QUESTIONS PEOPLE ASK', faqTitle:'Understanding the Check.<br><em>Without ambiguity.</em>', faqs:[['How can I test my mobility at home?','KŌMØ Check combines a 25-item functional questionnaire with the Stand-Up and Two-Step tests. Functional tests should only be attempted when the environment is safe and the instructions can be followed without pain or instability.'],['What is GLFS-25?','The 25-question Geriatric Locomotive Function Scale is a published questionnaire developed to assess subjective locomotor difficulties across pain, activities of daily living, mobility and participation.'],['What does an LS stage mean?','The Japanese Orthopaedic Association uses thresholds from the GLFS-25, Stand-Up Test and Two-Step Test. The most advanced threshold reached by any one test determines the LS stage.'],['Is KŌMØ Check a diagnosis?','No. It is a prevention-oriented functional screening experience. A result cannot establish the cause of a limitation and does not replace a medical assessment.'],['Does KŌMØ store my answers?','Not on this public page. The calculation is performed locally in your browser and no health answers are sent to KŌMØ by the Check.']],
    refsTitle:'Scientific references', footer:'Locomotor longevity · Prevention · Clinical continuity', scienceLink:'Science & method', libraryLink:'KŌMØ Library'
  },
  fr: {
    lang:'fr', locale:'fr_FR', title:'KŌMØ Check — Test gratuit de mobilité locomotrice', description:'Évaluez votre mobilité avec la GLFS-25, le test de lever et le Two-Step Test. Gratuit, sans inscription, résultat immédiat à visée préventive.',
    home:'/fr/', check:'/fr/check/', clinical:'/fr/clinical/', science:'/fr/science/', library:'/media', locomotor:'/fr/locomotor/', contact:'/fr/contact/',
    navBack:'KŌMØ', eyebrow:'KŌMØ CHECK · PRÉVENTION LOCOMOTRICE', hero:'Testez votre mobilité locomotrice.<br><em>En quelques minutes.</em>', lead:'Trois repères complémentaires — questionnaire, fonction des membres inférieurs et longueur fonctionnelle du pas — réunis dans une expérience simple, privée et lisible.',
    start:'Commencer le KŌMØ Check →', method:'Comprendre le test ↓', facts:['Gratuit','Sans compte','≈ 8 minutes','Calcul sur votre appareil'],
    methodEyebrow:'TROIS REPÈRES COMPLÉMENTAIRES', methodTitle:'Un questionnaire.<br><em>Deux tests fonctionnels.</em>', methodBody:'KŌMØ Check reprend les trois éléments du Locomotive Syndrome Risk Test de la Japanese Orthopaedic Association. Le stade LS global correspond au stade le plus avancé atteint par l’un des trois tests ; les résultats ne sont pas additionnés.',
    methods:[['GLFS-25','25 questions sur la douleur, les activités quotidiennes, la mobilité et la participation au cours du mois écoulé.'],['Test de lever','Une tâche fonctionnelle simple des membres inférieurs réalisée à partir de hauteurs définies.'],['Test des deux pas','Deux grands pas contrôlés rapportés à la taille pour obtenir un repère de longueur fonctionnelle du pas.']],
    privacy:'Vos réponses restent dans ce navigateur et ne sont pas transmises à KŌMØ par cette page.', progress:'Progression', question:'Question', of:'sur', hint:'Choisissez la réponse qui correspond le mieux au mois écoulé.', back:'Retour', continue:'Continuer →',
    standEyebrow:'TEST 02 · FONCTION DES MEMBRES INFÉRIEURS', standTitle:'Test de lever', standHint:'Bras croisés, levez-vous sans élan et maintenez la position 3 secondes. Sélectionnez le niveau le plus élevé que vous pouvez réaliser en sécurité.', standSafety:'Réalisez ce test uniquement si vous vous sentez stable et en sécurité. Faites-vous accompagner si nécessaire, utilisez un sol non glissant et arrêtez en cas de douleur, vertige ou perte d’équilibre.',
    standOptions:['Je peux me lever sur une jambe depuis 40 cm, à droite et à gauche.','Je ne peux pas le faire, mais je peux me lever à deux jambes depuis 20 cm.','Je ne peux pas me lever à deux jambes depuis 20 cm, mais je peux depuis 30 cm.','Je ne peux pas me lever à deux jambes depuis 30 cm.'],
    twoEyebrow:'TEST 03 · LONGUEUR FONCTIONNELLE DU PAS', twoTitle:'Test des deux pas', twoHint:'Après un bref échauffement, faites deux grands pas contrôlés sans sauter. Réalisez deux essais et conservez la meilleure distance.', height:'Votre taille', distance:'Meilleure distance sur deux pas', ratio:'Valeur deux pas', show:'Voir mon résultat →', invalid:'Renseignez une taille de 120 à 230 cm et une distance de 40 à 500 cm.',
    resultEyebrow:'VOTRE REPÈRE LOCOMOTEUR', resultReady:'Votre résultat est prêt.', stage0:'Sous le seuil LS Stage 1', stage1:'LS Stage 1', stage2:'LS Stage 2', stage3:'LS Stage 3',
    resultBodies:['Aucun des trois tests n’atteint le seuil actuel du LS Stage 1 selon la JOA. C’est un point de repère, pas une garantie concernant votre mobilité future.','Au moins l’un des trois tests atteint le seuil JOA du LS Stage 1. Ce résultat peut servir de signal pour porter davantage d’attention à la mobilité et à la prévention.','Au moins un test atteint le seuil JOA du LS Stage 2. Une évaluation professionnelle peut aider à remettre ce résultat dans son contexte et à identifier les facteurs contributifs.','Au moins un test atteint le seuil JOA du LS Stage 3. Une évaluation clinique professionnelle est particulièrement pertinente lorsque les activités quotidiennes, la marche ou la participation sont limitées.'],
    glfs:'GLFS-25', stand:'Lever', two:'Deux pas', overall:'Repère global', clinicalCta:'Découvrir KŌMØ Clinical →', libraryCta:'Lire KŌMØ Library ↗', download:'Télécharger la carte résultat', share:'Partager', restart:'Recommencer', boundary:'KŌMØ Check est une expérience de dépistage fonctionnel à visée éducative et préventive. Il ne diagnostique pas une maladie, ne prédit pas une évolution individuelle et ne remplace pas l’examen d’un professionnel de santé. Demandez rapidement un avis professionnel en cas de limitation nouvelle ou qui s’aggrave rapidement, de chutes répétées, de faiblesse marquée, de douleur importante ou de symptômes neurologiques.',
    faqEyebrow:'LES QUESTIONS QUE L’ON SE POSE', faqTitle:'Comprendre le Check.<br><em>Sans ambiguïté.</em>', faqs:[['Comment tester sa mobilité chez soi ?','KŌMØ Check associe un questionnaire fonctionnel de 25 items au test de lever et au test des deux pas. Les tests physiques ne doivent être réalisés que dans un environnement sûr et sans douleur ni instabilité.'],['Qu’est-ce que la GLFS-25 ?','La Geriatric Locomotive Function Scale en 25 questions est un questionnaire publié pour évaluer les difficultés locomotrices perçues : douleur, activités quotidiennes, mobilité et participation.'],['Que signifie un stade LS ?','La Japanese Orthopaedic Association utilise des seuils issus de la GLFS-25, du test de lever et du test des deux pas. Le stade le plus avancé atteint par l’un des trois tests détermine le stade LS.'],['KŌMØ Check pose-t-il un diagnostic ?','Non. Il s’agit d’un dépistage fonctionnel orienté prévention. Un résultat ne permet pas d’établir la cause d’une limitation et ne remplace pas une évaluation médicale.'],['KŌMØ enregistre-t-il mes réponses ?','Pas sur cette page publique. Le calcul est réalisé localement dans votre navigateur et aucune réponse de santé n’est envoyée à KŌMØ par le Check.']],
    refsTitle:'Références scientifiques', footer:'Longévité locomotrice · Prévention · Continuité clinique', scienceLink:'Science & méthode', libraryLink:'KŌMØ Library'
  },
  es: {
    lang:'es', locale:'es_ES', title:'KŌMØ Check — Test gratuito de movilidad locomotora', description:'Evalúa tu movilidad con GLFS-25, el Stand-Up Test y el Two-Step Test. Gratis, sin registro y con resultado educativo inmediato.',
    home:'/es/', check:'/es/check/', clinical:'/es/clinical/', science:'/es/science/', library:'/es/media', locomotor:'/es/locomotor/', contact:'/es/contact/',
    navBack:'KŌMØ', eyebrow:'KŌMØ CHECK · PREVENCIÓN LOCOMOTORA', hero:'Evalúa tu movilidad locomotora.<br><em>En pocos minutos.</em>', lead:'Tres referencias complementarias — cuestionario, función de las extremidades inferiores y longitud funcional del paso — reunidas en una experiencia sencilla, privada y clara.',
    start:'Empezar KŌMØ Check →', method:'Entender el test ↓', facts:['Gratis','Sin cuenta','≈ 8 minutos','Cálculo en tu dispositivo'],
    methodEyebrow:'TRES REFERENCIAS COMPLEMENTARIAS', methodTitle:'Un cuestionario.<br><em>Dos pruebas funcionales.</em>', methodBody:'KŌMØ Check utiliza los tres elementos del Locomotive Syndrome Risk Test de la Japanese Orthopaedic Association. El estadio LS global corresponde al estadio más avanzado alcanzado por cualquiera de las tres pruebas; los resultados no se suman.',
    methods:[['GLFS-25','25 preguntas sobre dolor, actividades cotidianas, movilidad y participación durante el último mes.'],['Stand-Up Test','Una tarea funcional sencilla de las extremidades inferiores realizada desde alturas definidas.'],['Two-Step Test','Dos pasos amplios y controlados, normalizados por la altura, como referencia de longitud funcional del paso.']],
    privacy:'Tus respuestas permanecen en este navegador y esta página no las envía a KŌMØ.', progress:'Progreso', question:'Pregunta', of:'de', hint:'Elige la respuesta que mejor refleje el último mes.', back:'Atrás', continue:'Continuar →',
    standEyebrow:'TEST 02 · FUNCIÓN DE LAS EXTREMIDADES INFERIORES', standTitle:'Stand-Up Test', standHint:'Con los brazos cruzados, levántate sin impulso y mantén la posición durante 3 segundos. Selecciona el nivel más alto que puedas completar con seguridad.', standSafety:'Realiza esta prueba únicamente si te sientes estable y seguro/a. Hazla acompañado/a cuando sea apropiado, utiliza una superficie antideslizante y detente si aparece dolor, mareo o pérdida de equilibrio.',
    standOptions:['Puedo levantarme sobre una pierna desde 40 cm, tanto con la derecha como con la izquierda.','No puedo hacerlo, pero puedo levantarme con ambas piernas desde 20 cm.','No puedo levantarme con ambas piernas desde 20 cm, pero sí desde 30 cm.','No puedo levantarme con ambas piernas desde 30 cm.'],
    twoEyebrow:'TEST 03 · LONGITUD FUNCIONAL DEL PASO', twoTitle:'Two-Step Test', twoHint:'Tras un breve calentamiento, da dos pasos amplios y controlados sin saltar. Haz dos intentos y conserva la mejor distancia.', height:'Tu altura', distance:'Mejor distancia en dos pasos', ratio:'Valor two-step', show:'Ver mi resultado →', invalid:'Introduce una altura de 120 a 230 cm y una distancia de 40 a 500 cm.',
    resultEyebrow:'TU REFERENCIA LOCOMOTORA', resultReady:'Tu resultado está listo.', stage0:'Por debajo de LS Stage 1', stage1:'LS Stage 1', stage2:'LS Stage 2', stage3:'LS Stage 3',
    resultBodies:['Ninguna de las tres pruebas alcanza el umbral actual de LS Stage 1 de la JOA. Es un punto de referencia, no una garantía sobre tu movilidad futura.','Al menos una de las tres pruebas alcanza el umbral JOA de LS Stage 1. El resultado puede utilizarse como señal para prestar más atención a la movilidad y la prevención.','Al menos una prueba alcanza el umbral JOA de LS Stage 2. Una evaluación profesional puede ayudar a situar el resultado en contexto e identificar factores contribuyentes.','Al menos una prueba alcanza el umbral JOA de LS Stage 3. Una evaluación clínica profesional es especialmente apropiada cuando las actividades cotidianas, la marcha o la participación están limitadas.'],
    glfs:'GLFS-25', stand:'Stand-Up', two:'Two-Step', overall:'Referencia global', clinicalCta:'Descubrir KŌMØ Clinical →', libraryCta:'Leer KŌMØ Library ↗', download:'Descargar tarjeta de resultado', share:'Compartir', restart:'Reiniciar', boundary:'KŌMØ Check es una experiencia de cribado funcional con finalidad educativa y preventiva. No diagnostica una enfermedad, no predice una evolución individual y no sustituye la exploración de un profesional sanitario. Solicita asesoramiento profesional ante una limitación nueva o que empeora rápidamente, caídas repetidas, debilidad marcada, dolor importante o síntomas neurológicos.',
    faqEyebrow:'PREGUNTAS FRECUENTES', faqTitle:'Entender el Check.<br><em>Sin ambigüedad.</em>', faqs:[['¿Cómo puedo evaluar mi movilidad en casa?','KŌMØ Check combina un cuestionario funcional de 25 ítems con el Stand-Up Test y el Two-Step Test. Las pruebas físicas solo deben realizarse en un entorno seguro y sin dolor ni inestabilidad.'],['¿Qué es GLFS-25?','La Geriatric Locomotive Function Scale de 25 preguntas es un cuestionario publicado para valorar dificultades locomotoras percibidas relacionadas con dolor, actividades cotidianas, movilidad y participación.'],['¿Qué significa un estadio LS?','La Japanese Orthopaedic Association utiliza umbrales del GLFS-25, Stand-Up Test y Two-Step Test. El estadio más avanzado alcanzado por cualquiera de las tres pruebas determina el estadio LS.'],['¿KŌMØ Check es un diagnóstico?','No. Es un cribado funcional orientado a prevención. Un resultado no establece la causa de una limitación y no sustituye una evaluación médica.'],['¿KŌMØ guarda mis respuestas?','No en esta página pública. El cálculo se realiza localmente en tu navegador y el Check no envía respuestas de salud a KŌMØ.']],
    refsTitle:'Referencias científicas', footer:'Longevidad locomotora · Prevención · Continuidad clínica', scienceLink:'Ciencia y método', libraryLink:'KŌMØ Library'
  }
};

const questions = { en: sourceData.questions.en, fr: sourceData.questions.fr, es: esQuestionsData };
const paths = { en:'/check/', fr:'/fr/check/', es:'/es/check/' };
const esc = (s='') => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

function faqSchema(c){
  return c.faqs.map(([q,a])=>({ '@type':'Question', name:q, acceptedAnswer:{ '@type':'Answer', text:a } }));
}
function page(locale){
  const c=COPY[locale], canonical=`https://komolongevity.com${paths[locale]}`;
  const schema={ '@context':'https://schema.org','@graph':[{
    '@type':'WebPage','@id':canonical,name:c.title,description:c.description,url:canonical,inLanguage:locale,isPartOf:{'@type':'WebSite',name:'KŌMØ',url:'https://komolongevity.com/'},about:['locomotor mobility','Locomotive Syndrome','GLFS-25','Stand-Up Test','Two-Step Test']
  },{'@type':'FAQPage','@id':`${canonical}#faq`,mainEntity:faqSchema(c)}]};
  const data=JSON.stringify({copy:c,questions:questions[locale]}).replaceAll('<','\\u003c');
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f5f1e9"><meta name="color-scheme" content="light"><title>${esc(c.title)}</title><meta name="description" content="${esc(c.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="https://komolongevity.com/check/"><link rel="alternate" hreflang="fr" href="https://komolongevity.com/fr/check/"><link rel="alternate" hreflang="es" href="https://komolongevity.com/es/check/"><link rel="alternate" hreflang="x-default" href="https://komolongevity.com/check/"><meta property="og:type" content="website"><meta property="og:site_name" content="KŌMØ"><meta property="og:locale" content="${c.locale}"><meta property="og:title" content="${esc(c.title)}"><meta property="og:description" content="${esc(c.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://komolongevity.com/assets/og-komo.svg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>${tokens}\n${styles}</style></head><body><div class="kc-page">
<header class="kc-header"><div class="kc-shell kc-header__inner"><a class="kc-brand" href="${c.home}">KŌMØ</a><div class="kc-header__right"><a class="kc-back" href="${c.home}">← ${esc(c.navBack)}</a><div class="kc-langs" aria-label="Language"><a href="/check/" ${locale==='en'?'aria-current="page"':''}>EN</a><a href="/fr/check/" ${locale==='fr'?'aria-current="page"':''}>FR</a><a href="/es/check/" ${locale==='es'?'aria-current="page"':''}>ES</a></div></div></div></header>
<main><section class="kc-hero"><div class="kc-shell kc-hero__grid"><div><p class="kc-eyebrow">${esc(c.eyebrow)}</p><h1>${c.hero}</h1></div><div class="kc-hero__aside"><p>${esc(c.lead)}</p><div class="kc-actions"><a class="kc-btn" href="#check">${esc(c.start)}</a><a class="kc-btn kc-btn--quiet" href="#method">${esc(c.method)}</a></div><ul class="kc-meta">${c.facts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><div class="kc-shell kc-rule" aria-hidden="true"></div></section>
<section class="kc-section" id="method"><div class="kc-shell"><div class="kc-intro"><div><p class="kc-eyebrow">${esc(c.methodEyebrow)}</p><h2>${c.methodTitle}</h2></div><div class="kc-intro__body"><p>${esc(c.methodBody)}</p><p>${esc(c.privacy)}</p></div></div><ol class="kc-method">${c.methods.map((m,i)=>`<li><span>0${i+1}</span><div><h3>${esc(m[0])}</h3><p>${esc(m[1])}</p></div></li>`).join('')}</ol></div></section>
<section class="kc-app" id="check"><div class="kc-reading"><div class="kc-progress"><div class="kc-progress__top"><span>${esc(c.progress)}</span><strong data-progress>1 / 27</strong></div><div class="kc-progress__bar"><i data-bar></i></div></div><div class="kc-card" data-card></div></div></section>
<section class="kc-result" data-result hidden><div class="kc-shell kc-result__grid"><div><p class="kc-eyebrow">${esc(c.resultEyebrow)}</p><h2>${esc(c.resultReady)}</h2><p class="kc-stage" data-stage-title></p><p class="kc-result__lead" data-result-body></p><div class="kc-result__actions"><a class="kc-btn" href="${c.clinical}">${esc(c.clinicalCta)}</a><a class="kc-btn kc-btn--quiet" href="${c.library}">${esc(c.libraryCta)}</a><button class="kc-btn kc-btn--quiet" type="button" data-download>${esc(c.download)}</button><button class="kc-btn kc-btn--quiet" type="button" data-share>${esc(c.share)}</button><button class="kc-btn kc-btn--quiet" type="button" data-restart>${esc(c.restart)}</button></div><p class="kc-boundary">${esc(c.boundary)}</p></div><div class="kc-result__metrics"><div class="kc-metric"><span>${esc(c.overall)}</span><strong data-overall></strong></div><div class="kc-metric"><span>${esc(c.glfs)}</span><strong data-glfs></strong></div><div class="kc-metric"><span>${esc(c.stand)}</span><strong data-stand></strong></div><div class="kc-metric"><span>${esc(c.two)}</span><strong data-two></strong></div></div></div></section>
<section class="kc-faq" id="faq"><div class="kc-shell kc-faq__grid"><div><p class="kc-eyebrow">${esc(c.faqEyebrow)}</p><h2>${c.faqTitle}</h2></div><div class="kc-faq-list">${c.faqs.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div></div></section>
<section class="kc-references"><div class="kc-shell"><h2>${esc(c.refsTitle)}</h2><ol><li><span>Japanese Orthopaedic Association. Locomotive Syndrome Risk Test: Stand-Up Test, Two-Step Test and GLFS-25. <a href="https://locomo-joa.jp/en" rel="noreferrer">Official JOA resource ↗</a></span></li><li><span>Seichi A, Hoshino Y, Doi T, et al. Development of a screening tool for risk of locomotive syndrome in the elderly: the 25-question Geriatric Locomotive Function Scale. <em>J Orthop Sci.</em> 2012;17(2):163–172. doi:10.1007/s00776-011-0193-5. <a href="https://pubmed.ncbi.nlm.nih.gov/22222445/" rel="noreferrer">PubMed ↗</a></span></li><li><span>Locomotive syndrome clinical practice guide 2021 (Abridged Translation Version). <em>J Orthop Sci.</em> 2025;30(5):721–747. <a href="https://pubmed.ncbi.nlm.nih.gov/40634155/" rel="noreferrer">PubMed ↗</a></span></li></ol></div></section></main>
<footer class="kc-footer"><div class="kc-shell kc-footer__row"><span>© 2026 KŌMØ · ${esc(c.footer)}</span><span><a href="${c.science}">${esc(c.scienceLink)}</a> · <a href="${c.library}">${esc(c.libraryLink)}</a> · <a href="${c.contact}">Contact</a></span></div></footer>
<script>const DATA=${data};${clientJs}</script></div></body></html>`;
}

const clientJs = String.raw`(()=>{const C=DATA.copy,Q=DATA.questions,total=27,answers=Array(25).fill(null);let step=0,stand=null,height='',distance='',ratio=null;const card=document.querySelector('[data-card]'),p=document.querySelector('[data-progress]'),bar=document.querySelector('[data-bar]'),result=document.querySelector('[data-result]');const stages=[C.stage0,C.stage1,C.stage2,C.stage3];const glfsScore=()=>answers.reduce((s,v)=>s+(v??0),0);const glfsStage=s=>s>=24?3:s>=16?2:s>=7?1:0;const twoStage=r=>r>=1.3?0:r>=1.1?1:r>=.9?2:3;const progress=()=>{p.textContent=(step+1)+' / '+total;bar.style.width=((step+1)/total*100)+'%'};const nav=()=>'<div class="kc-nav"><button type="button" data-back>'+ (step>0?'← '+C.back:'') +'</button><button type="button" data-next>'+C.continue+'</button></div>';
function renderQuestion(){const [q,opts]=Q[step];card.innerHTML='<div class="kc-card__inner"><p class="kc-eyebrow">GLFS-25 · '+C.question+' '+(step+1)+'</p><p class="kc-count">'+C.question+' '+(step+1)+' '+C.of+' 25</p><h2 class="kc-question">'+q+'</h2><p class="kc-hint">'+C.hint+'</p><div class="kc-answers">'+opts.map((o,i)=>'<button class="kc-answer" type="button" data-answer="'+i+'" aria-pressed="'+(answers[step]===i)+'"><b>'+i+'</b><span>'+o+'</span></button>').join('')+'</div>'+nav()+'</div>';card.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[step]=+b.dataset.answer;renderQuestion()});bindNav()}
function renderStand(){card.innerHTML='<div class="kc-card__inner"><p class="kc-eyebrow">'+C.standEyebrow+'</p><h2 class="kc-question">'+C.standTitle+'</h2><p class="kc-hint">'+C.standHint+'</p><div class="kc-answers">'+C.standOptions.map((o,i)=>'<button class="kc-answer" type="button" data-stand="'+i+'" aria-pressed="'+(stand===i)+'"><b>'+i+'</b><span>'+o+'</span></button>').join('')+'</div><p class="kc-safety">'+C.standSafety+'</p>'+nav()+'</div>';card.querySelectorAll('[data-stand]').forEach(b=>b.onclick=()=>{stand=+b.dataset.stand;renderStand()});bindNav()}
function renderTwo(){const current=height&&distance?(+distance/+height):null;card.innerHTML='<div class="kc-card__inner"><p class="kc-eyebrow">'+C.twoEyebrow+'</p><h2 class="kc-question">'+C.twoTitle+'</h2><p class="kc-hint">'+C.twoHint+'</p><div class="kc-fields"><div class="kc-field"><label>'+C.height+'</label><div class="kc-input"><input inputmode="decimal" data-height value="'+height+'" aria-label="'+C.height+'"><span>cm</span></div></div><div class="kc-field"><label>'+C.distance+'</label><div class="kc-input"><input inputmode="decimal" data-distance value="'+distance+'" aria-label="'+C.distance+'"><span>cm</span></div></div></div><div class="kc-calc"><span>'+C.ratio+'</span><strong data-ratio>'+(current?current.toFixed(2):'—')+'</strong></div><p class="kc-safety">'+C.standSafety+'</p><p class="kc-error" data-error></p><div class="kc-nav"><button type="button" data-back>← '+C.back+'</button><button type="button" data-finish>'+C.show+'</button></div></div>';const h=card.querySelector('[data-height]'),d=card.querySelector('[data-distance]'),r=card.querySelector('[data-ratio]');const calc=()=>{height=h.value.replace(',','.');distance=d.value.replace(',','.');const v=+distance/+height;r.textContent=Number.isFinite(v)&&v>0?v.toFixed(2):'—'};h.oninput=calc;d.oninput=calc;card.querySelector('[data-back]').onclick=()=>{step=25;render()};card.querySelector('[data-finish]').onclick=()=>{height=h.value.replace(',','.');distance=d.value.replace(',','.');const H=+height,D=+distance;if(!(H>=120&&H<=230&&D>=40&&D<=500)){card.querySelector('[data-error]').textContent=C.invalid;return}ratio=D/H;showResult()}}
function bindNav(){const back=card.querySelector('[data-back]'),next=card.querySelector('[data-next]');if(back)back.onclick=()=>{if(step>0){step--;render()}};if(next)next.onclick=()=>{if(step<25&&answers[step]===null)return;if(step===25&&stand===null)return;if(step<26){step++;render()}}}
function render(){progress();result.hidden=true;if(step<25)renderQuestion();else if(step===25)renderStand();else renderTwo();window.scrollTo({top:document.querySelector('#check').offsetTop-58,behavior:'smooth'})}
function label(stage){return stages[stage]}function showResult(){const gs=glfsStage(glfsScore()),ts=twoStage(ratio),overall=Math.max(gs,stand,ts);document.querySelector('[data-stage-title]').textContent=label(overall);document.querySelector('[data-result-body]').textContent=C.resultBodies[overall];document.querySelector('[data-overall]').textContent=label(overall);document.querySelector('[data-glfs]').textContent=glfsScore()+'/100 · '+label(gs);document.querySelector('[data-stand]').textContent=label(stand);document.querySelector('[data-two]').textContent=ratio.toFixed(2)+' · '+label(ts);result.hidden=false;setTimeout(()=>result.scrollIntoView({behavior:'smooth',block:'start'}),50);window.__KOMO_RESULT={overall,gs,stand,ts,score:glfsScore(),ratio}}
function canvasBlob(){return new Promise(resolve=>{const r=window.__KOMO_RESULT,c=document.createElement('canvas');c.width=1200;c.height=630;const x=c.getContext('2d');x.fillStyle='#f5f1e9';x.fillRect(0,0,1200,630);x.fillStyle='#121410';x.font='700 28px Arial';x.fillText('KŌMØ',72,72);x.fillStyle='#5f6f64';x.font='700 16px Arial';x.fillText('KŌMØ CHECK · LOCOMOTOR REFERENCE',72,120);x.fillStyle='#121410';x.font='54px Georgia';x.fillText(label(r.overall),72,208);x.fillStyle='#707670';x.font='25px Georgia';x.fillText('GLFS-25  '+r.score+'/100',72,302);x.fillText('Stand-Up  '+label(r.stand),72,350);x.fillText('Two-Step  '+r.ratio.toFixed(2),72,398);x.fillStyle='#121410';x.fillRect(72,486,1056,1);x.fillStyle='#707670';x.font='18px Arial';x.fillText('Educational functional screening · Not a medical diagnosis · komolongevity.com/check',72,536);c.toBlob(resolve,'image/png')})}
document.querySelector('[data-restart]').onclick=()=>{answers.fill(null);step=0;stand=null;height='';distance='';ratio=null;render()};document.querySelector('[data-download]').onclick=async()=>{const b=await canvasBlob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='KOMO-Check-result.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};document.querySelector('[data-share]').onclick=async()=>{const b=await canvasBlob(),f=new File([b],'KOMO-Check-result.png',{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'KŌMØ Check'});return}if(navigator.share){await navigator.share({title:'KŌMØ Check',url:location.href});return}}catch(e){}await navigator.clipboard?.writeText(location.href)};render()})();`;

for (const locale of ['en','fr','es']) {
  const target = locale === 'en' ? join(siteDir,'check/index.html') : join(siteDir,locale,'check/index.html');
  await mkdir(dirname(target), {recursive:true});
  await writeFile(target, page(locale), 'utf8');
}

const sitemapPath=join(siteDir,'sitemap.xml');
try{
  let sitemap=await readFile(sitemapPath,'utf8');
  for(const url of ['https://komolongevity.com/check/','https://komolongevity.com/fr/check/','https://komolongevity.com/es/check/']) if(!sitemap.includes(`<loc>${url}</loc>`)) sitemap=sitemap.replace('</urlset>',`  <url><loc>${url}</loc></url>\n</urlset>`);
  await writeFile(sitemapPath,sitemap,'utf8');
}catch{}
console.log('[check-v2] generated /check, /fr/check and /es/check');