export const site = {
  origin: 'https://www.komolongevity.com',
  pages: ['index', 'pulse', 'clinical', 'white-coast', 'motion-retreats', 'library', 'circle', 'science', 'contact'],
  locales: ['fr', 'en', 'es']
};

const base = {
  fr: {
    code: 'FR',
    lang: 'fr',
    languageName: 'Français',
    nav: {
      pulse: 'Pulse', clinical: 'Clinical', whiteCoast: 'White Coast', retreats: 'Retreats', library: 'Bibliothèque', circle: 'Circle', science: 'Science', contact: 'Contact', score: 'Calculer mon Motion Score', menu: 'Ouvrir le menu', close: 'Fermer le menu'
    },
    global: {
      brandSubtitle: 'Longévité en mouvement',
      allRights: '© 2026 KŌMØ. Tous droits réservés.',
      footerCopy: 'Mesurer, comprendre et préserver la mobilité humaine tout au long de la vie.',
      madeBy: 'Conçu avec exigence clinique, pour la vraie vie.',
      legal: 'Mentions légales', privacy: 'Confidentialité', terms: 'Conditions',
      currentLanguage: 'FR',
      skip: 'Aller au contenu',
      explore: 'Explorer',
      discover: 'Découvrir',
      getStarted: 'Commencer',
      readMore: 'Lire le dossier',
      contactUs: 'Nous contacter',
      visit: 'Visiter le site',
      medicalNotice: 'Le Motion Score est un indicateur personnel éducatif. Il ne constitue pas un diagnostic, un avis médical ni une décision de soin.'
    },
    footer: {
      ecosystem: 'Écosystème',
      resources: 'Ressources',
      company: 'KŌMØ',
      links1: [['Pulse', 'pulse'], ['KŌMØ Clinical', 'clinical'], ['White Coast', 'white-coast'], ['Motion Retreats', 'motion-retreats']],
      links2: [['Bibliothèque', 'library'], ['Science & méthode', 'science'], ['KŌMØ Circle', 'circle'], ['Contact', 'contact']],
      links3: [['À propos', 'index'], ['contact@komolongevity.com', 'mailto:contact@komolongevity.com'], ['Instagram', 'https://www.instagram.com/komo_longevity/']]
    },
    home: {
      metaTitle: 'KŌMØ — Longévité en mouvement',
      metaDescription: 'KŌMØ relie la mesure de la mobilité, l’accompagnement clinique, les séjours et la communauté pour faire de la longévité locomotrice un nouveau standard.',
      eyebrow: 'KŌMØ · Locomotor Longevity Network',
      title: 'Votre corps.<br>Votre vie, <em>en mouvement.</em>',
      lead: 'KŌMØ relie votre parcours de santé, vos repères personnels, les lieux où vous vous ressourcez et les personnes qui rendent une longue vie plus vivante.',
      primaryCta: 'Calculer mon Motion Score',
      secondaryCta: 'Découvrir l’écosystème',
      trust: ['Gratuit · environ 10 minutes', 'Score éducatif, sans diagnostic en ligne', 'Votre parcours Pulse, à votre rythme'],
      objectKicker: 'Le fil qui relie', objectNumber: '01', objectTitle: 'Une mesure.<br>Une trajectoire.', objectText: 'Pulse fait le lien entre votre première lecture, les professionnels et les expériences qui comptent.',
      introEyebrow: 'La méthode KŌMØ',
      introTitle: 'Un point de départ.<br>Un écosystème <em>pour la suite.</em>',
      introLead: 'KŌMØ ne se résume pas à un score. Pulse garde le fil ; la médecine, les lieux, la communauté et le savoir donnent à cette continuité une réalité.',
      wheel: [
        {num: '01', title: 'Pulse & Clinical', text: 'Votre score, l’évaluation et le suivi, dans un parcours lisible.', link: 'Découvrir Pulse', page: 'pulse'},
        {num: '02', title: 'White Coast', text: 'Mouvement, récupération et art de vivre sur la Costa Blanca.', link: 'Découvrir White Coast', page: 'white-coast'},
        {num: '03', title: 'KŌMØ Library', text: 'Comprendre avec rigueur, avant d’agir et sans surpromettre.', link: 'Explorer la bibliothèque', page: 'library'},
        {num: '04', title: 'Circle', text: 'Des annonces, des rencontres et des connexions utiles dans la vraie vie.', link: 'Découvrir Circle', page: 'circle'}
      ],
      systemEyebrow: 'La longévité locomotrice',
      systemTitle: 'Continuer à bouger<br>comme on choisit <em>de vivre.</em>',
      systemLead: 'La mobilité ne se résume pas à une seule mesure. Elle s’appuie sur plusieurs capacités, à préserver dans le temps et à interpréter dans leur contexte.',
      capacities: [
        ['01', 'Force', 'Se lever, porter, pousser et contrôler l’effort dans les activités quotidiennes.'],
        ['02', 'Équilibre', 'Contrôler le corps à l’arrêt comme en déplacement, dans des situations simples ou complexes.'],
        ['03', 'Mobilité utile', 'Disposer des amplitudes et de la souplesse nécessaires à vos activités.'],
        ['04', 'Coordination', 'Organiser les gestes, les appuis et les adaptations à chaque déplacement.'],
        ['05', 'Posture', 'Répartir les contraintes et s’ajuster au mouvement plutôt que figer une position.'],
        ['06', 'Endurance', 'Maintenir l’activité et retrouver ses capacités après l’effort.']
      ],
      entryEyebrow: 'Choisir son entrée',
      entryTitle: 'Commencez par ce qui<br>vous amène <em>ici.</em>',
      entryLead: 'Mesurer, être accompagné, comprendre, se ressourcer ou rencontrer : chaque entrée est utile à elle seule. Pulse rend le passage d’une expérience à l’autre plus simple.',
      entries: [
        {eyebrow: '01 · Première mesure', title: 'Rendre votre mouvement lisible', text: 'Un Mobility Check guidé pour créer un premier repère personnel.', link: 'Commencer avec Pulse', page: 'pulse'},
        {eyebrow: '02 · Parcours clinique', title: 'Approfondir avec un professionnel', text: 'Une évaluation contextualisée, lorsque cela est pertinent.', link: 'Découvrir Clinical', page: 'clinical'},
        {eyebrow: '03 · Vivre sur la côte', title: 'Mieux vivre, ensemble', text: 'Une communauté locale née autour de Jávea, du mouvement et de la récupération.', link: 'Entrer dans White Coast', page: 'white-coast'},
        {eyebrow: '04 · Comprendre', title: 'Faire de la mobilité un sujet clair', text: 'Des dossiers et des repères qui expliquent sans inquiéter.', link: 'Explorer la bibliothèque', page: 'library'}
      ],
      pulseEyebrow: 'KŌMØ Pulse',
      pulseTitle: 'Une première mesure.<br>Une suite <em>possible.</em>',
      pulseText: 'Pulse relie l’évaluation réalisée chez soi, l’approfondissement clinique et le suivi. Chaque niveau a son rôle, avec une responsabilité médicale toujours claire.',
      pulseStats: [['10 min', 'pour un premier Mobility Check'], ['3 niveaux', 'chez soi, en clinique, dans le temps'], ['1 fil', 'vos repères réunis dans Pulse']],
      chapterEyebrow: 'White Coast Longevity · First Chapter',
      chapterTitle: 'Vivre plus longtemps.<br><em>Appartenir</em> quelque part.',
      chapterText: 'White Coast est la première expression locale de KŌMØ : une communauté sur la Costa Blanca qui relie le mouvement, la récupération, les expériences choisies et les personnes qui partagent une même ambition de longévité.',
      chapterCta: 'Découvrir le projet Jávea',
      chapterNotes: [['Territoire', 'Jávea · Dénia · Moraira · Altea'], ['Format', 'Community · Retreats · réseau local']],
      chapterQuote: 'Une vie plus longue mérite d’être <em>mieux habitée.</em>',
      scienceEyebrow: 'Science & méthode',
      scienceTitle: 'Mesurer avec méthode.<br>Expliquer <em>sans surpromettre.</em>',
      scienceLead: 'KŌMØ associe questionnaires fonctionnels, tests physiques, mesures supervisées et suivi longitudinal. Chaque composante est distinguée selon son niveau de preuve et son usage.',
      scienceCta: 'Découvrir la méthode scientifique',
      finalTitle: 'Mesurer aujourd’hui.<br>Vivre plus longtemps <em>en mouvement.</em>',
      finalText: 'Votre mobilité commence par une première mesure. Votre trajectoire continue dans KŌMØ.',
      finalCta: 'Calculer mon Motion Score'
    },
    pulse: {
      metaTitle: 'KŌMØ Pulse — Votre score, votre profil, votre trajectoire',
      metaDescription: 'Pulse relie votre Mobility Check éducatif, l’évaluation clinique lorsqu’elle est pertinente et le suivi de votre trajectoire de mobilité.',
      eyebrow: 'KŌMØ Pulse', title: 'Votre score.<br>Votre profil.<br><em>Votre trajectoire.</em>', lead: 'Votre espace personnel pour commencer par un Mobility Check gratuit, garder le fil de vos repères et aller plus loin avec un professionnel lorsque cela est pertinent.',
      cta: 'Créer mon espace Pulse', note: 'Gratuit · environ 10 minutes · indicateur éducatif · sans diagnostic en ligne',
      sections: [
        ['01 · À domicile', 'Motion Score', 'Une première lecture éducative, gratuite et guidée de votre mobilité.'],
        ['02 · En cabinet', 'KŌMØ Clinical', 'Un parcours supervisé qui approfondit et interprète les mesures dans Pulse.'],
        ['03 · En séjour', 'Motion Retreats', 'Un espace-temps pour travailler le mouvement, la récupération et la suite du parcours.'],
        ['04 · Dans le temps', 'Suivi', 'Vos résultats et vos nouvelles évaluations dans un espace qui vous suit réellement.']
      ],
      methodEyebrow: 'Première mesure', methodTitle: 'Trois composantes.<br>Une lecture <em>structurée.</em>', methodLead: 'Le Mobility Check associe un questionnaire fonctionnel et deux observations guidées inspirées de tests physiques. Il oriente ; il ne diagnostique pas et ne remplace pas les protocoles supervisés.',
      methodSteps: [
        ['01', 'Questionnaire fonctionnel', 'Décrivez votre mobilité ressentie, vos activités et les situations qui vous limitent.'],
        ['02', 'Observation de lever', 'Une observation guidée inspirée du Stand-Up Test, à réaliser uniquement si les conditions de sécurité sont réunies.'],
        ['03', 'Observation de deux pas', 'Deux pas contrôlés inspirés du Two-Step Test pour documenter une expression fonctionnelle du déplacement.']
      ],
      compareEyebrow: 'Deux cadres, deux rôles', compareTitle: 'Commencer chez soi.<br>Approfondir <em>avec un professionnel.</em>',
      compareHead: ['Dimension', 'Mobility Check', 'Évaluation clinique dans Pulse'],
      compareRows: [
        ['Cadre', 'Réalisé à domicile, si les conditions de sécurité sont réunies.', 'Réalisée avec un professionnel qualifié dans une structure appropriée.'],
        ['Mesures', 'Questionnaire et observations simples guidées.', 'Mesures standardisées, supervisées et, selon le lieu, instrumentées.'],
        ['Objectif', 'Orientation et compréhension personnelle.', 'Analyse approfondie, indication et interprétation clinique.'],
        ['Restitution', 'Motion Score et indicateurs éducatifs.', 'Rapport interprété et plan individualisé lorsque cela relève du professionnel.']
      ],
      finalTitle: 'Votre première lecture<br>peut devenir <em>une trajectoire.</em>', finalText: 'Pulse est le fil simple qui rend le parcours continuellement lisible, sans confondre information et décision médicale.'
    },
    clinical: {
      metaTitle: 'KŌMØ Clinical — Mesurer avec précision, restituer avec clarté',
      metaDescription: 'KŌMØ Clinical est un parcours professionnel en préparation : évaluation structurée, mesures pertinentes et responsabilité médicale claire.',
      eyebrow: 'KŌMØ Clinical · programme en préparation', title: 'Mesurer avec précision.<br>Restituer avec <em>clarté.</em>', lead: 'La méthode KŌMØ se déploie d’abord dans les pratiques qui portent déjà une responsabilité clinique. Le professionnel reste responsable de l’indication, de l’interprétation et des décisions.',
      cta: 'Exprimer mon intérêt professionnel', note: 'Les lieux, modalités d’accès et autorisations applicables sont publiés progressivement.',
      introEyebrow: 'Un cadre clinique responsable', introTitle: 'Plus de données.<br>Une responsabilité <em>claire.</em>', introLead: 'KŌMØ Clinical n’est pas une promesse générique. C’est un environnement conçu pour structurer le parcours, le suivi et la restitution dans une organisation de soin appropriée.',
      steps: [
        ['01', 'Préparer', 'Le patient retrouve son objectif et les informations utiles dans Pulse avant sa venue.'],
        ['02', 'Évaluer', 'Le professionnel précise l’indication, l’histoire fonctionnelle et les mesures pertinentes.'],
        ['03', 'Mesurer', 'Les tests sont réalisés dans un cadre supervisé et peuvent être complétés par des données instrumentées selon le centre.'],
        ['04', 'Comprendre', 'Le praticien contextualise les résultats, explique les priorités et valide la restitution.'],
        ['05', 'Suivre', 'De nouvelles mesures peuvent être reliées à la trajectoire, au rythme défini avec le professionnel.']
      ],
      contextsEyebrow: 'Pour les professionnels et les lieux', contextsTitle: 'Une méthode.<br>Plusieurs <em>contextes.</em>',
      contexts: [
        ['Cabinets & cliniques', 'Une évaluation locomotrice intégrée à une pratique de soin, avec un périmètre et une responsabilité définis.'],
        ['Instituts de longévité', 'Des parcours structurés qui font dialoguer mesure, suivi et expérience patient.'],
        ['Hospitality & destinations', 'Des programmes non cliniques conçus avec une frontière explicite entre bien-être, prévention et soin.'],
        ['Performance & clubs', 'Des repères fonctionnels pour suivre la progression au long cours, selon le contexte professionnel.']
      ],
      finalTitle: 'Commencer par la<br><em>bonne rencontre.</em>', finalText: 'Praticiens, centres et partenaires peuvent décrire leur projet ; les premières séquences de déploiement seront sélectives et progressives.'
    },
    whiteCoast: {
      metaTitle: 'White Coast Longevity — Le premier chapitre local de KŌMØ',
      metaDescription: 'White Coast Longevity est la première expression locale de KŌMØ sur la Costa Blanca : communauté, récupération, mouvement et expériences choisies.',
      eyebrow: 'White Coast Longevity · First Chapter', title: 'Une côte.<br>Un écosystème de <em>longévité.</em>', lead: 'Née autour de Jávea, White Coast relie le mouvement, la récupération, des lieux choisis et une communauté qui souhaite vivre longtemps avec plus de disponibilité.',
      cta: 'Entrer dans White Coast', note: 'Jávea · Dénia · Moraira · Altea · chapitre communautaire en développement',
      introEyebrow: 'La première expression locale', introTitle: 'La santé a besoin<br>d’un <em>contexte.</em>', introLead: 'White Coast ne remplace pas une prise en charge médicale. Elle crée un cadre de vie où les habitudes, les rencontres, les séjours et les professionnels qualifiés se renforcent mutuellement.',
      cards: [
        ['Mouvement', 'Sessions adaptées, mobilité, force et pratiques qui rendent le corps plus disponible au quotidien.'],
        ['Récupération', 'Sommeil, régulation, nutrition, chaleur, froid ou repos : des expériences choisies avec discernement.'],
        ['Séjours', 'Formats courts ou résidentiels dans des villas, hôtels et lieux partenaires sélectionnés.'],
        ['Rencontres', 'Tables, conversations et introductions avec les personnes qui façonnent un territoire plus vivant.']
      ],
      chapterEyebrow: 'Founding Community', chapterTitle: 'Une vie plus longue<br>est meilleure <em>partagée.</em>', chapterText: 'Le Founding Circle réunit des résidents, visiteurs, praticiens, hôteliers et partenaires qui veulent participer à la construction de la première communauté KŌMØ sur la Costa Blanca.',
      chapterCta: 'Rejoindre la communauté', chapterNotes: [['Un chapitre local', 'Un point d’entrée dans la vision KŌMØ'], ['Un cadre clair', 'Communauté et hospitalité ; le soin reste dans les structures autorisées']], chapterQuote: 'Move.<br>Recover.<br><em>Belong.</em>',
      finalTitle: 'Une communauté locale.<br>Une ambition <em>internationale.</em>', finalText: 'White Coast est la première porte d’entrée territoriale vers KŌMØ ; le parcours reste relié à Pulse et au réseau plus large.'
    },
    motionRetreats: {
      metaTitle: 'KŌMØ Motion Retreats — Changer de lieu, rester dans sa trajectoire',
      metaDescription: 'Des séjours KŌMØ conçus pour donner du temps au mouvement, à la récupération et à une longue vie active.',
      eyebrow: 'KŌMØ Motion Retreats · programme en développement', title: 'Changer de lieu.<br>Rester dans <em>sa trajectoire.</em>', lead: 'Des séjours conçus pour donner du temps au mouvement, à la récupération et à ce qui vous permet de vivre longtemps avec un corps disponible. Pulse reste le fil avant, pendant et après l’expérience.',
      cta: 'Découvrir White Coast', note: 'Costa Blanca · formats fondateurs en préparation',
      introEyebrow: 'Pourquoi un séjour ?', introTitle: 'La prévention a besoin<br>de <em>contexte.</em>', introLead: 'Un séjour bien construit ne promet pas une transformation instantanée. Il crée les conditions pour comprendre son point de départ, expérimenter de nouveaux rythmes et repartir avec une suite réaliste.',
      rhythm: [
        ['Premier jour', 'Comprendre son point de départ', 'Accueil, intention personnelle, mouvement accessible et premiers repères.'],
        ['Le corps en action', 'Bouger avec précision', 'Mobilité, force, respiration et temps dehors adaptés au format du séjour.'],
        ['Récupérer', 'Laisser le corps assimiler', 'Sommeil, récupération, alimentation et rythmes qui laissent une place au temps.'],
        ['Repartir', 'Rester dans la trajectoire', 'Une continuité simple dans Pulse, et des points d’ancrage pour le retour au quotidien.']
      ],
      carouselEyebrow: 'Les formats', carouselTitle: 'Des expériences qui donnent<br>du temps à <em>ce qui compte.</em>',
      carousel: [
        ['The Gathering', 'Une journée de mouvement, de conversations et de déjeuner côtier à Jávea.'],
        ['The Long Table', 'Un dîner au coucher du soleil pour les personnes qui construisent une vie plus longue sur cette côte.'],
        ['The Reset', 'Un format court pour remettre mouvement et récupération au centre, sans se couper du réel.'],
        ['The Residence', 'Un séjour résidentiel à petite échelle, dans des lieux choisis avec soin.']
      ],
      finalTitle: 'Loin du quotidien.<br>Proche de <em>votre vie réelle.</em>', finalText: 'Les Retreats KŌMØ sont en préparation. Ils seront révélés avec leurs partenaires, leurs cadres précis et des formats volontairement limités.'
    },
    library: {
      metaTitle: 'KŌMØ Library — Comprendre la mobilité, sans la simplifier',
      metaDescription: 'La bibliothèque KŌMØ rend la longévité locomotrice lisible : mouvement, force, équilibre, récupération et méthode.',
      eyebrow: 'KŌMØ Library', title: 'La mobilité,<br>rendue <em>lisible.</em>', lead: 'Des dossiers, références et repères clairs pour comprendre le mouvement, faire de la longévité un sujet intelligible et choisir sans se laisser guider par l’inquiétude.',
      cta: 'Découvrir mon Motion Score', note: 'Accès libre · sources et méthode distinguées · pas de diagnostic en ligne',
      introEyebrow: 'Comprendre avant d’agir', introTitle: 'Votre mobilité mérite mieux<br>qu’une <em>impression.</em>', introLead: 'Nous séparons les données établies, les repères utiles et ce qui reste à valider. Une information claire ne remplace jamais un avis professionnel lorsqu’il est nécessaire.',
      articles: [
        ['Fondations', 'Qu’est-ce que la longévité locomotrice ?', 'Une manière de penser la capacité à se déplacer, agir et rester autonome au fil du temps.'],
        ['Consensus & données établies', 'Comprendre le syndrome locomoteur', 'Le concept japonais qui relie appareil locomoteur, capacité de déplacement et participation à la vie quotidienne.'],
        ['Méthode KŌMØ', 'Ce que mesure le Mobility Check', 'Fonction ressentie, capacité de lever et capacité de pas : trois regards complémentaires.'],
        ['Capacités', 'Pourquoi la force change-t-elle avec l’âge ?', 'La force soutient le lever, le port de charge et les activités quotidiennes.'],
        ['Capacités', 'Équilibre : comprendre avant de prévenir', 'L’équilibre résulte d’une intégration visuelle, vestibulaire, sensitive et motrice.'],
        ['Préserver', 'Récupération : ce qui se passe entre deux efforts', 'La progression dépend aussi du sommeil, de la charge globale et du temps d’adaptation.']
      ],
      finalTitle: 'Faire de la mobilité<br>un sujet <em>compréhensible.</em>', finalText: 'La bibliothèque est gratuite. Pulse permet ensuite de garder les dossiers utiles et d’organiser votre parcours à votre rythme.'
    },
    circle: {
      metaTitle: 'KŌMØ Circle — Les bonnes personnes, au bon moment',
      metaDescription: 'KŌMØ Circle relie les annonces, les événements et les rencontres qui rendent le réseau vivant, en ligne comme dans la vraie vie.',
      eyebrow: 'KŌMØ Circle', title: 'Les bonnes personnes.<br>Au bon <em>moment.</em>', lead: 'Circle rassemble les annonces, les événements et les mises en relation qui permettent au réseau KŌMØ de prendre vie — avec de vrais lieux, de vrais échanges et des intentions claires.',
      cta: 'Recevoir les annonces', note: 'Un réseau en construction · événements et introductions annoncés progressivement',
      introEyebrow: 'Le réseau devient réel', introTitle: 'Une communauté ne se construit<br>pas dans <em>un fil d’actualité.</em>', introLead: 'Elle se construit en présence : par des conversations utiles, des formats bien pensés et les bonnes connexions entre personnes, lieux et projets.',
      cards: [
        ['Annonces', 'Les ouvertures, contenus et rendez-vous KŌMØ qui méritent votre attention.'],
        ['Événements', 'Des formats à petite échelle, physiques ou hybrides, construits autour d’un vrai sujet.'],
        ['Introductions', 'Des mises en relation qui ont une raison d’être : un besoin, un projet ou une idée à faire avancer.'],
        ['Chapitres', 'White Coast aujourd’hui ; demain, d’autres expressions locales liées par la même méthode.']
      ],
      finalTitle: 'Une vision globale.<br>Des liens <em>locaux.</em>', finalText: 'Circle ne cherche pas à faire du bruit. Il donne un lieu aux bonnes conversations et une continuité aux rencontres qui comptent.'
    },
    science: {
      metaTitle: 'Science KŌMØ — Méthode, transparence et validation progressive',
      metaDescription: 'KŌMØ documente ses mesures, distingue le niveau de preuve et construit ses validations progressivement avec des professionnels et partenaires méthodologiques.',
      eyebrow: 'Science KŌMØ · méthode & validation', title: 'Mesurer avec méthode.<br>Expliquer <em>sans surpromettre.</em>', lead: 'KŌMØ associe questionnaires fonctionnels, tests physiques, mesures supervisées et suivi longitudinal. Chaque composante doit indiquer son origine, ses limites et le cadre de son interprétation.',
      cta: 'Proposer une collaboration', note: 'Site informatif. Aucune visualisation ne constitue un dispositif médical validé ni une recommandation individuelle.',
      introEyebrow: 'Notre engagement méthodologique', introTitle: 'La rigueur est une<br>forme de <em>respect.</em>', introLead: 'Les personnes qui utilisent KŌMØ ont besoin de savoir ce qui est établi, ce qui est proposé comme repère et ce qui est encore en cours de validation.', underEgide: 'KŌMØ est développé sous la direction du Dr Renan Chapon, avec une exigence clinique et méthodologique explicite.',
      steps: [
        ['01', 'Protocoles documentés', 'Chaque test indique son origine, ses conditions de réalisation, ses limites et les exigences de sécurité.'],
        ['02', 'Responsabilité identifiée', 'Le contenu éducatif, la mesure guidée et l’interprétation clinique ne sont jamais confondus.'],
        ['03', 'Données contextualisées', 'Les résultats n’ont de valeur que dans un parcours, un état de santé et un objectif qui leur donnent du sens.'],
        ['04', 'Validation progressive', 'Ce qui relève encore de la recherche est présenté comme tel, avant toute affirmation clinique.']
      ],
      finalTitle: 'Confronter la méthode<br>au <em>réel.</em>', finalText: 'KŌMØ recherche des praticiens et partenaires méthodologiques pour le POC, la reproductibilité inter-opérateur, les seuils et la validation prospective.'
    },
    contact: {
      metaTitle: 'Contacter KŌMØ — Longévité locomotrice',
      metaDescription: 'Contactez KŌMØ pour une question, un projet professionnel, une collaboration ou un projet territorial.',
      eyebrow: 'Contact KŌMØ', title: 'Une question.<br>Un projet.<br><em>Une conversation.</em>', lead: 'Vous souhaitez en savoir plus sur KŌMØ, imaginer un déploiement professionnel, parler d’un lieu ou d’une collaboration ? Écrivez-nous.',
      cta: 'Écrire à KŌMØ', note: 'Nous répondons aux demandes pertinentes pour les personnes, les professionnels et les partenaires.',
      formTitle: 'Parlons de votre projet.', formLead: 'Laissez vos coordonnées et le contexte de votre demande. Nous reviendrons vers vous avec la bonne personne ou la bonne prochaine étape.',
      fields: {name: 'Nom complet', email: 'Adresse e-mail', subject: 'Votre sujet', message: 'Votre message', consent: 'J’accepte que KŌMØ utilise ces informations pour répondre à ma demande.', submit: 'Envoyer ma demande'},
      asideTitle: 'KŌMØ se construit avec<br>des personnes et des <em>lieux engagés.</em>', asideText: 'Pour une demande de presse, de partenariat ou une question générale, vous pouvez aussi nous écrire directement.',
      direct: 'contact@komolongevity.com', finalTitle: 'La bonne suite commence<br>souvent par <em>une discussion.</em>', finalText: 'KŌMØ avance avec ambition, mais à un rythme compatible avec la qualité de ce que nous construisons.'
    }
  },
  en: {
    code: 'EN', lang: 'en', languageName: 'English',
    nav: {pulse: 'Pulse', clinical: 'Clinical', whiteCoast: 'White Coast', retreats: 'Retreats', library: 'Library', circle: 'Circle', science: 'Science', contact: 'Contact', score: 'Explore your mobility', menu: 'Open menu', close: 'Close menu'},
    global: {brandSubtitle: 'Longevity in motion', allRights: '© 2026 KŌMØ. All rights reserved.', footerCopy: 'Measure, understand and preserve human mobility throughout life.', madeBy: 'Built with clinical rigour, for real life.', legal: 'Legal notice', privacy: 'Privacy', terms: 'Terms', currentLanguage: 'EN', skip: 'Skip to content', explore: 'Explore', discover: 'Discover', getStarted: 'Get started', readMore: 'Read the story', contactUs: 'Contact us', visit: 'Visit website', medicalNotice: 'The Motion Score is a personal educational indicator. It is not a diagnosis, medical advice or a care decision.'},
    footer: {ecosystem: 'Ecosystem', resources: 'Resources', company: 'KŌMØ', links1: [['Pulse', 'pulse'], ['KŌMØ Clinical', 'clinical'], ['White Coast', 'white-coast'], ['Motion Retreats', 'motion-retreats']], links2: [['Library', 'library'], ['Science & method', 'science'], ['KŌMØ Circle', 'circle'], ['Contact', 'contact']], links3: [['About', 'index'], ['contact@komolongevity.com', 'mailto:contact@komolongevity.com'], ['Instagram', 'https://www.instagram.com/komo_longevity/']]},
    home: {
      metaTitle: 'KŌMØ — Longevity in motion', metaDescription: 'KŌMØ connects mobility measurement, clinical guidance, retreats and community to make locomotor longevity a new standard.', eyebrow: 'KŌMØ · Locomotor Longevity Network', title: 'Your body.<br>Your life, <em>in motion.</em>', lead: 'KŌMØ turns mobility from a feeling into a trajectory — connecting your personal reference points, clinical expertise, restorative places and the people who make a longer life more alive.', primaryCta: 'Explore your mobility', secondaryCta: 'Discover the ecosystem', trust: ['Educational orientation · not an online diagnosis', 'Clinical assessment when it is relevant', 'One trajectory, at your own pace'], objectKicker: 'The thread that connects', objectNumber: '01', objectTitle: 'Access.<br>Understand.<br>Continue.', objectText: 'Pulse connects your first reading, qualified professionals and the experiences that support your next step.',
      introEyebrow: 'The KŌMØ method', introTitle: 'One starting point.<br>An ecosystem <em>for what follows.</em>', introLead: 'KŌMØ is more than a score. Pulse keeps the thread; medicine, places, community and knowledge make that continuity real.',
      wheel: [
        {num: '01', title: 'Pulse & Clinical', text: 'Your score, assessment and follow-up in one understandable journey.', link: 'Discover Pulse', page: 'pulse'},
        {num: '02', title: 'White Coast', text: 'Movement, recovery and a way of life on the Costa Blanca.', link: 'Discover White Coast', page: 'white-coast'},
        {num: '03', title: 'KŌMØ Library', text: 'Understand with rigour before acting, without overpromising.', link: 'Explore the library', page: 'library'},
        {num: '04', title: 'Circle', text: 'Announcements, encounters and useful connections in real life.', link: 'Discover Circle', page: 'circle'}
      ],
      systemEyebrow: 'Locomotor longevity', systemTitle: 'Keep moving<br>the way you choose <em>to live.</em>', systemLead: 'Mobility cannot be reduced to a single measure. It relies on several abilities, to be preserved over time and interpreted in context.', capacities: [['01','Strength','Getting up, carrying, pushing and controlling effort in everyday life.'],['02','Balance','Controlling the body at rest and while moving, in simple or complex situations.'],['03','Useful mobility','Having the range and flexibility required for your activities.'],['04','Coordination','Organising movements, support and adaptations for every displacement.'],['05','Posture','Distributing load and adapting to movement instead of fixing a position.'],['06','Endurance','Maintaining activity and recovering capacity after effort.']],
      entryEyebrow: 'Choose your entry point', entryTitle: 'Start with what<br>brings you <em>here.</em>', entryLead: 'Measure, get support, understand, restore or meet: every entry point matters on its own. Pulse makes the transition between experiences simpler.', entries: [
        {eyebrow:'01 · First measurement',title:'Make your movement readable',text:'A guided Mobility Check to create a first personal reference point.',link:'Start with Pulse',page:'pulse'},
        {eyebrow:'02 · Clinical journey',title:'Go further with a professional',text:'A contextualised assessment, whenever it is relevant.',link:'Discover Clinical',page:'clinical'},
        {eyebrow:'03 · Living on the coast',title:'Live better, together',text:'A local community born around Jávea, movement and recovery.',link:'Enter White Coast',page:'white-coast'},
        {eyebrow:'04 · Understand',title:'Make mobility a clear subject',text:'Stories and reference points that explain without alarming.',link:'Explore the library',page:'library'}
      ],
      pulseEyebrow:'KŌMØ Pulse',pulseTitle:'A first measurement.<br>A <em>possible next step.</em>',pulseText:'Pulse connects the KŌMØ Locomo Check, clinician-led assessment and follow-up. Each level has a distinct role, with medical responsibility always clear.',pulseStats:[['10 min','to explore your mobility'],['3 levels','access, clinical assessment, follow-up'],['1 thread','your reference points in Pulse']],
      chapterEyebrow:'White Coast Longevity · First Chapter',chapterTitle:'Live longer.<br><em>Belong</em> somewhere.',chapterText:'White Coast is KŌMØ’s first local expression: a Costa Blanca community connecting movement, recovery, selected experiences and people who share a longevity ambition.',chapterCta:'Discover the Jávea project',chapterNotes:[['Territory','Jávea · Dénia · Moraira · Altea'],['Format','Community · Retreats · local network']],chapterQuote:'A longer life deserves to be <em>better inhabited.</em>',
      scienceEyebrow:'Science & method',scienceTitle:'Measure with method.<br>Explain <em>without overpromising.</em>',scienceLead:'KŌMØ brings together functional questionnaires, physical tests, supervised measures and longitudinal follow-up. Every component is distinguished by its level of evidence and use.',scienceCta:'Discover the scientific method',finalTitle:'Measure today.<br>Live longer <em>in motion.</em>',finalText:'Your mobility starts with a first measurement. Your trajectory continues in KŌMØ.',finalCta:'Explore your mobility'
    },
    pulse: {metaTitle:'KŌMØ Pulse — Your score, your profile, your trajectory',metaDescription:'Pulse connects your educational KŌMØ Locomo Check, clinical assessment when relevant and follow-up for your mobility trajectory.',eyebrow:'KŌMØ Pulse',title:'Your movement.<br>Your profile.<br><em>Your trajectory.</em>',lead:'Your personal continuity layer: start by exploring your mobility, keep your reference points, and go further with a professional whenever it is relevant.',cta:'Explore the KŌMØ Locomo Check',note:'Educational orientation · around 10 minutes · no online diagnosis',sections:[['01 · Access','KŌMØ Locomo Check','A guided educational first reading of your mobility and the right next question.'],['02 · In clinic','KŌMØ Clinical Assessment','A clinician-led journey that deepens and interprets appropriate measures in Pulse.'],['03 · In real life','Motion Retreats & network','Time and context to work on movement, recovery and what comes next.'],['04 · Over time','KŌMØ Follow','Your results and repeat assessments in a space that truly follows you.']],methodEyebrow:'First access',methodTitle:'Three components.<br>One <em>structured orientation.</em>',methodLead:'The KŌMØ Locomo Check combines a functional questionnaire and two guided observations inspired by physical tests. It helps orient the next step; it does not diagnose and cannot replace supervised protocols.',methodSteps:[['01','Functional questionnaire','Describe your perceived mobility, your activities and situations that limit you.'],['02','Sit-to-stand observation','A guided observation inspired by the Stand-Up Test, only when safety conditions are met.'],['03','Two-step observation','Two controlled steps inspired by the Two-Step Test, documenting a functional expression of displacement.']],compareEyebrow:'Two settings, two roles',compareTitle:'Explore at home.<br>Go further <em>with a professional.</em>',compareHead:['Dimension','KŌMØ Locomo Check','KŌMØ Clinical Assessment'],compareRows:[['Setting','Completed at home when safety conditions are met.','Completed with a qualified professional in an appropriate setting.'],['Measures','Questionnaire and simple guided observations.','Standardised, supervised and, depending on the location, instrumented measures.'],['Purpose','Orientation and personal understanding.','Deeper analysis, clinical indication and interpretation.'],['Feedback','Educational reference points and a suggested next question.','Interpreted report and individual plan when this belongs to the professional.']],finalTitle:'Your first reading<br>can become <em>a trajectory.</em>',finalText:'Pulse is the simple continuity layer that keeps the journey readable without confusing information with medical decisions.'},
    clinical: {metaTitle:'KŌMØ Clinical — Measure precisely, explain clearly',metaDescription:'KŌMØ Clinical is a professional pathway in development: structured assessment, relevant measures and clear medical responsibility.',eyebrow:'KŌMØ Clinical · programme in development',title:'Measure precisely.<br>Explain with <em>clarity.</em>',lead:'The KŌMØ method first deploys in practices that already carry clinical responsibility. The professional remains responsible for indication, interpretation and decisions.',cta:'Register professional interest',note:'Locations, access terms and applicable authorisations are published progressively.',introEyebrow:'A responsible clinical framework',introTitle:'More data.<br>Clear <em>responsibility.</em>',introLead:'KŌMØ Clinical is not a generic promise. It is an environment designed to structure the journey, follow-up and feedback within an appropriate care organisation.',steps:[['01','Prepare','The patient finds their objective and useful information in Pulse before the visit.'],['02','Assess','The professional clarifies indication, functional history and relevant measures.'],['03','Measure','Tests are carried out under supervision and may be complemented by instrumented data depending on the centre.'],['04','Understand','The practitioner contextualises results, explains priorities and validates the feedback.'],['05','Follow','Further measurements may be connected to the trajectory at the pace agreed with the professional.']],contextsEyebrow:'For professionals and places',contextsTitle:'One method.<br>Several <em>contexts.</em>',contexts:[['Practices & clinics','A locomotor assessment integrated into a care practice, with a defined scope and responsibility.'],['Longevity institutes','Structured journeys that bring measurement, follow-up and patient experience together.'],['Hospitality & destinations','Non-clinical programmes designed with a clear boundary between wellbeing, prevention and care.'],['Performance & clubs','Functional reference points to follow long-term progress, according to professional context.']],finalTitle:'Start with the<br><em>right conversation.</em>',finalText:'Practitioners, centres and partners can describe their project; the first deployment sequences will be selective and progressive.'},
    whiteCoast: {metaTitle:'White Coast Longevity — KŌMØ’s first local chapter',metaDescription:'White Coast Longevity is KŌMØ’s first local expression on the Costa Blanca: community, recovery, movement and selected experiences.',eyebrow:'White Coast Longevity · First Chapter',title:'One coast.<br>One longevity <em>ecosystem.</em>',lead:'Born around Jávea, White Coast connects movement, recovery, selected places and a community that wants to live longer with more availability.',cta:'Enter White Coast',note:'Jávea · Dénia · Moraira · Altea · community chapter in development',introEyebrow:'The first local expression',introTitle:'Health needs<br><em>context.</em>',introLead:'White Coast does not replace medical care. It creates a way of life in which habits, encounters, retreats and qualified professionals reinforce each other.',cards:[['Movement','Adapted sessions, mobility, strength and practices that make the body more available every day.'],['Recovery','Sleep, regulation, nutrition, heat, cold or rest: selected experiences used with discernment.'],['Retreats','Short or residential formats in selected villas, hotels and partner locations.'],['Encounters','Tables, conversations and introductions with people shaping a more alive territory.']],chapterEyebrow:'Founding Community',chapterTitle:'A longer life<br>is better <em>shared.</em>',chapterText:'The Founding Circle brings together residents, visitors, practitioners, hoteliers and partners who want to help build the first KŌMØ community on the Costa Blanca.',chapterCta:'Join the community',chapterNotes:[['A local chapter','A gateway to the wider KŌMØ vision'],['A clear framework','Community and hospitality; care stays within authorised structures']],chapterQuote:'Move.<br>Recover.<br><em>Belong.</em>',finalTitle:'A local community.<br>An <em>international</em> ambition.',finalText:'White Coast is the first territorial gateway into KŌMØ; the journey remains connected to Pulse and the wider network.'},
    motionRetreats: {metaTitle:'KŌMØ Motion Retreats — Change location, stay in your trajectory',metaDescription:'KŌMØ retreats are designed to make time for movement, recovery and a long, active life.',eyebrow:'KŌMØ Motion Retreats · programme in development',title:'Change location.<br>Stay in <em>your trajectory.</em>',lead:'Retreats designed to make time for movement, recovery and the things that let you live longer with a more available body. Pulse remains the thread before, during and after the experience.',cta:'Discover White Coast',note:'Costa Blanca · founding formats in development',introEyebrow:'Why a retreat?',introTitle:'Prevention needs<br><em>context.</em>',introLead:'A well-designed retreat does not promise an instant transformation. It creates the conditions to understand where you are, try new rhythms and leave with a realistic next step.',rhythm:[['Day one','Understand your starting point','Arrival, personal intention, accessible movement and first reference points.'],['Body in action','Move with precision','Mobility, strength, breathing and time outdoors suited to the retreat format.'],['Recover','Let the body assimilate','Sleep, recovery, food and rhythms that leave room for time.'],['Return','Stay on the trajectory','A simple continuity in Pulse and anchors for returning to everyday life.']],carouselEyebrow:'The formats',carouselTitle:'Experiences that make time<br>for <em>what matters.</em>',carousel:[['The Gathering','A day of movement, conversation and coastal lunch in Jávea.'],['The Long Table','A sunset supper for people building a longer, better life on this coast.'],['The Reset','A short format to bring movement and recovery back to the centre without disconnecting from real life.'],['The Residence','A small-scale residential stay in carefully selected locations.']],finalTitle:'Away from routine.<br>Close to <em>real life.</em>',finalText:'KŌMØ Retreats are in development. They will be revealed with partners, clear frameworks and deliberately limited formats.'},
    library: {metaTitle:'KŌMØ Library — Understand mobility without oversimplifying it',metaDescription:'The KŌMØ Library makes locomotor longevity readable: movement, strength, balance, recovery and method.',eyebrow:'KŌMØ Library',title:'Mobility,<br>made <em>readable.</em>',lead:'Stories, references and clear guideposts to understand movement, make longevity intelligible and choose without being led by anxiety.',cta:'Discover my Motion Score',note:'Open access · sources and method clearly separated · no online diagnosis',introEyebrow:'Understand before acting',introTitle:'Your mobility deserves more<br>than <em>a feeling.</em>',introLead:'We separate established data, useful guideposts and what still needs validation. Clear information never replaces professional advice when it is needed.',articles:[['Foundations','What is locomotor longevity?','A way to think about the ability to move, act and remain autonomous over time.'],['Consensus & established evidence','Understanding locomotor syndrome','The Japanese concept connecting the locomotor system, ability to move and participation in daily life.'],['KŌMØ method','What the Mobility Check measures','Perceived function, sit-to-stand ability and step ability: three complementary views.'],['Capacities','Why does strength change with age?','Strength supports standing, carrying load and everyday activity.'],['Capacities','Balance: understand before preventing','Balance results from visual, vestibular, sensory and motor integration.'],['Preserve','Recovery: what happens between two efforts','Progress also depends on sleep, overall load and time to adapt.']],finalTitle:'Make mobility<br>an <em>understandable</em> subject.',finalText:'The library is free. Pulse then makes it possible to keep useful stories and organise your journey at your own pace.'},
    circle: {metaTitle:'KŌMØ Circle — The right people, at the right time',metaDescription:'KŌMØ Circle connects announcements, events and encounters that make the network alive online and in real life.',eyebrow:'KŌMØ Circle',title:'The right people.<br>At the right <em>time.</em>',lead:'Circle gathers announcements, events and introductions that allow the KŌMØ network to come alive — with real places, real exchanges and clear intentions.',cta:'Receive announcements',note:'A network in development · events and introductions announced progressively',introEyebrow:'When the network becomes real',introTitle:'Community is not built<br>in <em>a newsfeed.</em>',introLead:'It is built in person: through useful conversations, well-designed formats and the right connections between people, places and projects.',cards:[['Announcements','The KŌMØ openings, content and appointments that are worth your attention.'],['Events','Small-scale physical or hybrid formats built around a real subject.'],['Introductions','Connections that have a reason to exist: a need, a project or an idea to move forward.'],['Chapters','White Coast today; tomorrow, other local expressions linked by the same method.']],finalTitle:'A global vision.<br>Local <em>ties.</em>',finalText:'Circle is not trying to make noise. It gives a place to meaningful conversation and continuity to encounters that matter.'},
    science: {metaTitle:'KŌMØ Science — Method, transparency and progressive validation',metaDescription:'KŌMØ documents its measures, distinguishes evidence levels and builds validation progressively with clinicians and methodological partners.',eyebrow:'KŌMØ Science · method & validation',title:'Measure with method.<br>Explain <em>without overpromising.</em>',lead:'KŌMØ brings together functional questionnaires, physical tests, supervised measures and longitudinal follow-up. Every component should show its origin, limits and interpretation framework.',cta:'Propose a collaboration',note:'Informational website. No visualisation constitutes a validated medical device or individual recommendation.',introEyebrow:'Our methodological commitment',introTitle:'Rigour is a form<br>of <em>respect.</em>',introLead:'People who use KŌMØ deserve to know what is established, what is offered as a guidepost and what is still being validated.',underEgide:'KŌMØ is developed under the clinical direction of Dr Renan Chapon, with an explicit clinical and methodological standard.',steps:[['01','Documented protocols','Every test shows its origin, conditions of use, limitations and safety requirements.'],['02','Identified responsibility','Educational content, guided measurement and clinical interpretation are never confused.'],['03','Contextualised data','Results only matter within a journey, health status and objective that give them meaning.'],['04','Progressive validation','What remains research is presented as such before any clinical claim.']],finalTitle:'Bring the method<br>into the <em>real world.</em>',finalText:'KŌMØ is looking for clinicians and methodological partners for POC work, inter-operator reproducibility, thresholds and prospective validation.'},
    contact: {metaTitle:'Contact KŌMØ — Locomotor longevity',metaDescription:'Contact KŌMØ about a question, professional project, collaboration or territorial project.',eyebrow:'Contact KŌMØ',title:'A question.<br>A project.<br><em>A conversation.</em>',lead:'Would you like to learn more about KŌMØ, imagine a professional deployment, discuss a place or a collaboration? Write to us.',cta:'Write to KŌMØ',note:'We reply to relevant requests from individuals, professionals and partners.',formTitle:'Tell us about your project.',formLead:'Leave your contact details and the context of your request. We will return to you with the right person or next step.',fields:{name:'Full name',email:'Email address',subject:'Your topic',message:'Your message',consent:'I agree that KŌMØ may use this information to reply to my request.',submit:'Send my request'},asideTitle:'KŌMØ is being built with<br>committed people and <em>places.</em>',asideText:'For press, partnership or general questions, you can also contact us directly.',direct:'contact@komolongevity.com',finalTitle:'The right next step often starts<br>with <em>a conversation.</em>',finalText:'KŌMØ moves with ambition, at a pace that respects the quality of what we are building.'}
  },
  es: {
    code: 'ES', lang: 'es', languageName: 'Español',
    nav: {pulse:'Pulse',clinical:'Clinical',whiteCoast:'White Coast',retreats:'Retreats',library:'Biblioteca',circle:'Circle',science:'Ciencia',contact:'Contacto',score:'Calcular mi Motion Score',menu:'Abrir menú',close:'Cerrar menú'},
    global: {brandSubtitle:'Longevidad en movimiento',allRights:'© 2026 KŌMØ. Todos los derechos reservados.',footerCopy:'Medir, comprender y preservar la movilidad humana durante toda la vida.',madeBy:'Diseñado con rigor clínico, para la vida real.',legal:'Aviso legal',privacy:'Privacidad',terms:'Condiciones',currentLanguage:'ES',skip:'Ir al contenido',explore:'Explorar',discover:'Descubrir',getStarted:'Empezar',readMore:'Leer el dossier',contactUs:'Contactar',visit:'Visitar el sitio',medicalNotice:'El Motion Score es un indicador educativo personal. No constituye un diagnóstico, un consejo médico ni una decisión asistencial.'},
    footer: {ecosystem:'Ecosistema',resources:'Recursos',company:'KŌMØ',links1:[['Pulse','pulse'],['KŌMØ Clinical','clinical'],['White Coast','white-coast'],['Motion Retreats','motion-retreats']],links2:[['Biblioteca','library'],['Ciencia y método','science'],['KŌMØ Circle','circle'],['Contacto','contact']],links3:[['Acerca de','index'],['contact@komolongevity.com','mailto:contact@komolongevity.com'],['Instagram','https://www.instagram.com/komo_longevity/']]},
    home: {
      metaTitle:'KŌMØ — Longevidad en movimiento',metaDescription:'KŌMØ conecta la medición de la movilidad, el acompañamiento clínico, los retiros y la comunidad para convertir la longevidad locomotora en un nuevo estándar.',eyebrow:'KŌMØ · Locomotor Longevity Network',title:'Tu cuerpo.<br>Tu vida, <em>en movimiento.</em>',lead:'KŌMØ conecta tu recorrido de salud, tus referencias personales, los lugares que te restauran y las personas que hacen que una vida más larga sea más viva.',primaryCta:'Calcular mi Motion Score',secondaryCta:'Descubrir el ecosistema',trust:['Gratis · unos 10 minutos','Puntuación educativa, sin diagnóstico online','Tu recorrido Pulse, a tu ritmo'],objectKicker:'El hilo que conecta',objectNumber:'01',objectTitle:'Una medición.<br>Una trayectoria.',objectText:'Pulse conecta tu primera lectura, los profesionales y las experiencias que importan.',
      introEyebrow:'El método KŌMØ',introTitle:'Un punto de partida.<br>Un ecosistema <em>para lo que sigue.</em>',introLead:'KŌMØ es más que una puntuación. Pulse mantiene el hilo; la medicina, los lugares, la comunidad y el conocimiento hacen real esa continuidad.',wheel:[{num:'01',title:'Pulse & Clinical',text:'Tu puntuación, evaluación y seguimiento en un recorrido comprensible.',link:'Descubrir Pulse',page:'pulse'},{num:'02',title:'White Coast',text:'Movimiento, recuperación y una forma de vivir en la Costa Blanca.',link:'Descubrir White Coast',page:'white-coast'},{num:'03',title:'KŌMØ Library',text:'Comprender con rigor antes de actuar, sin prometer de más.',link:'Explorar la biblioteca',page:'library'},{num:'04',title:'Circle',text:'Anuncios, encuentros y conexiones útiles en la vida real.',link:'Descubrir Circle',page:'circle'}],
      systemEyebrow:'Longevidad locomotora',systemTitle:'Seguir moviéndote<br>como eliges <em>vivir.</em>',systemLead:'La movilidad no se reduce a una sola medida. Se apoya en varias capacidades, que se deben preservar en el tiempo e interpretar en su contexto.',capacities:[['01','Fuerza','Levantarse, cargar, empujar y controlar el esfuerzo en las actividades cotidianas.'],['02','Equilibrio','Controlar el cuerpo en reposo y en movimiento, en situaciones simples o complejas.'],['03','Movilidad útil','Disponer del rango y la flexibilidad necesarios para tus actividades.'],['04','Coordinación','Organizar los gestos, los apoyos y las adaptaciones en cada desplazamiento.'],['05','Postura','Distribuir las cargas y adaptarse al movimiento en lugar de fijar una posición.'],['06','Resistencia','Mantener la actividad y recuperar capacidad después del esfuerzo.']],
      entryEyebrow:'Elige tu puerta de entrada',entryTitle:'Empieza por lo que<br>te trae <em>aquí.</em>',entryLead:'Medir, recibir apoyo, comprender, recuperarse o encontrarse: cada puerta de entrada importa por sí misma. Pulse hace más sencillo pasar de una experiencia a otra.',entries:[{eyebrow:'01 · Primera medición',title:'Hacer legible tu movimiento',text:'Un Mobility Check guiado para crear una primera referencia personal.',link:'Empezar con Pulse',page:'pulse'},{eyebrow:'02 · Recorrido clínico',title:'Profundizar con un profesional',text:'Una evaluación contextualizada, cuando sea relevante.',link:'Descubrir Clinical',page:'clinical'},{eyebrow:'03 · Vivir en la costa',title:'Vivir mejor, juntos',text:'Una comunidad local nacida alrededor de Jávea, el movimiento y la recuperación.',link:'Entrar en White Coast',page:'white-coast'},{eyebrow:'04 · Comprender',title:'Hacer de la movilidad un tema claro',text:'Dossiers y referencias que explican sin alarmar.',link:'Explorar la biblioteca',page:'library'}],
      pulseEyebrow:'KŌMØ Pulse',pulseTitle:'Una primera medición.<br>Un siguiente paso <em>posible.</em>',pulseText:'Pulse conecta la evaluación realizada en casa, la profundización clínica y el seguimiento. Cada nivel tiene su función, con una responsabilidad médica siempre clara.',pulseStats:[['10 min','para un primer Mobility Check'],['3 niveles','en casa, en clínica, en el tiempo'],['1 hilo','tus referencias reunidas en Pulse']],chapterEyebrow:'White Coast Longevity · First Chapter',chapterTitle:'Vivir más tiempo.<br><em>Pertenecer</em> a algún lugar.',chapterText:'White Coast es la primera expresión local de KŌMØ: una comunidad en la Costa Blanca que conecta movimiento, recuperación, experiencias seleccionadas y personas que comparten una misma ambición de longevidad.',chapterCta:'Descubrir el proyecto Jávea',chapterNotes:[['Territorio','Jávea · Dénia · Moraira · Altea'],['Formato','Comunidad · Retreats · red local']],chapterQuote:'Una vida más larga merece estar <em>mejor habitada.</em>',scienceEyebrow:'Ciencia y método',scienceTitle:'Medir con método.<br>Explicar <em>sin prometer de más.</em>',scienceLead:'KŌMØ combina cuestionarios funcionales, pruebas físicas, medidas supervisadas y seguimiento longitudinal. Cada componente se distingue según su nivel de evidencia y su uso.',scienceCta:'Descubrir el método científico',finalTitle:'Medir hoy.<br>Vivir más tiempo <em>en movimiento.</em>',finalText:'Tu movilidad empieza con una primera medición. Tu trayectoria continúa en KŌMØ.',finalCta:'Calcular mi Motion Score'
    },
    pulse: {metaTitle:'KŌMØ Pulse — Tu puntuación, tu perfil, tu trayectoria',metaDescription:'Pulse conecta tu Mobility Check educativo, la evaluación clínica cuando es relevante y el seguimiento de tu trayectoria de movilidad.',eyebrow:'KŌMØ Pulse',title:'Tu puntuación.<br>Tu perfil.<br><em>Tu trayectoria.</em>',lead:'Tu espacio personal para empezar con un Mobility Check gratuito, conservar tus referencias y profundizar con un profesional cuando sea relevante.',cta:'Crear mi espacio Pulse',note:'Gratis · unos 10 minutos · indicador educativo · sin diagnóstico online',sections:[['01 · En casa','Motion Score','Una primera lectura educativa, gratuita y guiada de tu movilidad.'],['02 · En consulta','KŌMØ Clinical','Un recorrido supervisado que profundiza e interpreta las medidas en Pulse.'],['03 · En retreat','Motion Retreats','Tiempo y espacio para trabajar el movimiento, la recuperación y la siguiente etapa.'],['04 · En el tiempo','Seguimiento','Tus resultados y evaluaciones futuras en un espacio que realmente te acompaña.']],methodEyebrow:'Primera medición',methodTitle:'Tres componentes.<br>Una lectura <em>estructurada.</em>',methodLead:'El Mobility Check combina un cuestionario funcional y dos observaciones guiadas inspiradas en pruebas físicas. Orienta; no diagnostica y no sustituye los protocolos supervisados.',methodSteps:[['01','Cuestionario funcional','Describe tu movilidad percibida, tus actividades y las situaciones que te limitan.'],['02','Observación de levantarse','Una observación guiada inspirada en el Stand-Up Test, solo si se cumplen las condiciones de seguridad.'],['03','Observación de dos pasos','Dos pasos controlados inspirados en el Two-Step Test para documentar una expresión funcional del desplazamiento.']],compareEyebrow:'Dos contextos, dos funciones',compareTitle:'Empezar en casa.<br>Profundizar <em>con un profesional.</em>',compareHead:['Dimensión','Mobility Check','Evaluación clínica en Pulse'],compareRows:[['Marco','Realizado en casa si se cumplen las condiciones de seguridad.','Realizado con un profesional cualificado en una estructura apropiada.'],['Medidas','Cuestionario y observaciones simples guiadas.','Medidas estandarizadas, supervisadas y, según el lugar, instrumentadas.'],['Objetivo','Orientación y comprensión personal.','Análisis profundo, indicación e interpretación clínica.'],['Devolución','Motion Score e indicadores educativos.','Informe interpretado y plan individual cuando corresponde al profesional.']],finalTitle:'Tu primera lectura<br>puede convertirse en <em>una trayectoria.</em>',finalText:'Pulse es el hilo sencillo que mantiene legible el recorrido sin confundir información con decisiones médicas.'},
    clinical: {metaTitle:'KŌMØ Clinical — Medir con precisión, explicar con claridad',metaDescription:'KŌMØ Clinical es un recorrido profesional en desarrollo: evaluación estructurada, medidas pertinentes y responsabilidad médica clara.',eyebrow:'KŌMØ Clinical · programa en desarrollo',title:'Medir con precisión.<br>Explicar con <em>claridad.</em>',lead:'El método KŌMØ se despliega primero en prácticas que ya asumen una responsabilidad clínica. El profesional sigue siendo responsable de la indicación, la interpretación y las decisiones.',cta:'Registrar interés profesional',note:'Los lugares, condiciones de acceso y autorizaciones aplicables se publican progresivamente.',introEyebrow:'Un marco clínico responsable',introTitle:'Más datos.<br>Responsabilidad <em>clara.</em>',introLead:'KŌMØ Clinical no es una promesa genérica. Es un entorno pensado para estructurar el recorrido, el seguimiento y la devolución dentro de una organización asistencial apropiada.',steps:[['01','Preparar','El paciente encuentra su objetivo y la información útil en Pulse antes de la visita.'],['02','Evaluar','El profesional aclara la indicación, la historia funcional y las medidas pertinentes.'],['03','Medir','Las pruebas se realizan bajo supervisión y pueden complementarse con datos instrumentados según el centro.'],['04','Comprender','El profesional contextualiza los resultados, explica las prioridades y valida la devolución.'],['05','Seguir','Las nuevas mediciones pueden vincularse a la trayectoria al ritmo acordado con el profesional.']],contextsEyebrow:'Para profesionales y lugares',contextsTitle:'Un método.<br>Varios <em>contextos.</em>',contexts:[['Consultas y clínicas','Una evaluación locomotora integrada en una práctica asistencial, con alcance y responsabilidad definidos.'],['Institutos de longevidad','Recorridos estructurados que conectan medición, seguimiento y experiencia del paciente.'],['Hospitality y destinos','Programas no clínicos diseñados con una frontera clara entre bienestar, prevención y asistencia.'],['Rendimiento y clubes','Referencias funcionales para seguir el progreso a largo plazo según el contexto profesional.']],finalTitle:'Empezar con la<br><em>conversación adecuada.</em>',finalText:'Los profesionales, centros y socios pueden describir su proyecto; las primeras secuencias de despliegue serán selectivas y progresivas.'},
    whiteCoast: {metaTitle:'White Coast Longevity — El primer capítulo local de KŌMØ',metaDescription:'White Coast Longevity es la primera expresión local de KŌMØ en la Costa Blanca: comunidad, recuperación, movimiento y experiencias seleccionadas.',eyebrow:'White Coast Longevity · First Chapter',title:'Una costa.<br>Un ecosistema de <em>longevidad.</em>',lead:'Nacida alrededor de Jávea, White Coast conecta movimiento, recuperación, lugares seleccionados y una comunidad que quiere vivir más tiempo con mayor disponibilidad.',cta:'Entrar en White Coast',note:'Jávea · Dénia · Moraira · Altea · capítulo comunitario en desarrollo',introEyebrow:'La primera expresión local',introTitle:'La salud necesita<br><em>contexto.</em>',introLead:'White Coast no sustituye la atención médica. Crea una forma de vida en la que los hábitos, los encuentros, los retiros y los profesionales cualificados se refuerzan mutuamente.',cards:[['Movimiento','Sesiones adaptadas, movilidad, fuerza y prácticas que hacen el cuerpo más disponible cada día.'],['Recuperación','Sueño, regulación, nutrición, calor, frío o descanso: experiencias seleccionadas con criterio.'],['Retreats','Formatos breves o residenciales en villas, hoteles y lugares asociados seleccionados.'],['Encuentros','Mesas, conversaciones e introducciones con las personas que dan forma a un territorio más vivo.']],chapterEyebrow:'Founding Community',chapterTitle:'Una vida más larga<br>se vive mejor <em>compartida.</em>',chapterText:'El Founding Circle reúne residentes, visitantes, profesionales, hoteleros y socios que quieren ayudar a construir la primera comunidad KŌMØ en la Costa Blanca.',chapterCta:'Unirse a la comunidad',chapterNotes:[['Un capítulo local','Una puerta de entrada a la visión KŌMØ'],['Un marco claro','Comunidad y hospitality; la asistencia permanece en estructuras autorizadas']],chapterQuote:'Move.<br>Recover.<br><em>Belong.</em>',finalTitle:'Una comunidad local.<br>Una ambición <em>internacional.</em>',finalText:'White Coast es la primera puerta territorial hacia KŌMØ; el recorrido permanece conectado a Pulse y a la red más amplia.'},
    motionRetreats: {metaTitle:'KŌMØ Motion Retreats — Cambiar de lugar, seguir en tu trayectoria',metaDescription:'Los retiros KŌMØ están pensados para dar tiempo al movimiento, la recuperación y una vida larga y activa.',eyebrow:'KŌMØ Motion Retreats · programa en desarrollo',title:'Cambiar de lugar.<br>Seguir en <em>tu trayectoria.</em>',lead:'Retreats diseñados para dar tiempo al movimiento, la recuperación y a lo que permite vivir más tiempo con un cuerpo más disponible. Pulse sigue siendo el hilo antes, durante y después de la experiencia.',cta:'Descubrir White Coast',note:'Costa Blanca · formatos fundadores en desarrollo',introEyebrow:'¿Por qué un retiro?',introTitle:'La prevención necesita<br><em>contexto.</em>',introLead:'Un retiro bien diseñado no promete una transformación inmediata. Crea las condiciones para entender dónde estás, probar nuevos ritmos y volver con una siguiente etapa realista.',rhythm:[['Primer día','Comprender tu punto de partida','Llegada, intención personal, movimiento accesible y primeras referencias.'],['El cuerpo en acción','Moverse con precisión','Movilidad, fuerza, respiración y tiempo al aire libre adecuados al formato del retiro.'],['Recuperar','Dejar que el cuerpo asimile','Sueño, recuperación, alimentación y ritmos que dejan espacio al tiempo.'],['Volver','Mantener la trayectoria','Una continuidad sencilla en Pulse y anclajes para volver a la vida cotidiana.']],carouselEyebrow:'Los formatos',carouselTitle:'Experiencias que dan tiempo<br>a <em>lo que importa.</em>',carousel:[['The Gathering','Un día de movimiento, conversación y almuerzo costero en Jávea.'],['The Long Table','Una cena al atardecer para personas que construyen una vida más larga y mejor en esta costa.'],['The Reset','Un formato breve para volver a poner movimiento y recuperación en el centro sin desconectarse de la vida real.'],['The Residence','Una estancia residencial a pequeña escala en lugares cuidadosamente seleccionados.']],finalTitle:'Lejos de la rutina.<br>Cerca de <em>la vida real.</em>',finalText:'Los KŌMØ Retreats están en desarrollo. Se revelarán con sus socios, marcos claros y formatos deliberadamente limitados.'},
    library: {metaTitle:'KŌMØ Library — Comprender la movilidad sin simplificarla',metaDescription:'La biblioteca KŌMØ hace legible la longevidad locomotora: movimiento, fuerza, equilibrio, recuperación y método.',eyebrow:'KŌMØ Library',title:'La movilidad,<br>hecha <em>legible.</em>',lead:'Dossiers, referencias y puntos de apoyo claros para comprender el movimiento, hacer inteligible la longevidad y elegir sin dejarse guiar por la ansiedad.',cta:'Descubrir mi Motion Score',note:'Acceso abierto · fuentes y método diferenciados · sin diagnóstico online',introEyebrow:'Comprender antes de actuar',introTitle:'Tu movilidad merece más<br>que <em>una impresión.</em>',introLead:'Separamos los datos establecidos, las referencias útiles y lo que aún requiere validación. Una información clara nunca sustituye el consejo profesional cuando se necesita.',articles:[['Fundamentos','¿Qué es la longevidad locomotora?','Una forma de pensar la capacidad de moverse, actuar y mantener la autonomía en el tiempo.'],['Consenso y datos establecidos','Comprender el síndrome locomotor','El concepto japonés que conecta el aparato locomotor, la capacidad de desplazamiento y la participación en la vida cotidiana.'],['Método KŌMØ','Qué mide el Mobility Check','Función percibida, capacidad de levantarse y capacidad de paso: tres miradas complementarias.'],['Capacidades','¿Por qué cambia la fuerza con la edad?','La fuerza sostiene levantarse, cargar peso y las actividades cotidianas.'],['Capacidades','Equilibrio: comprender antes de prevenir','El equilibrio resulta de una integración visual, vestibular, sensitiva y motora.'],['Preservar','Recuperación: lo que ocurre entre dos esfuerzos','El progreso depende también del sueño, la carga global y el tiempo de adaptación.']],finalTitle:'Hacer de la movilidad<br>un tema <em>comprensible.</em>',finalText:'La biblioteca es gratuita. Pulse permite después conservar los dossiers útiles y organizar tu recorrido a tu ritmo.'},
    circle: {metaTitle:'KŌMØ Circle — Las personas adecuadas, en el momento adecuado',metaDescription:'KŌMØ Circle conecta anuncios, eventos y encuentros que hacen viva la red tanto online como en la vida real.',eyebrow:'KŌMØ Circle',title:'Las personas adecuadas.<br>En el momento <em>adecuado.</em>',lead:'Circle reúne los anuncios, eventos e introducciones que permiten a la red KŌMØ cobrar vida: con lugares reales, intercambios reales e intenciones claras.',cta:'Recibir anuncios',note:'Una red en desarrollo · eventos e introducciones anunciados progresivamente',introEyebrow:'Cuando la red se vuelve real',introTitle:'Una comunidad no se construye<br>en <em>un feed.</em>',introLead:'Se construye en presencia: a través de conversaciones útiles, formatos bien pensados y las conexiones correctas entre personas, lugares y proyectos.',cards:[['Anuncios','Las aperturas, contenidos y citas KŌMØ que merecen tu atención.'],['Eventos','Formatos físicos o híbridos a pequeña escala, construidos alrededor de un tema real.'],['Introducciones','Conexiones con razón de ser: una necesidad, un proyecto o una idea que hacer avanzar.'],['Capítulos','White Coast hoy; mañana, otras expresiones locales unidas por el mismo método.']],finalTitle:'Una visión global.<br>Vínculos <em>locales.</em>',finalText:'Circle no busca hacer ruido. Da un lugar a las conversaciones valiosas y continuidad a los encuentros que importan.'},
    science: {metaTitle:'KŌMØ Ciencia — Método, transparencia y validación progresiva',metaDescription:'KŌMØ documenta sus mediciones, distingue los niveles de evidencia y construye la validación progresivamente con clínicos y socios metodológicos.',eyebrow:'KŌMØ Ciencia · método y validación',title:'Medir con método.<br>Explicar <em>sin prometer de más.</em>',lead:'KŌMØ combina cuestionarios funcionales, pruebas físicas, medidas supervisadas y seguimiento longitudinal. Cada componente debe mostrar su origen, límites y marco de interpretación.',cta:'Proponer una colaboración',note:'Sitio informativo. Ninguna visualización constituye un dispositivo médico validado ni una recomendación individual.',introEyebrow:'Nuestro compromiso metodológico',introTitle:'El rigor es una forma<br>de <em>respeto.</em>',introLead:'Las personas que usan KŌMØ merecen saber qué está establecido, qué se ofrece como referencia y qué sigue en validación.',underEgide:'KŌMØ se desarrolla bajo la dirección clínica del Dr. Renan Chapon, con una exigencia clínica y metodológica explícita.',steps:[['01','Protocolos documentados','Cada prueba indica su origen, condiciones de uso, límites y requisitos de seguridad.'],['02','Responsabilidad identificada','El contenido educativo, la medición guiada y la interpretación clínica nunca se confunden.'],['03','Datos contextualizados','Los resultados solo tienen valor dentro de un recorrido, un estado de salud y un objetivo que les dan sentido.'],['04','Validación progresiva','Lo que sigue siendo investigación se presenta como tal antes de cualquier afirmación clínica.']],finalTitle:'Confrontar el método<br>con <em>la realidad.</em>',finalText:'KŌMØ busca clínicos y socios metodológicos para POC, reproducibilidad inter-operador, umbrales y validación prospectiva.'},
    contact: {metaTitle:'Contactar KŌMØ — Longevidad locomotora',metaDescription:'Contacta con KŌMØ sobre una pregunta, proyecto profesional, colaboración o proyecto territorial.',eyebrow:'Contacto KŌMØ',title:'Una pregunta.<br>Un proyecto.<br><em>Una conversación.</em>',lead:'¿Quieres saber más sobre KŌMØ, imaginar un despliegue profesional, hablar de un lugar o una colaboración? Escríbenos.',cta:'Escribir a KŌMØ',note:'Respondemos a solicitudes relevantes de personas, profesionales y socios.',formTitle:'Hablemos de tu proyecto.',formLead:'Déjanos tus datos de contacto y el contexto de tu solicitud. Volveremos con la persona o el siguiente paso adecuado.',fields:{name:'Nombre completo',email:'Dirección de correo',subject:'Tu tema',message:'Tu mensaje',consent:'Acepto que KŌMØ use esta información para responder a mi solicitud.',submit:'Enviar mi solicitud'},asideTitle:'KŌMØ se construye con<br>personas y lugares <em>comprometidos.</em>',asideText:'Para prensa, alianzas o preguntas generales, también puedes escribirnos directamente.',direct:'contact@komolongevity.com',finalTitle:'El siguiente paso adecuado empieza a menudo<br>con <em>una conversación.</em>',finalText:'KŌMØ avanza con ambición, a un ritmo que respeta la calidad de lo que estamos construyendo.'}
  }
};

export const translations = base;
