import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const URL='https://uqlolefsiktbznnymriy.supabase.co',KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n',REM='komo_pulse_remember';
let client=null,running=false,lastRender=0;
function storage(){return localStorage.getItem(REM)==='1'?localStorage:sessionStorage}
function sb(){return window.KomoRuntime?.client||(client||(client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})))}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]))}
function money(cents,currency='EUR'){const n=Number(cents);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:currency||'EUR'}).format(n/100)}catch{return`${(n/100).toFixed(2)} €`}}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function status(v){return({paid:'Payé',succeeded:'Payé',pending:'En attente',created:'À régler',cancelled:'Annulé',canceled:'Annulé',failed:'Échec',refunded:'Remboursé'})[v]||String(v||'En attente')}
function locale(){const l=(document.documentElement.lang||'fr').toLowerCase();return l.startsWith('es')?'es':l.startsWith('en')?'en':'fr'}
function legalUrl(path){const l=locale();return`https://komolongevity.com/${l==='en'?'':`${l}/`}${path}/`}
async function data(){const c=sb(),{data:{session}}=await c.auth.getSession();if(!session?.user)return null;const p=await c.from('patients').select('id').eq('patient_user_id',session.user.id);const ids=(p.data||[]).map(x=>x.id);let payments=[];if(ids.length){const q=await c.from('payment_orders').select('id,patient_id,purpose,amount_cents,currency,status,created_at,updated_at').in('patient_id',ids).order('created_at',{ascending:false}).limit(12);if(!q.error)payments=q.data||[]}return{session,payments}}
function paymentRows(items){if(!items.length)return'<div class="kah-empty">Aucun paiement enregistré pour le moment. Quand la facturation KŌMØ sera activée pour votre bilan, vos transactions et justificatifs apparaîtront ici.</div>';return`<div class="kah-billing">${items.map(x=>`<div class="kah-payment"><div><span>${esc(date(x.created_at))}</span><strong>${esc(x.purpose||'Prestation KŌMØ')}</strong><small>${esc(status(x.status))}</small></div><div class="amount">${esc(money(x.amount_cents,x.currency))}</div></div>`).join('')}</div>`}
function legal(){return`<section class="kah-card kah-full kah-legal"><div class="kah-head"><div><p class="eyebrow">DOCUMENTS OFFICIELS</p><h3>Cadre légal & confidentialité.</h3><p>Les informations juridiques de référence sont publiées sur le site KŌMØ et restent accessibles à tout moment.</p></div><span class="kah-pill">Documents KŌMØ</span></div><div class="kah-links"><a href="${legalUrl('privacy')}" target="_blank" rel="noopener">Confidentialité <span>↗</span></a><a href="${legalUrl('terms')}" target="_blank" rel="noopener">Conditions d’utilisation <span>↗</span></a><a href="${legalUrl('medical-information')}" target="_blank" rel="noopener">Information médicale <span>↗</span></a><a href="${legalUrl('legal')}" target="_blank" rel="noopener">Mentions légales <span>↗</span></a><a href="${legalUrl('cookies')}" target="_blank" rel="noopener">Cookies <span>↗</span></a><a href="${legalUrl('intellectual-property')}" target="_blank" rel="noopener">Propriété intellectuelle <span>↗</span></a></div></section>`}
async function render(){if(location.hash!=='#profile'||running)return;const host=document.querySelector('[data-profile-v2]');if(!host||host.querySelector('[data-account-hub-v2]'))return;running=true;try{const d=await data();if(!d)return;const eyebrow=document.querySelector('#pageEyebrow'),title=document.querySelector('#pageTitle');if(eyebrow)eyebrow.textContent='KŌMØ PULSE · MON COMPTE';if(title)title.textContent='Mon compte';const section=document.createElement('section');section.className='kah';section.dataset.accountHubV2='1';section.innerHTML=`<div class="kah-grid"><article class="kah-card"><div class="kah-head"><div><p class="eyebrow">FACTURATION</p><h3>Paiements & justificatifs.</h3><p>Retrouvez ici les paiements liés à votre parcours KŌMØ.</p></div><span class="kah-pill">Compte patient</span></div>${paymentRows(d.payments)}</article><article class="kah-card"><div class="kah-head"><div><p class="eyebrow">KŌMØ</p><h3>Comprendre votre parcours.</h3><p>Pulse est votre espace personnel. Le site principal rassemble la méthode, la science et le réseau KŌMØ.</p></div></div><div class="kah-links"><a href="https://komolongevity.com/fr/" target="_blank" rel="noopener">Site KŌMØ <span>↗</span></a><a href="https://komolongevity.com/fr/method/" target="_blank" rel="noopener">Méthode <span>↗</span></a><a href="https://komolongevity.com/fr/science/" target="_blank" rel="noopener">Science <span>↗</span></a><a href="https://komolongevity.com/fr/network/" target="_blank" rel="noopener">Réseau <span>↗</span></a><a href="https://komolongevity.com/fr/media" target="_blank" rel="noopener">Library <span>↗</span></a><a href="https://komolongevity.com/fr/contact/" target="_blank" rel="noopener">Contact <span>↗</span></a></div></article>${legal()}</div>`;host.appendChild(section);lastRender=Date.now()}catch(e){console.error('[account-hub-v2]',e)}finally{running=false}}
function schedule(){if(location.hash!=='#profile')return;for(const ms of [80,350,950])setTimeout(()=>{if(!document.querySelector('[data-account-hub-v2]')&&Date.now()-lastRender>250)render()},ms)}
window.addEventListener('hashchange',schedule);window.addEventListener('komo:route-ready',schedule);document.addEventListener('DOMContentLoaded',schedule);schedule();
