import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const URL='https://uqlolefsiktbznnymriy.supabase.co',KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n',REM='komo_pulse_remember';
let client=null,running=false,timer=null;
function storage(){return localStorage.getItem(REM)==='1'?localStorage:sessionStorage}
function sb(){return window.KomoRuntime?.client||(client||(client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})))}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function money(cents,currency='EUR'){const n=Number(cents);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:currency||'EUR'}).format(n/100)}catch{return`${(n/100).toFixed(2)} €`}}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function status(v){return({paid:'Payé',succeeded:'Payé',pending:'En attente',created:'À régler',cancelled:'Annulé',canceled:'Annulé',failed:'Échec',refunded:'Remboursé'})[v]||String(v||'En attente')}
async function data(){const c=sb(),{data:{session}}=await c.auth.getSession();if(!session?.user)return null;const p=await c.from('patients').select('id').eq('patient_user_id',session.user.id);const ids=(p.data||[]).map(x=>x.id);let payments=[];if(ids.length){const q=await c.from('payment_orders').select('id,patient_id,purpose,amount_cents,currency,status,created_at,updated_at').in('patient_id',ids).order('created_at',{ascending:false}).limit(12);if(!q.error)payments=q.data||[]}return{session,payments}}
function paymentRows(items){if(!items.length)return'<div class="kah-empty">Aucun paiement enregistré pour le moment. Quand la facturation KŌMØ sera activée pour votre bilan, vos transactions et justificatifs apparaîtront ici.</div>';return`<div class="kah-billing">${items.map(x=>`<div class="kah-payment"><div><span>${esc(date(x.created_at))}</span><strong>${esc(x.purpose||'Prestation KŌMØ')}</strong><small>${esc(status(x.status))}</small></div><div class="amount">${esc(money(x.amount_cents,x.currency))}</div></div>`).join('')}</div>`}
function legal(){return`<section class="kah-card kah-full kah-legal"><div class="kah-head"><div><p class="eyebrow">CONDITIONS & INFORMATIONS</p><h3>Première base contractuelle KŌMØ.</h3><p>Une version volontairement courte et lisible, à finaliser avant l’ouverture commerciale des paiements.</p></div><span class="kah-pill">Préparatoire · 26 août 2026</span></div><div class="kah-legal-note"><strong>Version non contractuelle.</strong> L’identité juridique de la future entité KŌMØ, son siège, son immatriculation, son numéro de TVA le cas échéant, les prix définitifs, les règles d’annulation et le dispositif de règlement des litiges seront complétés avant toute vente au public.</div>
<details><summary>1. Objet et périmètre <span>+</span></summary><div class="kah-legal-body"><p>Les présentes conditions ont vocation à encadrer l’accès à KŌMØ Pulse, la réservation d’un bilan et, lorsque cela sera activé, le paiement de prestations ou services KŌMØ.</p><p><b>KŌMØ Start / Pulse Free</b> constitue un repère fonctionnel de dépistage et de suivi. Il ne constitue pas un diagnostic médical. <b>KŌMØ Motion</b> correspond à une évaluation fonctionnelle et instrumentée réalisée dans un centre autorisé. <b>KŌMØ Clinical</b> ajoute une lecture clinique lorsque celle-ci est indiquée et réalisée par un professionnel habilité.</p></div></details>
<details><summary>2. Réservation, prix et paiement <span>+</span></summary><div class="kah-legal-body"><p>Avant toute confirmation payante, le patient devra pouvoir connaître de manière lisible la prestation choisie, son prix total en euros toutes taxes comprises lorsqu’il y a lieu, le centre concerné, la date, l’heure et les conditions particulières d’exécution.</p><p>Les moyens de paiement et le prestataire de paiement seront identifiés au moment de l’activation du module. Pulse affichera ensuite l’historique des transactions accessibles au compte.</p></div></details>
<details><summary>3. Annulation, absence et remboursement <span>+</span></summary><div class="kah-legal-body"><p>Les conditions exactes d’annulation et d’éventuels frais d’absence seront affichées avant la réservation et reprises dans la confirmation. Aucun frais ne devra être appliqué sur la seule base de cette version préparatoire.</p><p>Lorsqu’un remboursement est dû, ses modalités dépendront du moyen de paiement utilisé et de la nature de la prestation concernée.</p></div></details>
<details><summary>4. Services de santé et droit de rétractation <span>+</span></summary><div class="kah-legal-body"><p>Le régime juridique dépend de la nature réelle de la prestation. Les services de santé fournis par des professionnels de santé à des patients pour évaluer, maintenir ou rétablir leur état de santé relèvent d’un régime spécifique et sont exclus du chapitre du Code de la consommation consacré aux contrats conclus à distance. Les éventuels services numériques ou non médicaux devront être qualifiés séparément et leurs règles de rétractation précisées avant paiement.</p></div></details>
<details><summary>5. Données, confidentialité et sécurité <span>+</span></summary><div class="kah-legal-body"><p>Pulse peut traiter des données personnelles et, selon le parcours, des données concernant la santé. L’information du patient doit rester concise, accessible et adaptée au contexte. Les finalités, bases juridiques, destinataires, durées de conservation et droits des personnes sont détaillés dans la politique de confidentialité.</p><p>Les professionnels et centres conservent leurs propres obligations lorsqu’ils interviennent comme responsables de traitement ou acteurs de soins.</p></div></details>
<details><summary>6. Responsabilités et usage de Pulse <span>+</span></summary><div class="kah-legal-body"><p>Pulse n’est pas un service d’urgence et ne doit pas être utilisé pour demander une prise en charge urgente. Les informations et scores affichés doivent être interprétés selon leur niveau de validation. Les résultats Clinical restent soumis à une validation professionnelle lorsqu’elle est requise.</p><p>L’utilisateur est responsable de l’exactitude des informations qu’il saisit et du maintien de la confidentialité de ses accès.</p></div></details>
<details><summary>7. Réclamations et litiges <span>+</span></summary><div class="kah-legal-body"><p>Les réclamations liées au fonctionnement de Pulse seront adressées au support KŌMØ. Les réclamations portant sur un acte ou service de santé devront être orientées vers le professionnel ou l’établissement concerné selon le cas.</p><p>Le dispositif de médiation de la consommation applicable aux prestations non médicales sera indiqué lorsque l’entité commerciale et son médiateur auront été définitivement désignés. Les litiges relatifs aux services de santé fournis par des professionnels de santé ne relèvent pas du régime général de médiation de la consommation.</p></div></details>
<div class="kah-source-links"><a href="https://komolongevity.com/fr/cgv/" target="_blank" rel="noopener">Lire la version web des CGV ↗</a><a href="https://komolongevity.com/fr/confidentialite/" target="_blank" rel="noopener">Confidentialité ↗</a><a href="https://komolongevity.com/fr/mentions-legales/" target="_blank" rel="noopener">Mentions légales ↗</a></div></section>`}
async function render(){if(location.hash!=='#profile'||running)return;const host=document.querySelector('[data-profile-v2]');if(!host||host.querySelector('[data-account-hub-v2]'))return;running=true;try{const d=await data();if(!d)return;document.querySelector('#pageEyebrow').textContent='KŌMØ PULSE · MON COMPTE';document.querySelector('#pageTitle').textContent='Mon compte';const section=document.createElement('section');section.className='kah';section.dataset.accountHubV2='1';section.innerHTML=`<div class="kah-grid"><article class="kah-card"><div class="kah-head"><div><p class="eyebrow">FACTURATION</p><h3>Paiements & justificatifs.</h3><p>Retrouvez ici les paiements liés à votre parcours KŌMØ.</p></div><span class="kah-pill">Compte patient</span></div>${paymentRows(d.payments)}</article><article class="kah-card"><div class="kah-head"><div><p class="eyebrow">KŌMØ</p><h3>Comprendre votre parcours.</h3><p>Pulse est votre espace personnel. Le site principal rassemble la méthode, la science et le réseau KŌMØ.</p></div></div><div class="kah-links"><a href="https://komolongevity.com/fr/" target="_blank" rel="noopener">Site KŌMØ <span>↗</span></a><a href="https://komolongevity.com/fr/methode/" target="_blank" rel="noopener">Méthode <span>↗</span></a><a href="https://komolongevity.com/fr/science/" target="_blank" rel="noopener">Science <span>↗</span></a><a href="https://komolongevity.com/fr/network/" target="_blank" rel="noopener">Réseau <span>↗</span></a><a href="https://komolongevity.com/media" target="_blank" rel="noopener">Library <span>↗</span></a><a href="https://komolongevity.com/fr/contact/" target="_blank" rel="noopener">Contact <span>↗</span></a></div></article>${legal()}</div>`;host.appendChild(section);section.querySelectorAll('details').forEach(x=>x.addEventListener('toggle',()=>{const s=x.querySelector('summary span');if(s)s.textContent=x.open?'−':'+'}))}catch(e){console.error('[account-hub-v2]',e)}finally{running=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(render,120)}
window.addEventListener('hashchange',schedule);window.addEventListener('komo:route-ready',schedule);document.addEventListener('DOMContentLoaded',()=>setTimeout(render,950));const obs=new MutationObserver(()=>{if(location.hash==='#profile'&&document.querySelector('[data-profile-v2]')&&!document.querySelector('[data-account-hub-v2]'))schedule()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(render,1500);