import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const VERSION='5.0.0';
const URL='https://uqlolefsiktbznnymriy.supabase.co';
const KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REM='komo_pulse_remember';
const S={client:null,session:null,centers:[],appointments:[],directory:{centers:[],professionals:[]},loading:false};
const route=()=>window.KomoPatientNavigation?.route?.()||location.hash.replace(/^#/,'')||'home';
const storage=()=>localStorage.getItem(REM)==='1'?localStorage:sessionStorage;
const sb=()=>window.KomoRuntime?.client||(S.client||(S.client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})));
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function serviceLabel(v){return v==='clinical'?'KŌMØ Clinical':'KŌMØ Motion'}
function statusLabel(v){return({scheduled:'Planifié',confirmed:'Confirmé',arrived:'Arrivé',in_progress:'En cours',completed:'Terminé',cancelled:'Annulé',no_show:'Absent'})[v]||v||'À planifier'}
function fullDate(value,tz='Europe/Paris'){return new Intl.DateTimeFormat('fr-FR',{timeZone:tz,weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)).replace('.','')}
function upcoming(){return S.appointments.filter(x=>new Date(x.scheduled_start)>new Date()&&!['cancelled','completed','no_show'].includes(x.status)).sort((a,b)=>new Date(a.scheduled_start)-new Date(b.scheduled_start))}
function installStyle(){if(document.querySelector('#agendaHubV5Style'))return;const s=document.createElement('style');s.id='agendaHubV5Style';s.textContent=`
body.agenda-v5 .main-shell{background:#f4f0e9!important}
body.agenda-v5 #viewRoot{padding-top:0!important}
.ag5{padding:0 0 110px}.ag5 *{box-sizing:border-box}
.ag5-hero{position:relative;overflow:hidden;min-height:188px;padding:22px 24px;border-radius:24px;color:#fff;background:radial-gradient(circle at 94% 8%,rgba(216,127,103,.25),transparent 31%),radial-gradient(circle at 78% 94%,rgba(104,137,178,.18),transparent 32%),linear-gradient(135deg,#26272a,#34363b 60%,#51403f);box-shadow:0 22px 60px rgba(37,34,31,.12)}
.ag5-hero:after{content:'';position:absolute;width:420px;height:420px;right:-145px;top:-235px;border-radius:50%;border:1px solid rgba(255,255,255,.07);box-shadow:0 0 0 46px rgba(255,255,255,.018),0 0 0 92px rgba(255,255,255,.012)}
.ag5-grid{position:relative;z-index:2;display:grid;grid-template-columns:1.35fr .65fr;gap:26px;align-items:center}
.ag5-kicker{font:700 7px/1 'DM Sans',sans-serif;letter-spacing:.14em;text-transform:uppercase;color:rgba(255,255,255,.48)}
.ag5 h2{margin:7px 0 0;font:500 clamp(37px,4vw,58px)/.93 Manrope,sans-serif;letter-spacing:-.055em}
.ag5-copy{max-width:610px;margin:10px 0 0;color:rgba(255,255,255,.62);font:400 9px/1.5 'DM Sans',sans-serif}
.ag5-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:15px}.ag5-btn{border:1px solid rgba(255,255,255,.13);border-radius:11px;background:rgba(255,255,255,.075);color:#fff;padding:9px 12px;font:700 7px 'DM Sans',sans-serif;cursor:pointer}.ag5-btn.primary{background:#f5f0e7;color:#302f2d;border-color:#f5f0e7}
.ag5-next{padding:15px 16px;border:1px solid rgba(255,255,255,.10);border-radius:18px;background:rgba(255,255,255,.07);backdrop-filter:blur(12px)}
.ag5-next-top{display:flex;align-items:center;justify-content:space-between;gap:9px}.ag5-next-top span{font:700 6px 'DM Sans',sans-serif;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.47)}.ag5-next-top b{padding:4px 6px;border-radius:999px;background:rgba(255,255,255,.09);font:700 6px 'DM Sans',sans-serif}
.ag5-next strong{display:block;margin-top:11px;font:600 17px/1.06 Manrope,sans-serif}.ag5-next small{display:block;margin-top:6px;color:rgba(255,255,255,.57);font:400 7px/1.4 'DM Sans',sans-serif}.ag5-metrics{display:flex;gap:15px;margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.08)}.ag5-metrics span{font:500 6px 'DM Sans',sans-serif;color:rgba(255,255,255,.5)}.ag5-metrics b{margin-right:3px;color:#fff;font-size:10px}
@media(max-width:850px){.ag5-grid{grid-template-columns:1fr}.ag5-hero{padding:20px}.ag5-next{max-width:520px}.ag5 h2{font-size:clamp(36px,9vw,52px)}}
@media(max-width:560px){.ag5-hero{border-radius:20px;min-height:auto;padding:18px}.ag5-actions{display:grid;grid-template-columns:1fr}.ag5-btn{width:100%}.ag5-metrics{gap:11px}}
`;document.head.appendChild(s)}
function hero(){const up=upcoming(),n=up[0],center=n?S.centers.find(x=>x.id===n.organization_id):null,tz=center?.timezone||'Europe/Paris';return `<div class="ag5" data-kbook-patient data-agenda-hub-v5><section class="ag5-hero"><div class="ag5-grid"><div><div class="ag5-kicker">KŌMØ PULSE · AGENDA</div><h2>Planifier. Préparer.<br>Continuer.</h2><p class="ag5-copy">Votre rendez-vous, votre centre et la préparation du prochain bilan réunis dans un seul écran.</p><div class="ag5-actions"><button class="ag5-btn primary" data-ag5-action="reserve">Réserver →</button><button class="ag5-btn" data-ag5-route="motion">Préparer Motion</button><button class="ag5-btn" data-ag5-action="map">Voir la carte</button></div></div><aside class="ag5-next"><div class="ag5-next-top"><span>PROCHAINE ÉTAPE</span><b>${n?esc(statusLabel(n.status)):'À planifier'}</b></div>${n?`<strong>${esc(serviceLabel(n.appointment_type))}</strong><small>${esc(center?.name||'Centre KŌMØ')} · ${esc(fullDate(n.scheduled_start,tz))}</small>`:`<strong>KŌMØ Motion</strong><small>Choisissez votre prochaine étape depuis votre parcours KŌMØ.</small>`}<div class="ag5-metrics"><span><b>${up.length}</b> à venir</span><span><b>${S.centers.length}</b> centres</span><span><b>${S.directory?.professionals?.length||0}</b> pros</span></div></aside></div></section></div>`}
function render(){if(route()!=='documents')return;installStyle();document.body.classList.remove('agenda-v3','agenda-v4');document.body.classList.add('agenda-v5');const root=document.querySelector('#viewRoot');if(!root)return;const pe=document.querySelector('#pageEyebrow'),pt=document.querySelector('#pageTitle');if(pe)pe.textContent='KŌMØ PULSE · AGENDA';if(pt)pt.textContent='Organiser la suite, simplement.';root.innerHTML=hero();bind()}
function bind(){document.querySelectorAll('[data-ag5-route]').forEach(b=>b.addEventListener('click',()=>window.KomoPatientNavigation?.go?.(b.dataset.ag5Route)||(location.hash=b.dataset.ag5Route)));document.querySelector('[data-ag5-action="reserve"]')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('komo:agenda-reserve-request')));document.querySelector('[data-ag5-action="map"]')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('komo:agenda-map-request')))}
async function load(){if(route()!=='documents')return;try{const ses=await sb().auth.getSession();S.session=ses.data.session;if(!S.session?.user){render();return}const p=await sb().from('patients').select('id').eq('patient_user_id',S.session.user.id);const ids=(p.data||[]).map(x=>x.id);const [centers,directory,appointments]=await Promise.all([sb().rpc('komo_booking_centers'),sb().rpc('komo_booking_directory'),ids.length?sb().from('organization_appointments').select('id,organization_id,appointment_type,scheduled_start,status').in('patient_id',ids).order('scheduled_start',{ascending:true}):Promise.resolve({data:[],error:null})]);S.centers=centers.data||[];S.directory=directory.data||{centers:[],professionals:[]};S.appointments=appointments.data||[];render()}catch(e){console.error('[agenda-hub-v5]',e);render()}}
async function refresh(){if(route()!=='documents'){document.body.classList.remove('agenda-v5');return}render();await load()}
const root=document.querySelector('#viewRoot');if(root)new MutationObserver(()=>{if(route()==='documents'&&!document.querySelector('[data-agenda-hub-v5]'))setTimeout(render,0)}).observe(root,{childList:true,subtree:false});
window.addEventListener('hashchange',()=>route()==='documents'?setTimeout(refresh,20):document.body.classList.remove('agenda-v5'));window.addEventListener('pageshow',()=>{if(route()==='documents')setTimeout(refresh,60)});document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(route()==='documents')refresh()},500));
window.KomoAgendaHubV5={version:VERSION,refresh,ownsPatientAgenda:()=>route()==='documents'};
