/* KŌMØ Pulse — Connected v3 · daily signals + trajectory */
(()=>{
'use strict';
const V='3.1.0';
let cache=null,cacheAt=0,busy=false,timer=0,period=7;
const route=()=>window.KomoPatientNavigation?.route?.()||location.hash.replace(/^#/,'')||'home';
const client=()=>window.KomoRuntime?.client||null;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const dayKey=d=>{const x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),dd=String(x.getDate()).padStart(2,'0');return`${y}-${m}-${dd}`};
const dayDate=k=>new Date(`${k}T12:00:00`);
const shiftDay=(k,n)=>{const d=dayDate(k);d.setDate(d.getDate()+n);return dayKey(d)};
const fmtDate=v=>{if(!v)return'—';const d=dayDate(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(d).replace('.','')};
const fmtLongDate=v=>{if(!v)return'—';const d=dayDate(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(d)};
const fmtInt=v=>v===null?'—':Math.round(v).toLocaleString('fr-FR');
const fmtHours=v=>v===null?'—':`${Math.floor(v/60)}h ${String(Math.round(v%60)).padStart(2,'0')}`;
const fmtBpm=v=>v===null?'—':`${Math.round(v)} bpm`;
const sliceCalendar=(rows,end,days)=>{const start=shiftDay(end,-days+1);return rows.filter(r=>r.metric_date>=start&&r.metric_date<=end)};
const previousCalendar=(rows,end,days)=>{const prevEnd=shiftDay(end,-days),start=shiftDay(prevEnd,-days+1);return rows.filter(r=>r.metric_date>=start&&r.metric_date<=prevEnd)};
function provisionalEstimate(row,key){const e=row?.raw_payload?.motion_today_estimate;if(!e||e.validation!=='provisional')return null;if(key==='sleep_minutes')return num(e.in_bed_minutes);if(key==='resting_hr')return num(e.nocturnal_hr_p10);return null}
function valueFor(row,key){const canonical=num(row?.[key]);if(canonical!==null)return canonical;return provisionalEstimate(row,key)}
function isProvisional(row,key){return num(row?.[key])===null&&provisionalEstimate(row,key)!==null}
function meanMetric(rows,key){const vals=rows.map(r=>valueFor(r,key)).filter(v=>v!==null);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function validMetricCount(rows,key){return rows.map(r=>valueFor(r,key)).filter(v=>v!==null).length}
function deltaPct(current,usual,inverse=false){if(current===null||usual===null||usual===0)return null;const d=(current-usual)/usual*100;return inverse?-d:d}
function scoreFromDelta(delta,sensitivity=2){return delta===null?null:Math.round(clamp(70+delta*sensitivity))}
function tone(score){if(score===null)return'neutral';if(score>=80)return'good';if(score>=65)return'stable';return'low'}
function scoreLabel(score){if(score===null)return'Données à compléter';if(score>=90)return'Très bon signal';if(score>=80)return'Vous êtes bien aujourd’hui';if(score>=65)return'Dans votre zone habituelle';return'En dessous de votre habituel'}
function trendText(delta){if(delta===null)return'Référence insuffisante';const sign=delta>0?'+':'';return`${sign}${Math.round(delta)}% vs habituel`}
function style(){if(document.querySelector('#connectedV3Style'))return;const s=document.createElement('style');s.id='connectedV3Style';s.textContent=`
body.connected-v3 .main-shell,body.connected-v3 #viewRoot{background:#050706!important}.kcn3{--bg:#050706;--panel:#0a0e0b;--panel2:#0d130f;--line:rgba(255,255,255,.09);--ink:#f1f4f1;--muted:#929d96;--green:#91b29a;--greenSoft:rgba(145,178,154,.10);--amber:#d4b16f;--red:#d28a82;max-width:1480px;margin:0 auto;padding:4px 0 118px;color:var(--ink);display:grid;gap:12px}.kcn3 *{box-sizing:border-box}.kcn3-card{background:var(--panel);border:1px solid var(--line);border-radius:24px}.kcn3-kicker{font-size:8px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:#77867c}.kcn3 h2,.kcn3 h3,.kcn3 h4{margin:0;font-family:Manrope,sans-serif;letter-spacing:-.045em;font-weight:500}.kcn3 h2{font-size:clamp(32px,4.2vw,58px);line-height:.96}.kcn3 h3{font-size:24px}.kcn3 p{color:var(--muted)}
.kcn3-today{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(380px,.85fr);min-height:270px;overflow:hidden}.kcn3-score{padding:28px 30px;display:flex;flex-direction:column;justify-content:space-between;background:linear-gradient(145deg,#0a0f0c,#111b14)}.kcn3-scoretop{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.kcn3-scorevalue{font:500 clamp(64px,8vw,110px)/.82 Manrope,sans-serif;letter-spacing:-.08em;color:#edf3ee}.kcn3-scorevalue small{font-size:17px;letter-spacing:-.02em;color:#819188;margin-left:7px}.kcn3-score h2{margin-top:13px}.kcn3-score p{max-width:650px;margin:11px 0 0;font-size:12px;line-height:1.55}.kcn3-date{text-align:right}.kcn3-date strong{display:block;margin-top:7px;font-size:12px;font-weight:600}.kcn3-date span{display:block;margin-top:4px;color:#76847b;font-size:9px}.kcn3-composite-note{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:18px;color:#829189;font-size:9px}.kcn3-dot{width:7px;height:7px;border-radius:50%;background:var(--green)}.kcn3-provisional{display:inline-flex;align-items:center;padding:4px 7px;border:1px solid rgba(212,177,111,.25);border-radius:999px;color:#d8bd84;background:rgba(212,177,111,.08);font-size:7px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.kcn3-signals{padding:18px;display:grid;grid-template-columns:1fr;gap:8px;background:#080b09}.kcn3-signal{min-height:72px;padding:14px 15px;border:1px solid var(--line);border-radius:16px;background:var(--panel2);display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.kcn3-signal.good{background:var(--greenSoft);border-color:rgba(145,178,154,.17)}.kcn3-signal .label{font-size:8px;text-transform:uppercase;letter-spacing:.11em;color:#7e8c83}.kcn3-signal strong{display:block;margin-top:5px;font:600 22px/1 Manrope,sans-serif}.kcn3-signal small{display:block;margin-top:5px;color:#849087;font-size:8px}.kcn3-subscore{font:500 26px/1 Manrope,sans-serif;color:#a9b7ad;text-align:right}.kcn3-subscore.good{color:#a9cab1}.kcn3-subscore em{display:block;margin-top:5px;font:500 7px DM Sans,sans-serif;text-transform:uppercase;letter-spacing:.1em;color:#748178;font-style:normal}
.kcn3-section{padding:22px}.kcn3-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin-bottom:18px}.kcn3-head p{max-width:610px;text-align:right;font-size:9px;line-height:1.55;margin:0}.kcn3-periods{display:flex;padding:3px;border:1px solid var(--line);border-radius:999px;background:#080b09}.kcn3-periods button{border:0;border-radius:999px;background:transparent;color:#77847c;padding:8px 13px;font:600 9px DM Sans,sans-serif;cursor:pointer}.kcn3-periods button.active{background:#edf2ee;color:#18221c}
.kcn3-trajectory{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.55fr);gap:12px}.kcn3-chart{padding:18px;border:1px solid var(--line);border-radius:18px;background:#080b09}.kcn3-charttop{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.kcn3-charttop strong{font:600 30px/1 Manrope,sans-serif}.kcn3-charttop span{display:block;margin-top:6px;color:#7d8a82;font-size:8px}.kcn3-bars{height:155px;margin-top:20px;display:flex;align-items:flex-end;gap:5px;border-bottom:1px solid rgba(255,255,255,.07)}.kcn3-barwrap{height:100%;min-width:0;flex:1;display:flex;align-items:flex-end;position:relative}.kcn3-bar{width:100%;min-height:2px;border-radius:5px 5px 1px 1px;background:#65756b}.kcn3-bar.current{background:#a7c3ad}.kcn3-barwrap:hover:after{content:attr(data-tip);position:absolute;bottom:calc(100% + 8px);left:50%;transform:translateX(-50%);white-space:nowrap;padding:5px 7px;border-radius:7px;background:#f1f3f0;color:#162018;font-size:7px;z-index:4}.kcn3-axis{display:flex;justify-content:space-between;margin-top:7px;color:#67736b;font-size:7px}.kcn3-periodstats{display:grid;grid-template-columns:1fr;gap:8px}.kcn3-periodstat{padding:15px;border:1px solid var(--line);border-radius:16px;background:#0c110e}.kcn3-periodstat span{display:block;color:#7d8981;font-size:7px;text-transform:uppercase;letter-spacing:.1em}.kcn3-periodstat strong{display:block;margin-top:6px;font:600 18px/1.1 Manrope,sans-serif}.kcn3-periodstat small{display:block;margin-top:6px;color:#78857d;font-size:8px}
.kcn3-more{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.kcn3-mini{padding:15px;border:1px solid var(--line);border-radius:16px;background:#0b100d}.kcn3-mini span{display:block;color:#79867e;font-size:7px;text-transform:uppercase;letter-spacing:.1em}.kcn3-mini strong{display:block;margin-top:7px;font:600 19px/1 Manrope,sans-serif}.kcn3-mini small{display:block;margin-top:6px;color:#748078;font-size:8px}.kcn3-foot{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:15px 18px}.kcn3-foot p{margin:0;font-size:8px;line-height:1.5}.kcn3-btn{border:1px solid rgba(255,255,255,.12);border-radius:11px;background:#111712;color:#dfe5e0;padding:8px 11px;font:600 8px DM Sans,sans-serif;cursor:pointer}.kcn3-btn.primary{background:#91b29a;color:#142018;border-color:#91b29a}.kcn3-empty{padding:22px;border:1px solid var(--line);border-radius:18px;background:#0a0e0b;color:#89958d;font-size:10px;line-height:1.55}
@media(max-width:980px){.kcn3-today{grid-template-columns:1fr}.kcn3-signals{grid-template-columns:repeat(3,1fr)}.kcn3-signal{grid-template-columns:1fr}.kcn3-subscore{text-align:left}.kcn3-trajectory{grid-template-columns:1fr}.kcn3-periodstats{grid-template-columns:repeat(3,1fr)}}
@media(max-width:720px){.kcn3{padding-top:0;gap:9px}.kcn3-card{border-radius:19px}.kcn3-score{padding:21px 18px}.kcn3-scoretop{display:block}.kcn3-date{text-align:left;margin-top:22px}.kcn3-signals{grid-template-columns:1fr;padding:12px}.kcn3-section{padding:17px}.kcn3-head{display:block}.kcn3-head p{text-align:left;margin-top:7px}.kcn3-periods{margin-top:13px;width:max-content}.kcn3-more{grid-template-columns:1fr 1fr}.kcn3-periodstats{grid-template-columns:1fr}.kcn3-bars{height:130px}.kcn3-foot{align-items:flex-start;flex-direction:column}.kcn3-foot .kcn3-btn{width:100%}}
`;document.head.appendChild(s)}
async function load(force=false){if(!force&&cache&&Date.now()-cacheAt<15000)return cache;const c=client();if(!c)return null;const session=window.KomoRuntime?.getContext?.()?.session||(await c.auth.getSession()).data?.session;if(!session?.user)return null;const from=new Date();from.setDate(from.getDate()-100);const [d,co]=await Promise.all([c.from('wearable_daily_metrics').select('metric_date,steps,distance_m,active_minutes,sedentary_minutes,resting_hr,avg_hr,hrv_ms,spo2_avg,sleep_minutes,deep_sleep_minutes,rem_sleep_minutes,wear_minutes,source,source_quality,day_wear_mode,night_worn,raw_payload').eq('user_id',session.user.id).gte('metric_date',dayKey(from)).order('metric_date',{ascending:false}).limit(100),c.from('wearable_consents').select('*').eq('user_id',session.user.id).eq('purpose','connected_followup').order('accepted_at',{ascending:false}).limit(1)]);if(d.error)throw d.error;if(co.error)throw co.error;cache={session,rows:d.data||[],consent:(co.data||[])[0]||null};cacheAt=Date.now();return cache}
const consentActive=d=>d?.consent?.status==='active';
function latestWith(rows,key){return rows.find(r=>valueFor(r,key)!==null)||null}
function baselineFor(rows,latestDate,key,days=28){const all=sliceCalendar(rows,shiftDay(latestDate,-1),days);return{value:meanMetric(all,key),count:validMetricCount(all,key)}}
function dailySignals(rows){const latest=rows[0]||null;if(!latest)return null;const stepRow=latestWith(rows,'steps'),sleepRow=latestWith(rows,'sleep_minutes'),heartRow=latestWith(rows,'resting_hr');const build=(row,key,inverse=false,sensitivity=2)=>{if(!row)return{row:null,value:null,usual:null,delta:null,score:null,count:0,provisional:false};const b=baselineFor(rows,row.metric_date,key);const value=valueFor(row,key),delta=b.count>=2?deltaPct(value,b.value,inverse):null,score=b.count>=2?scoreFromDelta(delta,sensitivity):null;return{row,value,usual:b.value,delta,score,count:b.count,provisional:isProvisional(row,key)}};const move=build(stepRow,'steps',false,2),sleep=build(sleepRow,'sleep_minutes',false,2),heart=build(heartRow,'resting_hr',true,2.5);const parts=[['move',move,.40],['sleep',sleep,.35],['heart',heart,.25]].filter(([,x])=>x.score!==null);const totalWeight=parts.reduce((a,p)=>a+p[2],0);const composite=parts.length===3?Math.round(parts.reduce((a,p)=>a+p[1].score*p[2],0)/totalWeight):null;const provisional=[move,sleep,heart].some(x=>x.provisional);return{latest,move,sleep,heart,composite,parts:parts.length,provisional}}
function periodStats(rows,days){const end=rows[0]?.metric_date||dayKey(new Date()),current=sliceCalendar(rows,end,days),previous=previousCalendar(rows,end,days);const metric=(key,inverse=false)=>{const cur=meanMetric(current,key),prev=meanMetric(previous,key),delta=validMetricCount(previous,key)>=Math.min(2,days)?deltaPct(cur,prev,inverse):null;return{cur,prev,delta,count:validMetricCount(current,key)}};return{end,current,previous,steps:metric('steps'),sleep:metric('sleep_minutes'),rhr:metric('resting_hr',true),active:metric('active_minutes'),distance:metric('distance_m'),hrv:metric('hrv_ms'),spo2:metric('spo2_avg'),coverage:Math.round(new Set(current.map(r=>r.metric_date)).size/days*100)}}
function bars(rows,days){const end=rows[0]?.metric_date||dayKey(new Date()),start=shiftDay(end,-days+1),map=new Map(rows.map(r=>[r.metric_date,valueFor(r,'steps')]));const vals=[];for(let i=0;i<days;i++){const k=shiftDay(start,i);vals.push({k,v:map.get(k)??null})}const max=Math.max(1,...vals.map(x=>x.v||0));return vals.map((x,i)=>`<div class="kcn3-barwrap" data-tip="${esc(fmtDate(x.k))} · ${x.v===null?'—':fmtInt(x.v)+' pas'}"><i class="kcn3-bar ${i===vals.length-1?'current':''}" style="height:${x.v===null?2:Math.max(4,Math.round(x.v/max*100))}%"></i></div>`).join('')}
function signalCard(label,data,formatter,goodCopy){const t=tone(data.score),source=data.provisional?' · provisoire Mi Fitness':'';return`<article class="kcn3-signal ${t==='good'?'good':''}"><div><span class="label">${esc(label)}</span><strong>${formatter(data.value)}</strong><small>${data.usual===null?'Habituel en construction':`${trendText(data.delta)} · habituel ${formatter(data.usual)}`}${source}</small></div><div class="kcn3-subscore ${t==='good'?'good':''}">${data.score===null?'—':data.score}<em>${data.score===null?'score en attente':goodCopy}</em></div></article>`}
function periodComparison(label,m,formatter){return`<article class="kcn3-periodstat"><span>${esc(label)}</span><strong>${formatter(m.cur)}</strong><small>${m.count} jour${m.count>1?'s':''} · ${m.delta===null?'comparaison en attente':trendText(m.delta)}</small></article>`}
function html(data){const rows=data.rows||[],sig=dailySignals(rows),on=consentActive(data);if(!sig)return`<section class="kcn3"><div class="kcn3-empty">Aucune donnée Connected n’est encore disponible. Dès qu’un dispositif compatible synchronise ses données, votre journée et votre trajectoire apparaissent ici.</div></section>`;const ps=periodStats(rows,period),latest=sig.latest,latestActive=latestWith(rows,'active_minutes'),latestHrv=latestWith(rows,'hrv_ms'),latestSpo2=latestWith(rows,'spo2_avg'),latestDistance=latestWith(rows,'distance_m'),composite=sig.composite;return`<section class="kcn3" data-connected-v3>
<article class="kcn3-card kcn3-today"><div class="kcn3-score"><div><div class="kcn3-scoretop"><div><div class="kcn3-kicker">MOTION TODAY · CONNECTED</div><div class="kcn3-scorevalue">${composite===null?'—':composite}<small>${composite===null?'':'/100'}</small></div></div><div class="kcn3-date"><div class="kcn3-kicker">DERNIÈRE JOURNÉE</div><strong>${esc(fmtLongDate(latest.metric_date))}</strong><span>${on?'Synchronisation active':'Collecte inactive'}</span></div></div><h2>${esc(scoreLabel(composite))}</h2><p>${composite===null?'Le score quotidien apparaîtra lorsque Mouvement, Sommeil et Cœur disposent d’une référence suffisante. Les données disponibles restent affichées sans valeur inventée.':'Votre signal Connected combine mouvement, sommeil et fréquence cardiaque par rapport à votre propre niveau habituel.'}</p></div><div class="kcn3-composite-note"><span class="kcn3-dot"></span><span>Signal quotidien non clinique · Motion Myodev reste votre mesure de référence</span>${sig.provisional?'<span class="kcn3-provisional">Estimation provisoire</span>':''}</div></div><div class="kcn3-signals">${signalCard('Mouvement',sig.move,v=>v===null?'—':fmtInt(v)+' pas','mouvement')}${signalCard(sig.sleep.provisional?'Sommeil · temps au lit':'Sommeil',sig.sleep,fmtHours,'sommeil')}${signalCard(sig.heart.provisional?'Cœur · FC nocturne':'Cœur · FC repos',sig.heart,fmtBpm,'cœur')}</div></article>
<article class="kcn3-card kcn3-section"><div class="kcn3-head"><div><div class="kcn3-kicker">TRAJECTOIRE</div><h3>Où vous vous situez.</h3></div><div><p>Votre niveau récent est comparé à la période précédente, avec la couverture réelle des données.</p><div class="kcn3-periods"><button type="button" data-kcn-period="7" class="${period===7?'active':''}">7 jours</button><button type="button" data-kcn-period="30" class="${period===30?'active':''}">30 jours</button></div></div></div><div class="kcn3-trajectory"><div class="kcn3-chart"><div class="kcn3-charttop"><div><div class="kcn3-kicker">PAS MOYENS · ${period} JOURS</div><strong>${ps.steps.cur===null?'—':fmtInt(ps.steps.cur)}</strong><span>${ps.steps.delta===null?'Comparaison en attente':trendText(ps.steps.delta)} · couverture ${ps.coverage}%</span></div><div class="kcn3-kicker">${fmtDate(shiftDay(ps.end,-period+1))} → ${fmtDate(ps.end)}</div></div><div class="kcn3-bars">${bars(rows,period)}</div><div class="kcn3-axis"><span>${fmtDate(shiftDay(ps.end,-period+1))}</span><span>${fmtDate(ps.end)}</span></div></div><div class="kcn3-periodstats">${periodComparison('Pas / jour',ps.steps,v=>v===null?'—':fmtInt(v))}${periodComparison('Sommeil / nuit',ps.sleep,fmtHours)}${periodComparison('FC repos / nocturne',ps.rhr,fmtBpm)}</div></div></article>
<article class="kcn3-card kcn3-section"><div class="kcn3-head"><div><div class="kcn3-kicker">PLUS DE SIGNAL</div><h3>Votre quotidien, sans surcharge.</h3></div><p>Ces données complètent la trajectoire sans remplacer votre bilan Motion.</p></div><div class="kcn3-more"><article class="kcn3-mini"><span>Temps actif</span><strong>${latestActive&&valueFor(latestActive,'active_minutes')!==null?`${Math.round(valueFor(latestActive,'active_minutes'))} min`:'—'}</strong><small>${latestActive?'dernière donnée disponible':'en attente de synchronisation'}</small></article><article class="kcn3-mini"><span>Distance</span><strong>${latestDistance&&valueFor(latestDistance,'distance_m')!==null?`${(valueFor(latestDistance,'distance_m')/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})} km`:'—'}</strong><small>${latestDistance?'dernière donnée disponible':'en attente de synchronisation'}</small></article><article class="kcn3-mini"><span>HRV</span><strong>${latestHrv&&valueFor(latestHrv,'hrv_ms')!==null?`${Math.round(valueFor(latestHrv,'hrv_ms'))} ms`:'—'}</strong><small>${latestHrv?'dernière donnée disponible':'en attente de synchronisation'}</small></article><article class="kcn3-mini"><span>SpO₂</span><strong>${latestSpo2&&valueFor(latestSpo2,'spo2_avg')!==null?`${valueFor(latestSpo2,'spo2_avg').toLocaleString('fr-FR',{maximumFractionDigits:1})}%`:'—'}</strong><small>${latestSpo2?'dernière donnée disponible':'en attente de synchronisation'}</small></article></div></article>
<article class="kcn3-card kcn3-foot"><p>${on?'Connected collecte les catégories que vous avez autorisées.':'La collecte Connected est inactive.'} Les valeurs provisoires issues de Mi Fitness restent identifiées comme telles jusqu’à validation de leur mapping définitif.</p><button class="kcn3-btn ${on?'':'primary'}" type="button" data-connected-consent>${on?'Gérer la collecte':'Activer Connected'}</button></article>
</section>`}
function setChrome(){const eyebrow=document.querySelector('#pageEyebrow'),title=document.querySelector('#pageTitle');if(eyebrow)eyebrow.textContent='KŌMØ CONNECTED';if(title)title.textContent='Votre quotidien, dans le temps.'}
async function toggleConsent(){if(busy)return;busy=true;try{const d=await load(true),c=client();if(!d||!c)return;if(consentActive(d)){if(!confirm('Arrêter la collecte KŌMØ Connected ? Les données déjà enregistrées restent dans votre historique tant qu’elles ne sont pas supprimées.'))return;const r=await c.from('wearable_consents').update({status:'withdrawn',withdrawn_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',d.consent.id);if(r.error)throw r.error}else{const r=await c.from('wearable_consents').insert({user_id:d.session.user.id,purpose:'connected_followup',consent_version:'2026-09-03-connected-v3',status:'active',data_categories:['movement','sleep','heart_rate','spo2']});if(r.error)throw r.error}cache=null;window.dispatchEvent(new CustomEvent('komo:wearable-data-updated'));await render(true)}catch(e){console.error('[connected-v3]',e);alert(e.message||'Action impossible.')}finally{busy=false}}
function bind(root){root.querySelector('[data-connected-consent]')?.addEventListener('click',toggleConsent);root.querySelectorAll('[data-kcn-period]').forEach(b=>b.addEventListener('click',()=>{period=Number(b.dataset.kcnPeriod)||7;render(false)}))}
async function render(force=false){if(route()!=='key')return;style();document.body.classList.add('connected-v2','connected-v3');const root=document.querySelector('#viewRoot');if(!root)return;setChrome();try{const d=await load(force);if(route()!=='key')return;if(!d){root.innerHTML='<section class="kcn3"><div class="kcn3-empty">Session indisponible. Reconnectez-vous pour accéder à KŌMØ Connected.</div></section>';return}root.innerHTML=html(d);bind(root)}catch(e){console.error('[connected-v3]',e);root.innerHTML='<section class="kcn3"><div class="kcn3-empty">KŌMØ Connected est momentanément indisponible. Les autres espaces Pulse restent accessibles.</div></section>'}}
function enter(force=false){if(route()!=='key'){document.body.classList.remove('connected-v2','connected-v3');return}clearTimeout(timer);timer=setTimeout(()=>render(force),25)}
window.addEventListener('hashchange',()=>enter(false));window.addEventListener('pageshow',()=>enter(false));window.addEventListener('komo:session-ready',()=>enter(false));window.addEventListener('komo:wearable-data-updated',()=>{cache=null;enter(true)});document.addEventListener('DOMContentLoaded',()=>enter(false));setTimeout(()=>enter(false),300);window.KomoKeyHubV1={version:V,refresh:()=>render(true)};
})();
