/* KŌMØ Pulse — KŌMØ Connected v2 · continuous wearable data */
(()=>{
'use strict';
const V='2.0.0';
let cache=null,cacheAt=0,busy=false,timer=0;
const route=()=>window.KomoPatientNavigation?.route?.()||location.hash.replace(/^#/,'')||'home';
const client=()=>window.KomoRuntime?.client||null;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const mean=(rows,key)=>{const v=rows.map(r=>num(r[key])).filter(v=>v!==null);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};
const dayKey=d=>{const x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),dd=String(x.getDate()).padStart(2,'0');return`${y}-${m}-${dd}`};
const fmtDate=v=>{if(!v)return'—';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'long',year:'numeric'}).format(d)};
const fmtInt=v=>v===null?'—':Math.round(v).toLocaleString('fr-FR');
function style(){if(document.querySelector('#connectedV2Style'))return;const s=document.createElement('style');s.id='connectedV2Style';s.textContent=`
body.connected-v2 .main-shell{background:#f6f7f5!important}body.connected-v2 #viewRoot{background:transparent!important}.kcv2{--ink:#1f2f25;--muted:#718078;--line:rgba(31,47,37,.10);--green:#4f7059;--green-bg:#e8f0e9;--red:#96584f;--red-bg:#f8e9e6;max-width:1500px;margin:0 auto;display:grid;gap:14px;padding-bottom:24px;color:var(--ink)}.kcv2 *{box-sizing:border-box}.kcv2-card{border:1px solid var(--line);border-radius:24px;background:#fff;box-shadow:0 16px 42px rgba(24,39,29,.045)}.kcv2-kicker{font-size:7px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#7e8a83}.kcv2 h2,.kcv2 h3{margin:0;font-family:Manrope,sans-serif;letter-spacing:-.045em}.kcv2 h2{font-size:clamp(30px,4vw,48px);line-height:1}.kcv2 h3{font-size:20px}.kcv2 p{color:var(--muted)}
.kcv2-hero{padding:24px;background:linear-gradient(145deg,#17241c,#294333);color:#fff;border-color:rgba(255,255,255,.06);box-shadow:0 24px 68px rgba(18,31,23,.15)}.kcv2-hero .kcv2-kicker,.kcv2-hero p{color:rgba(255,255,255,.58)}.kcv2-hero-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:20px;align-items:end}.kcv2-hero p{max-width:720px;margin:9px 0 0;font-size:10px;line-height:1.55}.kcv2-live{text-align:right}.kcv2-live small{display:block;font-size:7px;letter-spacing:.12em;text-transform:uppercase;opacity:.55}.kcv2-live strong{display:block;margin-top:7px;font:500 35px/1 Manrope,sans-serif}.kcv2-live span{display:block;margin-top:5px;font-size:8px;opacity:.62}
.kcv2-section{padding:20px}.kcv2-head{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;margin-bottom:14px}.kcv2-head p{max-width:590px;margin:0;font-size:8.5px;line-height:1.45;text-align:right}.kcv2-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.kcv2-metric{padding:16px;border-radius:18px;background:#f7f9f7;border:1px solid var(--line)}.kcv2-metric small{display:block;font-size:6.5px;text-transform:uppercase;letter-spacing:.1em;color:#849087}.kcv2-metric strong{display:block;margin-top:8px;font:600 27px/1 Manrope,sans-serif}.kcv2-metric span{display:block;margin-top:6px;font-size:8px;color:#748078}.kcv2-status{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kcv2-panel{padding:18px;border-radius:19px;background:#f6f8f6;border:1px solid var(--line)}.kcv2-panel.good{background:var(--green-bg);border-color:rgba(79,112,89,.12)}.kcv2-panel small{display:block;font-size:6.5px;text-transform:uppercase;letter-spacing:.1em;color:#849087}.kcv2-panel strong{display:block;margin-top:8px;font-size:15px}.kcv2-panel p{margin:7px 0 0;font-size:8px;line-height:1.5}.kcv2-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.kcv2-btn{border:1px solid #d9ddd9;border-radius:12px;background:#fff;color:#26382d;padding:9px 12px;font:700 8px DM Sans,sans-serif;cursor:pointer}.kcv2-btn.primary{background:#23372b;color:#fff;border-color:#23372b}.kcv2-empty{padding:18px;border-radius:17px;background:#f3f5f3;color:#6d7871;font-size:9px;line-height:1.5}
@media(max-width:820px){.kcv2-hero-grid{grid-template-columns:1fr}.kcv2-live{text-align:left}.kcv2-grid{grid-template-columns:1fr 1fr}.kcv2-status{grid-template-columns:1fr}}
@media(max-width:620px){.kcv2{gap:10px}.kcv2-card{border-radius:20px}.kcv2-hero,.kcv2-section{padding:16px}.kcv2-head{display:block}.kcv2-head p{margin-top:7px;text-align:left}.kcv2-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function load(force=false){if(!force&&cache&&Date.now()-cacheAt<15000)return cache;const c=client();if(!c)return null;const session=window.KomoRuntime?.getContext?.()?.session||(await c.auth.getSession()).data?.session;if(!session?.user)return null;const from=new Date();from.setDate(from.getDate()-95);const [d,co]=await Promise.all([c.from('wearable_daily_metrics').select('metric_date,steps,active_minutes,distance_m,sleep_minutes,resting_hr,spo2_avg,day_wear_mode,night_worn').eq('user_id',session.user.id).gte('metric_date',dayKey(from)).order('metric_date',{ascending:false}).limit(95),c.from('wearable_consents').select('*').eq('user_id',session.user.id).eq('purpose','connected_followup').order('accepted_at',{ascending:false}).limit(1)]);if(d.error)throw d.error;if(co.error)throw co.error;cache={session,rows:d.data||[],consent:(co.data||[])[0]||null};cacheAt=Date.now();return cache}
const consentActive=d=>d?.consent?.status==='active';
function stats(data){const rows=data.rows||[],latest=rows[0]||null,r7=rows.slice(0,7),r30=rows.slice(0,30),days30=new Set(r30.map(r=>r.metric_date)).size;return{latest,steps7:mean(r7,'steps'),sleep7:mean(r7,'sleep_minutes'),rhr7:mean(r7,'resting_hr'),active7:mean(r7,'active_minutes'),distance7:mean(r7,'distance_m'),spo7:mean(r7,'spo2_avg'),coverage30:Math.min(100,Math.round(days30/30*100)),rows30:r30.length}}
function html(data){const s=stats(data),on=consentActive(data),last=s.latest;return`<section class="kcv2" data-connected-v2>
<article class="kcv2-card kcv2-hero"><div class="kcv2-hero-grid"><div><div class="kcv2-kicker">LIVE · BETWEEN ASSESSMENTS</div><h2>KŌMØ Connected.</h2><p>Connected reçoit les données compatibles de votre quotidien entre deux bilans. Il ne remplace pas Motion et ne crée pas un score médical parallèle : il observe votre continuité.</p></div><div class="kcv2-live"><small>DERNIÈRE SYNCHRONISATION</small><strong>${last?esc(fmtDate(last.metric_date)):'Aucune donnée'}</strong><span>${on?'Collecte autorisée':'Collecte inactive'}</span></div></div></article>
<article class="kcv2-card kcv2-section"><div class="kcv2-head"><div><div class="kcv2-kicker">CONNECTED DATA</div><h3>Ce qui remonte de votre quotidien.</h3></div><p>Moyennes des 7 derniers jours disponibles. Les détails et comparaisons à votre baseline sont regroupés dans Résultats.</p></div>${last?`<div class="kcv2-grid"><article class="kcv2-metric"><small>Pas</small><strong>${fmtInt(s.steps7)}</strong><span>moyenne / jour</span></article><article class="kcv2-metric"><small>Sommeil</small><strong>${s.sleep7===null?'—':`${(s.sleep7/60).toLocaleString('fr-FR',{maximumFractionDigits:1})} h`}</strong><span>moyenne / nuit</span></article><article class="kcv2-metric"><small>FC repos</small><strong>${s.rhr7===null?'—':`${Math.round(s.rhr7)} bpm`}</strong><span>moyenne disponible</span></article><article class="kcv2-metric"><small>Temps actif</small><strong>${s.active7===null?'—':`${Math.round(s.active7)} min`}</strong><span>moyenne / jour</span></article><article class="kcv2-metric"><small>Distance</small><strong>${s.distance7===null?'—':`${(s.distance7/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})} km`}</strong><span>moyenne / jour</span></article><article class="kcv2-metric"><small>SpO₂</small><strong>${s.spo7===null?'—':`${s.spo7.toLocaleString('fr-FR',{maximumFractionDigits:1})}%`}</strong><span>moyenne compatible</span></article></div>`:'<div class="kcv2-empty">Aucune donnée connectée n’est encore disponible. Une fois la collecte activée et un dispositif compatible synchronisé, les premières métriques apparaîtront ici.</div>'}</article>
<article class="kcv2-card kcv2-section"><div class="kcv2-head"><div><div class="kcv2-kicker">CONNEXION</div><h3>Contrôler la continuité.</h3></div></div><div class="kcv2-status"><article class="kcv2-panel ${on?'good':''}"><small>Collecte</small><strong>${on?'Active':'Inactive'}</strong><p>${on?'Vos données compatibles peuvent alimenter Connected tant que ce consentement reste actif.':'Activez volontairement la collecte pour commencer le suivi connecté.'}</p><div class="kcv2-actions"><button class="kcv2-btn primary" type="button" data-connected-consent>${on?'Arrêter la collecte':'Activer la collecte'}</button></div></article><article class="kcv2-panel"><small>Couverture · 30 jours</small><strong>${s.coverage30}%</strong><p>${s.rows30} journée${s.rows30>1?'s':''} disponible${s.rows30>1?'s':''}. Une couverture faible est affichée comme telle et ne doit pas être surinterprétée.</p><div class="kcv2-actions"><button class="kcv2-btn" type="button" data-connected-results>Voir tous les détails dans Résultats</button></div></article></div></article>
</section>`}
function setChrome(){const eyebrow=document.querySelector('#pageEyebrow'),title=document.querySelector('#pageTitle');if(eyebrow)eyebrow.textContent='KŌMØ CONNECTED';if(title)title.textContent='Votre quotidien, connecté à votre trajectoire.'}
async function toggleConsent(){if(busy)return;busy=true;try{const d=await load(true),c=client();if(!d||!c)return;if(consentActive(d)){if(!confirm('Arrêter la collecte KŌMØ Connected ? Les données déjà enregistrées restent dans votre historique tant qu’elles ne sont pas supprimées.'))return;const r=await c.from('wearable_consents').update({status:'withdrawn',withdrawn_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',d.consent.id);if(r.error)throw r.error}else{const r=await c.from('wearable_consents').insert({user_id:d.session.user.id,purpose:'connected_followup',consent_version:'2026-09-01-connected-v2',status:'active',data_categories:['movement','sleep','heart_rate','spo2']});if(r.error)throw r.error}cache=null;window.dispatchEvent(new CustomEvent('komo:wearable-data-updated'));await render(true)}catch(e){console.error('[connected-v2]',e);alert(e.message||'Action impossible.')}finally{busy=false}}
function bind(root){root.querySelector('[data-connected-consent]')?.addEventListener('click',toggleConsent);root.querySelector('[data-connected-results]')?.addEventListener('click',()=>window.KomoPatientNavigation?.go?.('results')||(location.hash='results'))}
async function render(force=false){if(route()!=='key')return;style();document.body.classList.add('connected-v2');const root=document.querySelector('#viewRoot');if(!root)return;setChrome();root.innerHTML='<section class="kcv2"><div class="kcv2-empty">Chargement de KŌMØ Connected…</div></section>';try{const d=await load(force);if(route()!=='key')return;if(!d){root.innerHTML='<section class="kcv2"><div class="kcv2-empty">Session indisponible. Reconnectez-vous pour accéder à KŌMØ Connected.</div></section>';return}root.innerHTML=html(d);bind(root)}catch(e){console.error('[connected-v2]',e);root.innerHTML='<section class="kcv2"><div class="kcv2-empty">KŌMØ Connected est momentanément indisponible. Les autres espaces Pulse restent accessibles.</div></section>'}}
function enter(force=false){if(route()!=='key'){document.body.classList.remove('connected-v2');return}clearTimeout(timer);timer=setTimeout(()=>render(force),40)}
window.addEventListener('hashchange',()=>enter(false));window.addEventListener('pageshow',()=>enter(false));window.addEventListener('komo:session-ready',()=>enter(false));window.addEventListener('komo:wearable-data-updated',()=>{cache=null;enter(true)});document.addEventListener('DOMContentLoaded',()=>enter(false));setTimeout(()=>enter(false),800);window.KomoKeyHubV1={version:V,refresh:()=>render(true)};
})();
