import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL='https://uqlolefsiktbznnymriy.supabase.co';
const SUPABASE_KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REMEMBER_KEY='komo_pulse_remember';
const VERSION='1.0.0';
const ROUTE='key';
const LEGACY_ROUTE='followup';
const WEARABLE_FIELDS=['steps','distance_m','active_minutes','sedentary_minutes','avg_hr','resting_hr','hrv_ms','spo2_avg','sleep_minutes','deep_sleep_minutes','rem_sleep_minutes','wear_minutes'];

let client=null;
let cache=null;
let cacheAt=0;
let loading=false;
let renderTimer=null;
let homeTimer=null;
let importState={rows:[],fileName:'',format:''};

const storage=()=>localStorage.getItem(REMEMBER_KEY)==='1'?localStorage:sessionStorage;
const sb=()=>window.KomoRuntime?.client||(client||(client=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})));
const route=()=>location.hash.replace(/^#/,'')||'home';
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const fmtInt=v=>v==null?'—':Math.round(v).toLocaleString('fr-FR');
const fmtDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})};
const fmtDateTime=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})};
const dayKey=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),dd=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${dd}`};
const agoDays=n=>{const d=new Date();d.setDate(d.getDate()-n);return dayKey(d)};
const latest=(...values)=>values.filter(Boolean).map(v=>new Date(v)).filter(d=>!Number.isNaN(d.getTime())).sort((a,b)=>b-a)[0]||null;
const normKey=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/%/g,'pct').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');

function ensureStyle(){
  if(document.querySelector('#komoKeyStyle'))return;
  const s=document.createElement('style');s.id='komoKeyStyle';s.textContent=`
  :root{--kk-ink:#17221b;--kk-deep:#17261d;--kk-deep2:#263a2c;--kk-sage:#91a894;--kk-mint:#cddbcf;--kk-paper:#fbfaf6;--kk-ivory:#f3efe6;--kk-line:rgba(30,45,35,.09);--kk-muted:#758078;--kk-gold:#b59c6a}
  #desktopNav .kwf-nav-extra span,#mobileNav .kwf-nav-extra span{transition:opacity .2s ease}
  #desktopNav .kwf-nav-extra.kk-active,#mobileNav .kwf-nav-extra.kk-active{background:rgba(47,72,55,.08);color:#2c4735}
  #desktopNav .kwf-nav-extra.kk-active:before,#mobileNav .kwf-nav-extra.kk-active:before{content:"";width:5px;height:5px;border-radius:50%;background:#75937e;box-shadow:0 0 0 5px rgba(117,147,126,.12);position:absolute;right:12px}
  .kk-shell{display:grid;gap:14px;animation:kkFade .42s ease both}
  @keyframes kkFade{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
  .kk-hero{position:relative;min-height:330px;overflow:hidden;border-radius:32px;padding:34px;background:radial-gradient(circle at 78% 20%,rgba(160,187,164,.19),transparent 30%),linear-gradient(145deg,#16251c 0%,#243a2b 58%,#18281e 100%);color:#f7f5ef;border:1px solid rgba(255,255,255,.07);box-shadow:0 22px 55px rgba(25,39,30,.13)}
  .kk-hero:before{content:"";position:absolute;inset:0;opacity:.21;background-image:linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(90deg,transparent 0%,#000 35%,#000 100%)}
  .kk-scan{position:absolute;top:-30%;bottom:-30%;width:1px;left:55%;background:linear-gradient(180deg,transparent,rgba(190,218,194,.65),transparent);box-shadow:0 0 22px rgba(190,218,194,.25);animation:kkScan 7s ease-in-out infinite}
  @keyframes kkScan{0%,100%{transform:translateX(-210px);opacity:.1}50%{transform:translateX(300px);opacity:.8}}
  .kk-hero-grid{position:relative;z-index:2;display:grid;grid-template-columns:minmax(0,1.25fr) minmax(310px,.75fr);gap:28px;align-items:center;min-height:260px}
  .kk-kicker{margin:0 0 10px;font:800 7px/1 'DM Sans',sans-serif;letter-spacing:.18em;text-transform:uppercase;color:rgba(226,237,227,.63)}
  .kk-hero h2{margin:0;font:500 clamp(42px,6vw,72px)/.9 Manrope,'DM Sans',sans-serif;letter-spacing:-.065em;color:#fbfaf6}.kk-hero h2 em{display:block;font-style:normal;color:#a9bdaa}
  .kk-hero-copy{max-width:620px;margin:18px 0 0;color:rgba(243,246,240,.68);font-size:11px;line-height:1.65}
  .kk-hero-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.kk-btn{appearance:none;border:0;border-radius:14px;padding:11px 15px;font:700 8px/1 'DM Sans',sans-serif;letter-spacing:.02em;cursor:pointer;transition:.22s ease}.kk-btn:hover{transform:translateY(-1px)}.kk-btn.primary{background:#f5f2ea;color:#1d3023}.kk-btn.ghost{background:rgba(255,255,255,.08);color:#fff;border:1px solid rgba(255,255,255,.1)}.kk-btn.soft{background:#e8eee7;color:#294333;border:1px solid rgba(36,60,44,.07)}.kk-btn.dark{background:#23392a;color:#fff}.kk-btn[disabled]{opacity:.45;cursor:not-allowed;transform:none}
  .kk-orbit{position:relative;width:252px;height:252px;margin:auto;border:1px solid rgba(255,255,255,.1);border-radius:50%;display:grid;place-items:center;box-shadow:inset 0 0 48px rgba(255,255,255,.025)}.kk-orbit:before,.kk-orbit:after{content:"";position:absolute;border:1px solid rgba(255,255,255,.075);border-radius:50%}.kk-orbit:before{inset:27px}.kk-orbit:after{inset:60px}
  .kk-core{position:relative;z-index:3;width:98px;height:98px;border-radius:32px;background:linear-gradient(145deg,rgba(255,255,255,.14),rgba(255,255,255,.055));border:1px solid rgba(255,255,255,.13);backdrop-filter:blur(14px);display:grid;place-items:center;text-align:center;box-shadow:0 16px 40px rgba(0,0,0,.13)}.kk-core strong{font:600 22px/1 Manrope,sans-serif;letter-spacing:-.06em}.kk-core span{display:block;margin-top:5px;font-size:6px;letter-spacing:.14em;text-transform:uppercase;color:rgba(255,255,255,.52)}
  .kk-node{--a:0deg;--r:126px;position:absolute;left:50%;top:50%;transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(var(--r)*-1)) rotate(calc(var(--a)*-1));width:13px;height:13px;border-radius:50%;background:#53685a;border:2px solid rgba(255,255,255,.2);box-shadow:0 0 0 6px rgba(255,255,255,.025)}.kk-node.live{background:#b2c9b5;box-shadow:0 0 0 7px rgba(178,201,181,.08),0 0 20px rgba(178,201,181,.2);animation:kkPulse 2.6s ease-in-out infinite}.kk-node:after{content:attr(data-label);position:absolute;white-space:nowrap;left:18px;top:-1px;color:rgba(255,255,255,.56);font:700 6px/1 'DM Sans',sans-serif;letter-spacing:.08em;text-transform:uppercase}.kk-node:nth-of-type(n+5):after{left:auto;right:18px;text-align:right}
  @keyframes kkPulse{0%,100%{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(var(--r)*-1)) rotate(calc(var(--a)*-1)) scale(.92)}50%{transform:translate(-50%,-50%) rotate(var(--a)) translateY(calc(var(--r)*-1)) rotate(calc(var(--a)*-1)) scale(1.1)}}
  .kk-hero-stats{position:absolute;z-index:3;left:34px;right:34px;bottom:24px;display:flex;gap:24px;align-items:flex-end}.kk-stat strong{display:block;font:500 18px/1 Manrope,sans-serif;letter-spacing:-.045em}.kk-stat span{display:block;margin-top:4px;color:rgba(255,255,255,.46);font-size:6px;letter-spacing:.08em;text-transform:uppercase}.kk-stat-sep{height:25px;width:1px;background:rgba(255,255,255,.1)}
  .kk-domain-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.kk-domain{position:relative;overflow:hidden;border:1px solid var(--kk-line);border-radius:19px;padding:16px;background:rgba(255,255,255,.72);min-height:126px;cursor:pointer;transition:.25s ease;box-shadow:0 10px 25px rgba(31,44,36,.025)}.kk-domain:hover{transform:translateY(-2px);background:#fff}.kk-domain:before{content:"";position:absolute;inset:auto -20px -35px auto;width:78px;height:78px;border:1px solid rgba(47,75,57,.06);border-radius:50%}.kk-domain-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.kk-domain-icon{width:28px;height:28px;border-radius:10px;background:#edf1eb;color:#3b5945;display:grid;place-items:center;font:800 7px/1 'DM Sans',sans-serif;letter-spacing:.05em}.kk-live{width:6px;height:6px;border-radius:50%;background:#d1d5cf}.kk-live.on{background:#76917b;box-shadow:0 0 0 5px rgba(118,145,123,.1)}.kk-domain strong{display:block;margin-top:18px;font:600 21px/1 Manrope,sans-serif;letter-spacing:-.05em;color:#26372d}.kk-domain h3{margin:5px 0 0;font:650 9px/1.15 'DM Sans',sans-serif;color:#334238}.kk-domain p{margin:5px 0 0;color:#818a84;font-size:6.5px;line-height:1.35}
  .kk-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(330px,.85fr);gap:10px}.kk-card{border:1px solid var(--kk-line);border-radius:23px;background:rgba(255,255,255,.77);padding:22px;box-shadow:0 12px 32px rgba(31,44,36,.028)}.kk-card-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:18px}.kk-card-head h3{margin:4px 0 0;font:600 20px/1.05 Manrope,sans-serif;letter-spacing:-.045em;color:#26372d}.kk-card-head p{margin:0;color:#7a847d;font-size:7px;line-height:1.45}.kk-card-head .kk-kicker{color:#7a867d;margin:0}
  .kk-signal{position:relative;height:265px;border-radius:18px;overflow:hidden;background:linear-gradient(155deg,#eef2eb,#f8f6f0);border:1px solid rgba(35,52,40,.06)}.kk-signal-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(35,52,40,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(35,52,40,.045) 1px,transparent 1px);background-size:32px 32px}.kk-signal-line{position:absolute;left:6%;right:6%;top:50%;height:1px;background:rgba(35,52,40,.11)}.kk-wave{position:absolute;inset:25px 16px;display:flex;align-items:center}.kk-wave svg{width:100%;height:100%;overflow:visible}.kk-wave path{fill:none;stroke:#496b54;stroke-width:2.2;stroke-linecap:round;filter:drop-shadow(0 6px 9px rgba(73,107,84,.12));stroke-dasharray:900;animation:kkDraw 2.1s ease both}@keyframes kkDraw{from{stroke-dashoffset:900}to{stroke-dashoffset:0}}
  .kk-signal-nodes{position:absolute;inset:0}.kk-signal-dot{position:absolute;width:10px;height:10px;border-radius:50%;background:#fff;border:2px solid #6e8a74;box-shadow:0 0 0 5px rgba(110,138,116,.09)}.kk-signal-dot span{position:absolute;top:15px;left:50%;transform:translateX(-50%);white-space:nowrap;padding:4px 6px;border-radius:8px;background:rgba(255,255,255,.8);color:#607067;font-size:5.5px;font-weight:800;letter-spacing:.05em;text-transform:uppercase}.kk-signal-dot.d1{left:14%;top:46%}.kk-signal-dot.d2{left:34%;top:35%}.kk-signal-dot.d3{left:52%;top:53%}.kk-signal-dot.d4{left:70%;top:27%}.kk-signal-dot.d5{left:86%;top:43%}
  .kk-quality{display:grid;grid-template-columns:110px 1fr;gap:18px;align-items:center}.kk-gauge{--p:0;width:108px;height:108px;border-radius:50%;background:conic-gradient(#45664f calc(var(--p)*1%),#e3e7e1 0);display:grid;place-items:center;position:relative}.kk-gauge:after{content:"";position:absolute;inset:9px;border-radius:50%;background:#fbfaf6}.kk-gauge div{position:relative;z-index:2;text-align:center}.kk-gauge strong{display:block;font:600 22px/1 Manrope,sans-serif;letter-spacing:-.05em;color:#283a2e}.kk-gauge span{display:block;margin-top:4px;color:#7b877f;font-size:5.5px;text-transform:uppercase;letter-spacing:.08em}.kk-quality-list{display:grid;gap:9px}.kk-qrow{display:grid;grid-template-columns:1fr auto;gap:10px;padding-bottom:8px;border-bottom:1px solid rgba(31,44,36,.06);font-size:7px;color:#77827a}.kk-qrow:last-child{border-bottom:0;padding-bottom:0}.kk-qrow strong{color:#33453a;font-size:7.5px}
  .kk-spark{height:82px;display:flex;gap:3px;align-items:end;margin-top:14px}.kk-spark i{flex:1;min-width:2px;border-radius:4px 4px 2px 2px;background:linear-gradient(180deg,#5f816a,#b5c7b8);opacity:.9;transform-origin:bottom;animation:kkBars .65s ease both}@keyframes kkBars{from{transform:scaleY(.05);opacity:.2}to{transform:scaleY(1);opacity:.9}}
  .kk-stream{padding:0;overflow:hidden}.kk-stream-head{padding:20px 22px 14px;display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.kk-stream-head h3{margin:4px 0 0;font:600 20px/1.05 Manrope,sans-serif;letter-spacing:-.04em;color:#27382d}.kk-tools{display:flex;gap:6px;align-items:center}.kk-tools input,.kk-tools select{border:1px solid rgba(34,52,40,.08);background:#f8f6f0;color:#435148;border-radius:11px;padding:9px 10px;font:600 7px/1 'DM Sans',sans-serif;outline:none}.kk-tools input{min-width:170px}.kk-table-wrap{overflow:auto;border-top:1px solid rgba(31,44,36,.06)}.kk-table{width:100%;border-collapse:collapse;min-width:700px}.kk-table th{padding:10px 14px;text-align:left;font:800 5.8px/1 'DM Sans',sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#8b928d;background:#f8f6f1;border-bottom:1px solid rgba(31,44,36,.06)}.kk-table td{padding:11px 14px;border-bottom:1px solid rgba(31,44,36,.055);font-size:7.5px;color:#647168;vertical-align:middle}.kk-table tr:last-child td{border-bottom:0}.kk-table strong{color:#34463a;font-size:8px}.kk-source{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf1eb;color:#52675a;font-size:5.7px;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.kk-qc{display:inline-flex;align-items:center;gap:5px;font-size:6.5px;color:#748078}.kk-qc i{width:6px;height:6px;border-radius:50%;background:#c9cec8}.kk-qc.valid i{background:#78957e}.kk-qc.suspect i,.kk-qc.pending i{background:#b89d68}.kk-empty{padding:28px;color:#7b857e;font-size:8px;line-height:1.6;text-align:center}
  .kk-home-inline{margin-top:8px;padding:9px 11px;border-radius:13px;background:rgba(255,255,255,.72);border:1px solid rgba(31,44,36,.065);display:flex;align-items:center;justify-content:space-between;gap:10px}.kk-home-inline span{color:#66736b;font-size:6.2px}.kk-home-inline strong{color:#31463a;font-size:7px}.kk-home-inline button{border:0;background:transparent;color:#365542;font:800 6.5px/1 'DM Sans',sans-serif;cursor:pointer}
  .kk-home-card{margin-top:12px;border:1px solid var(--kk-line);border-radius:20px;padding:15px 17px;background:linear-gradient(145deg,#fdfcf8,#f0f3ed);display:flex;align-items:center;justify-content:space-between;gap:14px;box-shadow:0 10px 26px rgba(31,44,36,.025)}.kk-home-card-left{display:flex;align-items:center;gap:11px}.kk-home-key{width:42px;height:42px;border-radius:14px;background:#253c2d;color:#fff;display:grid;place-items:center;font:800 7px/1 'DM Sans',sans-serif;letter-spacing:.1em}.kk-home-card small{display:block;color:#7c867f;font-size:5.5px;letter-spacing:.12em;text-transform:uppercase}.kk-home-card strong{display:block;margin-top:4px;color:#2d4134;font:600 13px/1.1 Manrope,sans-serif;letter-spacing:-.025em}.kk-home-meta{display:flex;align-items:center;gap:12px;color:#748078;font-size:6.5px}.kk-home-card button{border:0;background:#e5ece4;color:#2e4c39;border-radius:11px;padding:9px 11px;font:800 6.5px/1 'DM Sans',sans-serif;cursor:pointer}
  .kk-modal{position:fixed;inset:0;z-index:1000;background:rgba(17,26,20,.52);backdrop-filter:blur(10px);display:grid;place-items:center;padding:18px;animation:kkFade .2s ease both}.kk-modal-panel{width:min(900px,96vw);max-height:90vh;overflow:auto;border-radius:28px;background:#f9f7f1;border:1px solid rgba(255,255,255,.35);box-shadow:0 30px 80px rgba(16,26,19,.26)}.kk-modal-head{position:sticky;top:0;z-index:2;padding:20px 22px;background:rgba(249,247,241,.92);backdrop-filter:blur(16px);display:flex;align-items:flex-start;justify-content:space-between;gap:14px;border-bottom:1px solid rgba(31,44,36,.07)}.kk-modal-head h3{margin:5px 0 0;font:600 24px/1 Manrope,sans-serif;letter-spacing:-.045em;color:#26382c}.kk-close{border:0;width:34px;height:34px;border-radius:12px;background:#e9ece6;color:#425448;font-size:18px;cursor:pointer}.kk-modal-body{padding:22px}.kk-import-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.kk-import-choice{border:1px solid rgba(31,44,36,.08);border-radius:18px;padding:16px;background:#fff;text-align:left;cursor:pointer;transition:.2s ease}.kk-import-choice:hover,.kk-import-choice.active{border-color:rgba(53,83,63,.24);background:#f0f4ee}.kk-import-choice strong{display:block;color:#314438;font-size:9px}.kk-import-choice span{display:block;margin-top:6px;color:#7a857e;font-size:6.5px;line-height:1.45}.kk-import-stage{margin-top:12px;border:1px solid rgba(31,44,36,.07);border-radius:18px;background:#fff;padding:18px}.kk-drop{border:1px dashed rgba(42,65,49,.2);border-radius:15px;padding:24px;text-align:center;background:#fafaf7}.kk-drop strong{display:block;color:#33483a;font-size:10px}.kk-drop span{display:block;margin-top:7px;color:#7b867f;font-size:7px}.kk-drop input{margin-top:12px;font-size:8px}.kk-preview{overflow:auto;margin-top:13px;border:1px solid rgba(31,44,36,.07);border-radius:13px}.kk-preview table{width:100%;border-collapse:collapse;min-width:650px}.kk-preview th,.kk-preview td{padding:8px 9px;border-bottom:1px solid rgba(31,44,36,.05);font-size:6.5px;text-align:left}.kk-preview th{background:#f7f6f1;color:#818b84;text-transform:uppercase;letter-spacing:.08em;font-size:5.5px}.kk-import-status{margin-top:10px;color:#5d6d63;font-size:7px;line-height:1.45}.kk-governance{padding:15px;border-radius:14px;background:#f0f2ed;color:#66736b;font-size:7px;line-height:1.55}.kk-governance strong{color:#34483b}
  @media(max-width:1180px){.kk-domain-grid{grid-template-columns:repeat(3,1fr)}.kk-hero-grid{grid-template-columns:1fr 300px}.kk-orbit{width:225px;height:225px}.kk-node{--r:112px}}
  @media(max-width:900px){.kk-hero-grid,.kk-grid{grid-template-columns:1fr}.kk-hero{padding:28px;padding-bottom:92px}.kk-orbit{display:none}.kk-domain-grid{grid-template-columns:repeat(3,1fr)}.kk-import-grid{grid-template-columns:1fr}.kk-home-meta{display:none}}
  @media(max-width:700px){.kk-hero{border-radius:24px;min-height:350px;padding:23px;padding-bottom:105px}.kk-hero h2{font-size:46px}.kk-hero-stats{left:23px;right:23px;bottom:22px;gap:13px;flex-wrap:wrap}.kk-stat-sep{display:none}.kk-domain-grid{grid-template-columns:1fr 1fr}.kk-card{padding:18px;border-radius:20px}.kk-quality{grid-template-columns:90px 1fr}.kk-gauge{width:88px;height:88px}.kk-tools{width:100%;flex-wrap:wrap}.kk-tools input{min-width:0;flex:1}.kk-stream-head{align-items:flex-start;flex-direction:column}.kk-home-card{align-items:flex-start;flex-direction:column}.kk-home-card button{width:100%}}
  @media(prefers-reduced-motion:reduce){.kk-shell,.kk-scan,.kk-node.live,.kk-wave path,.kk-spark i{animation:none!important}}
  `;document.head.appendChild(s);
}

function keyIcon(){return '<svg class="kwf-nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 12h5l2-5 3 10 2-5h4"/><circle cx="4" cy="12" r="1.5"/><circle cx="20" cy="12" r="1.5"/></svg>'}
function ensureNav(){
  const patch=nav=>{
    if(!nav)return;
    let b=nav.querySelector('[data-route="followup"]');
    if(!b){b=document.createElement('button');b.type='button';b.className='nav-item kwf-nav-extra';b.dataset.route='followup';const results=nav.querySelector('[data-route="results"]');results?.insertAdjacentElement('afterend',b)||nav.appendChild(b)}
    b.setAttribute('aria-label','KŌMØ Key');b.innerHTML=`${keyIcon()}<span>Key</span>`;
  };
  patch(document.querySelector('#desktopNav'));patch(document.querySelector('#mobileNav'));markNav();
}
function markNav(){
  if(route()!==ROUTE)return;
  document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active','kk-active'));
  document.querySelectorAll('[data-route="followup"]').forEach(x=>x.classList.add('active','kk-active'));
}

async function safe(query){try{const r=await query;return r?.error?[]:(r?.data||[])}catch{return[]}}
async function safeOne(query){try{const r=await query;return r?.error?null:(r?.data||null)}catch{return null}}
async function load(force=false){
  if(!force&&cache&&Date.now()-cacheAt<30000)return cache;
  if(loading&&cache)return cache;loading=true;
  try{
    const c=sb(),session=(await c.auth.getSession()).data?.session;if(!session?.user)return null;const userId=session.user.id;
    const [roleRow,patient,wearables,devices,activity,freeAssessment,defs]=await Promise.all([
      safeOne(c.from('account_roles').select('role').eq('user_id',userId).maybeSingle()),
      safeOne(c.from('patients').select('*').eq('patient_user_id',userId).order('created_at',{ascending:false}).limit(1).maybeSingle()),
      safe(c.from('wearable_daily_metrics').select('*').eq('user_id',userId).gte('metric_date',agoDays(90)).order('metric_date',{ascending:true})),
      safe(c.from('wearable_devices').select('*').eq('user_id',userId).order('created_at',{ascending:false})),
      safe(c.from('komo_activity_entries').select('*').eq('user_id',userId).gte('activity_date',agoDays(90)).order('activity_date',{ascending:false})),
      safeOne(c.from('pulse_assessments').select('*').eq('user_id',userId).order('updated_at',{ascending:false}).limit(1).maybeSingle()),
      safe(c.from('indicator_definitions').select('code,label_fr,domain,scoring_role,product_status'))
    ]);
    let assessments=[],measurements=[],questionnaireSessions=[],questionnaireResponses=[],documents=[],scores=[],imports=[];
    if(patient?.id){
      assessments=await safe(c.from('assessments').select('*').eq('patient_id',patient.id).order('created_at',{ascending:false}).limit(6));
      const ids=assessments.map(x=>x.id);
      if(ids.length){
        [measurements,questionnaireSessions,documents,scores,imports]=await Promise.all([
          safe(c.from('measurements').select('*').in('assessment_id',ids).order('recorded_at',{ascending:false}).limit(500)),
          safe(c.from('questionnaire_sessions').select('*').in('assessment_id',ids).order('created_at',{ascending:false})),
          safe(c.from('assessment_documents').select('*').in('assessment_id',ids).order('created_at',{ascending:false})),
          safe(c.from('scores').select('*').in('assessment_id',ids).order('calculated_at',{ascending:false})),
          safe(c.from('myodev_imports').select('id,assessment_id,source_product,source_version,source_format,source_file_name,status,recorded_at,created_at,warnings').in('assessment_id',ids).order('created_at',{ascending:false}))
        ]);
        const qids=questionnaireSessions.map(x=>x.id);if(qids.length)questionnaireResponses=await safe(c.from('questionnaire_responses').select('*').in('questionnaire_session_id',qids).order('created_at',{ascending:false}).limit(600));
      }
    }
    const data={session,userId,role:roleRow?.role||'member',patient,assessments,measurements,questionnaireSessions,questionnaireResponses,documents,scores,imports,wearables,devices,activity,freeAssessment,defs};
    data.summary=summarize(data);data.stream=buildStream(data);cache=data;cacheAt=Date.now();return data;
  }finally{loading=false}
}

function wearablePointCount(rows){return rows.reduce((sum,row)=>sum+WEARABLE_FIELDS.reduce((n,k)=>n+(row[k]!==null&&row[k]!==undefined?1:0),0),0)}
function measurementCategory(m,def){const code=String(m.indicator_code||'').toLowerCase(),source=String(m.source||'').toLowerCase(),task=String(m.task_code||'').toLowerCase(),domain=String(def?.domain||'').toLowerCase();if(source==='laboratory'||/bio|hba|crp|vit|apo|ldl|ferr|homa/.test(code))return'biology';if(source==='imaging'||/sva|pi.?ll|postur|eos|angle/.test(code))return'posture';if((m.muscle_code&&m.muscle_code!=='NA')||/myo|mvc|cci|lsi|muscle/.test(code)||domain==='muscle_control')return'muscle';if(source==='myocare'||task||['mobility','performance','balance'].includes(domain))return'motion';return'motion'}
function summarize(d){
  const defMap=Object.fromEntries((d.defs||[]).map(x=>[x.code,x]));const cats={motion:0,muscle:0,posture:0,biology:0,daily:wearablePointCount(d.wearables),context:d.questionnaireResponses.length};
  d.measurements.forEach(m=>cats[measurementCategory(m,defMap[m.indicator_code])]++);
  if(d.freeAssessment?.responses&&typeof d.freeAssessment.responses==='object')cats.context+=Object.keys(d.freeAssessment.responses).length;
  const points=Object.values(cats).reduce((a,b)=>a+b,0)+d.activity.length;
  const sources=new Set();d.measurements.forEach(m=>sources.add(sourceLabel(m.source)));if(cats.daily||d.activity.length)sources.add('Connected');if(cats.context)sources.add('Questionnaires');d.documents.forEach(x=>sources.add(docSource(x.document_type)));
  const qrows=d.measurements.filter(x=>['valid','suspect','invalid','pending'].includes(x.qc_status));const valid=qrows.filter(x=>x.qc_status==='valid').length;const qc=qrows.length?Math.round(valid/qrows.length*100):null;
  const recent30=d.wearables.filter(x=>x.metric_date>=agoDays(29));const days30=new Set(recent30.map(x=>x.metric_date)).size,coverage=Math.round(days30/30*100);
  const last=latest(d.measurements[0]?.recorded_at,d.wearables.at(-1)?.metric_date?`${d.wearables.at(-1).metric_date}T12:00:00`:null,d.questionnaireResponses[0]?.created_at,d.documents[0]?.created_at,d.assessments[0]?.updated_at,d.activity[0]?.activity_date?`${d.activity[0].activity_date}T12:00:00`:null);
  return{cats,points,sources:[...sources].filter(Boolean),sourceCount:sources.size,qc,coverage,last,days30,assessmentCount:d.assessments.length,documentCount:d.documents.length};
}
function sourceLabel(s){const map={myocare:'MyoCare',laboratory:'Biologie',imaging:'Imagerie',patient:'Patient',operator:'KŌMØ Motion',clinician:'Clinical',derived:'KŌMØ',manual_import:'Import',wearable:'Connected'};return map[String(s||'').toLowerCase()]||String(s||'KŌMØ')}
function docSource(t){return t==='laboratory'?'Biologie':t==='imaging'?'Imagerie':t==='myocare_export'?'MyoCare':'Documents'}
function catLabel(k){return({motion:'Motion',muscle:'Muscle',posture:'Posture',biology:'Biologie',daily:'Daily',context:'Context'})[k]||k}
function qcLabel(q){return({valid:'Validé',suspect:'À contrôler',invalid:'Non retenu',missing:'Manquant',pending:'En attente'})[q]||'Traçable'}
function buildStream(d){
  const defMap=Object.fromEntries((d.defs||[]).map(x=>[x.code,x]));const out=[];
  d.measurements.forEach(m=>{const def=defMap[m.indicator_code],cat=measurementCategory(m,def);out.push({date:m.recorded_at||m.created_at,category:cat,source:sourceLabel(m.source),label:def?.label_fr||m.indicator_code||'Mesure',value:m.numeric_value??m.text_value??'—',unit:m.unit||'',qc:m.qc_status||'pending',detail:[m.task_code,m.muscle_code,m.side].filter(Boolean).join(' · ')})});
  d.questionnaireSessions.forEach(q=>out.push({date:q.completed_at||q.updated_at||q.created_at,category:'context',source:'Questionnaire',label:q.instrument_code||'Questionnaire',value:q.score??`${Math.round(Number(q.completeness||0))}%`,unit:q.score!=null?'':'complété',qc:q.score_status==='valid'?'valid':q.status==='completed'?'valid':'pending',detail:q.instrument_version||''}));
  d.wearables.slice(-30).forEach(w=>out.push({date:`${w.metric_date}T12:00:00`,category:'daily',source:'Connected',label:'Daily Motion',value:w.steps??w.active_minutes??'—',unit:w.steps!=null?'pas':w.active_minutes!=null?'min':'',qc:w.wear_minutes&&w.wear_minutes<300?'suspect':'valid',detail:[w.resting_hr!=null?`${Math.round(w.resting_hr)} bpm repos`:null,w.sleep_minutes!=null?`${(w.sleep_minutes/60).toFixed(1)} h sommeil`:null].filter(Boolean).join(' · ')}));
  d.documents.forEach(doc=>out.push({date:doc.source_date||doc.created_at,category:doc.document_type==='laboratory'?'biology':doc.document_type==='imaging'?'posture':'context',source:docSource(doc.document_type),label:doc.file_name||doc.document_type,value:'Document',unit:'',qc:doc.verification_status==='verified'?'valid':doc.verification_status==='rejected'?'invalid':'pending',detail:doc.document_type}));
  return out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,160)
}

function domainCard(key,count,copy,icon){return`<button type="button" class="kk-domain" data-kk-filter="${key}"><div class="kk-domain-top"><span class="kk-domain-icon">${icon}</span><i class="kk-live ${count?'on':''}"></i></div><strong>${fmtInt(count)}</strong><h3>${catLabel(key)}</h3><p>${copy}</p></button>`}
function orbitNode(label,a,live){return`<i class="kk-node ${live?'live':''}" style="--a:${a}deg" data-label="${label}"></i>`}
function spark(rows){const last=rows.slice(-21),vals=last.map(x=>num(x.steps)||num(x.active_minutes)||0),max=Math.max(1,...vals);if(!last.length)return'<div class="kk-empty">Les courbes quotidiennes apparaîtront après une première synchronisation.</div>';return`<div class="kk-spark">${vals.map((v,i)=>`<i style="height:${Math.max(4,(v/max)*100)}%;animation-delay:${i*18}ms" title="${fmtInt(v)}"></i>`).join('')}</div>`}
function signalWave(data){const s=data.summary,c=s.cats,weights=[c.motion,c.muscle,c.posture,c.biology,c.daily,c.context].map(x=>Math.min(34,6+Math.log10(x+1)*18));const pts=weights.map((v,i)=>`${i===0?'M':'L'} ${i*(100/(weights.length-1))} ${50+(i%2?-1:1)*v}`).join(' ');return`<div class="kk-signal"><div class="kk-signal-grid"></div><div class="kk-signal-line"></div><div class="kk-wave"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="${pts}"/></svg></div><div class="kk-signal-nodes"><i class="kk-signal-dot d1"><span>Motion</span></i><i class="kk-signal-dot d2"><span>Muscle</span></i><i class="kk-signal-dot d3"><span>Posture</span></i><i class="kk-signal-dot d4"><span>Daily</span></i><i class="kk-signal-dot d5"><span>Context</span></i></div></div>`}
function renderMain(data){
  const s=data.summary,c=s.cats,qc=s.qc??Math.min(100,Math.round((s.coverage*.35)+(s.points?60:0))),activeDevice=data.devices.find(x=>x.status==='active')||data.devices[0];
  return`<div class="kk-shell"><section class="kk-hero"><div class="kk-scan"></div><div class="kk-hero-grid"><div><p class="kk-kicker">KŌMØ KEY · DATA LAYER</p><h2>Every signal.<em>One key.</em></h2><p class="kk-hero-copy">KŌMØ Key rassemble les données capturées au cours de votre parcours — mouvement instrumenté, fonction musculaire, posture, biologie, questionnaires et suivi quotidien. Chaque donnée conserve sa source, sa date et son statut de qualité.</p><div class="kk-hero-actions"><button class="kk-btn primary" type="button" id="kkImportOpen">Importer des données</button><button class="kk-btn ghost" type="button" id="kkGoResults">Voir l’interprétation →</button></div></div><div class="kk-orbit"><div class="kk-core"><div><strong>KEY</strong><span>data signature</span></div></div>${orbitNode('Motion',0,c.motion)}${orbitNode('Muscle',60,c.muscle)}${orbitNode('Posture',120,c.posture)}${orbitNode('Biologie',180,c.biology)}${orbitNode('Daily',240,c.daily)}${orbitNode('Context',300,c.context)}</div></div><div class="kk-hero-stats"><div class="kk-stat"><strong>${fmtInt(s.points)}</strong><span>points capturés</span></div><i class="kk-stat-sep"></i><div class="kk-stat"><strong>${s.sourceCount}</strong><span>sources actives</span></div><i class="kk-stat-sep"></i><div class="kk-stat"><strong>${fmtDate(s.last)}</strong><span>dernière capture</span></div><i class="kk-stat-sep"></i><div class="kk-stat"><strong>${s.assessmentCount}</strong><span>évaluations reliées</span></div></div></section>
  <section class="kk-domain-grid">${domainCard('motion',c.motion,'Marche, tests fonctionnels, cinématique.','M')}${domainCard('muscle',c.muscle,'Activation, force, asymétries, contrôle.','μ')}${domainCard('posture',c.posture,'Repères posturaux et données d’imagerie.','P')}${domainCard('biology',c.biology,'Biomarqueurs reçus dans le parcours Clinical.','B')}${domainCard('daily',c.daily,'Activité, récupération et données connectées.','D')}${domainCard('context',c.context,'Questionnaires, contexte et ressenti fonctionnel.','C')}</section>
  <section class="kk-grid"><article class="kk-card"><div class="kk-card-head"><div><p class="kk-kicker">SIGNAL MAP</p><h3>Votre signature de données</h3></div><p>${s.points?'Une vue de la densité des couches capturées.':'Votre carte se construit mesure après mesure.'}</p></div>${signalWave(data)}</article><aside class="kk-card"><div class="kk-card-head"><div><p class="kk-kicker">DATA INTEGRITY</p><h3>Qualité & provenance</h3></div><p>Traçabilité avant interprétation.</p></div><div class="kk-quality"><div class="kk-gauge" style="--p:${qc}"><div><strong>${qc}%</strong><span>signal utile</span></div></div><div class="kk-quality-list"><div class="kk-qrow"><span>QC des mesures</span><strong>${s.qc==null?'À qualifier':`${s.qc}% valides`}</strong></div><div class="kk-qrow"><span>Couverture connected · 30 j</span><strong>${s.coverage}%</strong></div><div class="kk-qrow"><span>Documents reliés</span><strong>${s.documentCount}</strong></div><div class="kk-qrow"><span>Appareil actif</span><strong>${esc(activeDevice?.display_name||activeDevice?.model||'Aucun')}</strong></div></div></div>${spark(data.wearables)}</aside></section>
  <section class="kk-card kk-stream"><div class="kk-stream-head"><div><p class="kk-kicker">CAPTURED DATA</p><h3>Flux de données</h3></div><div class="kk-tools"><input id="kkSearch" type="search" placeholder="Rechercher une mesure…"><select id="kkFilter"><option value="all">Toutes les couches</option><option value="motion">Motion</option><option value="muscle">Muscle</option><option value="posture">Posture</option><option value="biology">Biologie</option><option value="daily">Daily</option><option value="context">Context</option></select></div></div><div class="kk-table-wrap"><table class="kk-table"><thead><tr><th>Date</th><th>Couche</th><th>Donnée</th><th>Valeur</th><th>Source</th><th>Qualité</th></tr></thead><tbody id="kkStreamBody"></tbody></table></div></section>
  <section class="kk-card"><div class="kk-card-head"><div><p class="kk-kicker">PROVENANCE</p><h3>La donnée reste distincte de son interprétation.</h3></div><p>KŌMØ Key est la couche de collecte et de traçabilité. Le score et l’interprétation clinique restent séparés.</p></div><div class="kk-governance"><strong>Architecture KŌMØ.</strong> Les imports instrumentés MyoCare/MyoDev, biologiques et d’imagerie passent par le flux professionnel lorsqu’une validation est requise. Les données quotidiennes personnelles peuvent être importées dans Key et restent identifiées comme données de suivi.</div></section></div>`
}
function renderStream(data,filter='all',query=''){
  const body=document.querySelector('#kkStreamBody');if(!body)return;const q=query.toLowerCase().trim();const rows=data.stream.filter(x=>(filter==='all'||x.category===filter)&&(!q||`${x.label} ${x.source} ${x.detail} ${x.value}`.toLowerCase().includes(q))).slice(0,80);
  body.innerHTML=rows.length?rows.map(x=>`<tr><td>${fmtDate(x.date)}</td><td><strong>${catLabel(x.category)}</strong></td><td><strong>${esc(x.label)}</strong>${x.detail?`<div style="margin-top:3px;color:#8a918c;font-size:6px">${esc(x.detail)}</div>`:''}</td><td>${esc(x.value)}${x.unit?` <span style="color:#8b928d">${esc(x.unit)}</span>`:''}</td><td><span class="kk-source">${esc(x.source)}</span></td><td><span class="kk-qc ${esc(x.qc)}"><i></i>${qcLabel(x.qc)}</span></td></tr>`).join(''):`<tr><td colspan="6"><div class="kk-empty">Aucune donnée ne correspond à ce filtre.</div></td></tr>`
}

function bindMain(data){
  document.querySelector('#kkImportOpen')?.addEventListener('click',()=>openImport(data));document.querySelector('#kkGoResults')?.addEventListener('click',()=>location.hash='results');
  const search=document.querySelector('#kkSearch'),filter=document.querySelector('#kkFilter');const apply=()=>renderStream(data,filter?.value||'all',search?.value||'');search?.addEventListener('input',apply);filter?.addEventListener('change',apply);
  document.querySelectorAll('[data-kk-filter]').forEach(b=>b.addEventListener('click',()=>{if(filter)filter.value=b.dataset.kkFilter;apply();document.querySelector('.kk-stream')?.scrollIntoView({behavior:'smooth',block:'start'})}));renderStream(data)
}

async function render(force=false){
  if(route()!==ROUTE)return;ensureStyle();ensureNav();markNav();const root=document.querySelector('#viewRoot');if(!root)return;const eyebrow=document.querySelector('#pageEyebrow'),title=document.querySelector('#pageTitle');if(eyebrow)eyebrow.textContent='KŌMØ KEY · DATA LAYER';if(title)title.textContent='Vos données, rendues lisibles.';root.innerHTML='<div class="kk-card kk-empty">Synchronisation des sources KŌMØ…</div>';
  const data=await load(force);if(route()!==ROUTE)return;if(!data){root.innerHTML='<div class="kk-card kk-empty">Connectez-vous à Pulse pour ouvrir KŌMØ Key.</div>';return}root.innerHTML=renderMain(data);bindMain(data);markNav();window.dispatchEvent(new CustomEvent('komo:key-ready',{detail:{version:VERSION,points:data.summary.points,sources:data.summary.sourceCount}}))
}
function schedule(force=false){clearTimeout(renderTimer);renderTimer=setTimeout(()=>render(force),60)}

function homeAnchor(){return document.querySelector('[data-kw-home]')?.parentElement||document.querySelector('.kdw-connected')||document.querySelector('.hero-grid')||document.querySelector('.kdw')||document.querySelector('#viewRoot')}
async function patchHome(){
  if(route()!=='home')return;ensureNav();const host=homeAnchor();if(!host||document.querySelector('[data-kk-home-summary]'))return;const data=await load(false);if(route()!=='home'||!data)return;const s=data.summary;
  if(document.querySelector('[data-kw-home]')){const target=document.querySelector('[data-kw-home]')?.parentElement||host;target.insertAdjacentHTML('beforeend',`<div class="kk-home-inline" data-kk-home-summary><span><strong>${fmtInt(s.points)} points</strong> · ${s.sourceCount} sources · dernière capture ${fmtDate(s.last)}</span><button type="button" data-kk-open>Ouvrir toutes les données →</button></div>`)}else{host.insertAdjacentHTML('afterend',`<div class="kk-home-card" data-kk-home-summary><div class="kk-home-card-left"><div class="kk-home-key">KEY</div><div><small>KŌMØ KEY · DATA LAYER</small><strong>${fmtInt(s.points)} points · ${s.sourceCount} sources</strong></div></div><div class="kk-home-meta"><span>Motion</span><span>Muscle</span><span>Posture</span><span>Daily</span></div><button type="button" data-kk-open>Ouvrir Key →</button></div>`)}bindGlobalOpen()
}
function scheduleHome(){clearTimeout(homeTimer);homeTimer=setTimeout(patchHome,180)}
function bindGlobalOpen(){document.querySelectorAll('[data-kk-open]').forEach(b=>{if(b.dataset.kkBound)return;b.dataset.kkBound='1';b.addEventListener('click',()=>location.hash=ROUTE)})}

function openImport(data){
  document.querySelector('#kkImportModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="kk-modal" id="kkImportModal" role="dialog" aria-modal="true" aria-label="Importer dans KŌMØ Key"><div class="kk-modal-panel"><div class="kk-modal-head"><div><p class="kk-kicker">KŌMØ KEY · INGEST</p><h3>Importer une source</h3></div><button class="kk-close" type="button" id="kkImportClose" aria-label="Fermer">×</button></div><div class="kk-modal-body"><div class="kk-import-grid"><button class="kk-import-choice active" type="button" data-kk-source="wearable"><strong>Wearable / activité</strong><span>CSV, Excel ou JSON. Pas, activité, sommeil, fréquence cardiaque, HRV, SpO₂.</span></button><button class="kk-import-choice" type="button" data-kk-source="myocare"><strong>MyoCare / MyoDev</strong><span>Import instrumenté normalisé dans KŌMØ Motion avec contrôle qualité.</span></button><button class="kk-import-choice" type="button" data-kk-source="clinical"><strong>Biologie / imagerie</strong><span>Données reçues dans le flux Clinical, avec validation et provenance.</span></button></div><div class="kk-import-stage" id="kkImportStage"></div></div></div></div>`);
  const modal=document.querySelector('#kkImportModal');document.querySelector('#kkImportClose')?.addEventListener('click',()=>modal?.remove());modal?.addEventListener('click',e=>{if(e.target===modal)modal.remove()});document.querySelectorAll('[data-kk-source]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-kk-source]').forEach(x=>x.classList.toggle('active',x===b));renderImportStage(b.dataset.kkSource,data)}));renderImportStage('wearable',data)
}
function renderImportStage(type,data){const stage=document.querySelector('#kkImportStage');if(!stage)return;importState={rows:[],fileName:'',format:''};if(type==='wearable'){stage.innerHTML=`<div class="kk-drop"><strong>Déposez un export de suivi quotidien</strong><span>.csv · .xlsx · .xls · .json — les colonnes reconnues sont normalisées avant import.</span><input id="kkFile" type="file" accept=".csv,.xlsx,.xls,.json"></div><div id="kkPreview"></div><div class="kk-import-status" id="kkImportStatus">Colonnes reconnues : date, pas, distance, temps actif/sédentaire, fréquence cardiaque, HRV, SpO₂ et sommeil.</div>`;document.querySelector('#kkFile')?.addEventListener('change',e=>parseImportFile(e.target.files?.[0]))}else if(type==='myocare'){const pro=['professional','admin'].includes(data.role);stage.innerHTML=`<div class="kk-governance"><strong>MyoCare reste un flux instrumenté.</strong><br>L’export est normalisé vers le contrat canonique KŌMØ, avec conservation de l’ID de session, de la version source, des unités, du QC et de la provenance. ${pro?'Vous pouvez poursuivre dans Clinical sur l’évaluation du patient.':'Cet import est réalisé par le professionnel pendant le bilan KŌMØ.'}</div><div style="margin-top:12px"><button class="kk-btn dark" type="button" id="kkMyoCareGo">${pro?'Ouvrir l’import Clinical →':'Voir mon parcours →'}</button></div>`;document.querySelector('#kkMyoCareGo')?.addEventListener('click',()=>{document.querySelector('#kkImportModal')?.remove();location.hash=pro?'clinical':'path'})}else{const pro=['professional','admin'].includes(data.role);stage.innerHTML=`<div class="kk-governance"><strong>Biologie et imagerie : couche Clinical.</strong><br>Les valeurs interprétables ne sont pas injectées comme de simples données personnelles : elles sont rattachées à une évaluation, à une source et à un statut de validation. Dès qu’elles sont disponibles dans le dossier, Key les présente automatiquement. ${pro?'Le flux professionnel permet la saisie et la validation.':'Vos documents et résultats validés apparaîtront ici sans action supplémentaire.'}</div><div style="margin-top:12px"><button class="kk-btn dark" type="button" id="kkClinicalGo">${pro?'Ouvrir Clinical →':'Voir mes documents →'}</button></div>`;document.querySelector('#kkClinicalGo')?.addEventListener('click',()=>{document.querySelector('#kkImportModal')?.remove();location.hash=pro?'clinical':'documents'})}}

function csvRows(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const split=line=>{const out=[];let q=false,c='';for(let i=0;i<line.length;i++){const ch=line[i],nx=line[i+1];if(ch==='"'){if(q&&nx==='"'){c+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(c);c=''}else c+=ch}out.push(c);return out};const head=split(lines[0]);return lines.slice(1).map(line=>{const vals=split(line),o={};head.forEach((h,i)=>o[h]=vals[i]??'');return o})}
function canonicalDate(v){if(v instanceof Date&&!Number.isNaN(v.getTime()))return dayKey(v);const s=String(v??'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const fr=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);if(fr)return`${fr[3]}-${fr[2].padStart(2,'0')}-${fr[1].padStart(2,'0')}`;const d=new Date(s);return Number.isNaN(d.getTime())?null:dayKey(d)}
function pickFlat(o,aliases){const map=Object.fromEntries(Object.entries(o||{}).map(([k,v])=>[normKey(k),v]));for(const a of aliases){const v=map[normKey(a)];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return null}
function nval(v){if(v===null||v===undefined||String(v).trim()==='')return null;const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:null}
function normalizeWearable(raw){const date=canonicalDate(pickFlat(raw,['date','metric_date','day','jour','start_date','calendar_date']));if(!date)return null;return{date,steps:nval(pickFlat(raw,['steps','step_count','pas','nombre_de_pas'])),distance_m:nval(pickFlat(raw,['distance_m','distance','distance_meters','distance_metres'])),active_minutes:nval(pickFlat(raw,['active_minutes','activity_minutes','minutes_active','temps_actif','move_minutes'])),sedentary_minutes:nval(pickFlat(raw,['sedentary_minutes','minutes_sedentary','temps_sedentaire'])),avg_hr:nval(pickFlat(raw,['avg_hr','average_hr','heart_rate_avg','fc_moyenne'])),resting_hr:nval(pickFlat(raw,['resting_hr','rhr','resting_heart_rate','fc_repos'])),hrv_ms:nval(pickFlat(raw,['hrv_ms','hrv','rmssd','vfc_ms'])),spo2_avg:nval(pickFlat(raw,['spo2_avg','spo2','oxygen_saturation','saturation_o2'])),sleep_minutes:nval(pickFlat(raw,['sleep_minutes','sleep_duration_minutes','sommeil_minutes'])),deep_sleep_minutes:nval(pickFlat(raw,['deep_sleep_minutes','deep_sleep','sommeil_profond_minutes'])),rem_sleep_minutes:nval(pickFlat(raw,['rem_sleep_minutes','rem_sleep','sommeil_paradoxal_minutes'])),wear_minutes:nval(pickFlat(raw,['wear_minutes','device_wear_minutes','port_minutes']))}}
async function parseImportFile(file){
  const status=document.querySelector('#kkImportStatus'),preview=document.querySelector('#kkPreview');if(!file)return;try{if(status)status.textContent='Lecture et normalisation…';const ext=(file.name.split('.').pop()||'').toLowerCase(),buf=await file.arrayBuffer();let raw=[];if(ext==='json'){const j=JSON.parse(new TextDecoder().decode(buf));raw=Array.isArray(j)?j:Array.isArray(j.data)?j.data:Array.isArray(j.rows)?j.rows:[j]}else if(ext==='csv')raw=csvRows(new TextDecoder().decode(buf));else if(['xlsx','xls'].includes(ext)){const XLSX=await import('https://esm.sh/xlsx@0.18.5');const wb=XLSX.read(buf,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];raw=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true})}else throw new Error('Format non supporté.');const rows=raw.map(normalizeWearable).filter(Boolean).filter(r=>WEARABLE_FIELDS.some(k=>r[k]!=null));if(!rows.length)throw new Error('Aucune ligne quotidienne reconnue. Vérifiez la colonne de date et les métriques.');importState={rows,fileName:file.name,format:ext};if(preview)preview.innerHTML=previewImport(rows);if(status)status.textContent=`${rows.length} jour(s) détecté(s). Vérifiez l’aperçu avant import.`;document.querySelector('#kkImportConfirm')?.addEventListener('click',()=>commitWearableImport())}catch(e){if(preview)preview.innerHTML='';if(status)status.textContent=e.message||'Lecture impossible.'}}
function previewImport(rows){return`<div class="kk-preview"><table><thead><tr><th>Date</th><th>Pas</th><th>Actif</th><th>FC repos</th><th>HRV</th><th>Sommeil</th></tr></thead><tbody>${rows.slice(0,6).map(r=>`<tr><td>${r.date}</td><td>${fmtInt(r.steps)}</td><td>${fmtInt(r.active_minutes)}</td><td>${fmtInt(r.resting_hr)}</td><td>${fmtInt(r.hrv_ms)}</td><td>${r.sleep_minutes==null?'—':`${(r.sleep_minutes/60).toFixed(1)} h`}</td></tr>`).join('')}</tbody></table></div><div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="kk-btn dark" type="button" id="kkImportConfirm">Importer ${rows.length} jour(s) dans Key</button></div>`}
async function commitWearableImport(){
  const button=document.querySelector('#kkImportConfirm'),status=document.querySelector('#kkImportStatus');if(!importState.rows.length)return;button&&(button.disabled=true);try{if(status)status.textContent='Import sécurisé en cours…';const c=sb(),session=(await c.auth.getSession()).data?.session;if(!session?.user)throw new Error('Session Pulse introuvable.');let device=(cache?.devices||[]).find(x=>x.status==='active')||(cache?.devices||[])[0];if(!device){const ins=await c.from('wearable_devices').insert({user_id:session.user.id,provider:'manual',display_name:'KŌMØ Key · import',model:'Imported daily data',source_adapter:'komo_key_import',paired_at:new Date().toISOString(),metadata:{created_by:'komo-key-v1'}}).select().single();if(ins.error)throw ins.error;device=ins.data}const now=new Date().toISOString(),payload=importState.rows.map(r=>({user_id:session.user.id,device_id:device.id,metric_date:r.date,steps:r.steps,distance_m:r.distance_m,active_minutes:r.active_minutes,sedentary_minutes:r.sedentary_minutes,avg_hr:r.avg_hr,resting_hr:r.resting_hr,hrv_ms:r.hrv_ms,spo2_avg:r.spo2_avg,sleep_minutes:r.sleep_minutes,deep_sleep_minutes:r.deep_sleep_minutes,rem_sleep_minutes:r.rem_sleep_minutes,wear_minutes:r.wear_minutes,source:'manual_import',source_quality:'manual',raw_payload:{file_name:importState.fileName,format:importState.format,adapter:'komo-key-v1',imported_at:now}}));const res=await c.from('wearable_daily_metrics').upsert(payload,{onConflict:'user_id,device_id,metric_date,source'});if(res.error)throw res.error;await c.from('wearable_devices').update({last_sync_at:now}).eq('id',device.id);if(status)status.textContent=`${payload.length} jour(s) intégrés à KŌMØ Key.`;cache=null;cacheAt=0;setTimeout(()=>{document.querySelector('#kkImportModal')?.remove();schedule(true)},700)}catch(e){if(status)status.textContent=e.message||'Import impossible.';button&&(button.disabled=false)}}

function onHash(){if(route()===LEGACY_ROUTE){location.hash=ROUTE;return}ensureNav();if(route()===ROUTE)schedule(false);if(route()==='home')scheduleHome()}
function interceptLegacy(e){const target=e.target.closest?.('[data-route="followup"],[data-kw-open]');if(!target)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();location.hash=ROUTE}
function observe(){const root=document.querySelector('#viewRoot'),desktop=document.querySelector('#desktopNav'),mobile=document.querySelector('#mobileNav');const obs=new MutationObserver(()=>{ensureNav();if(route()===ROUTE&&!document.querySelector('.kk-shell'))schedule(false);if(route()==='home')scheduleHome()});[root,desktop,mobile].filter(Boolean).forEach(x=>obs.observe(x,{childList:true,subtree:true}))}

ensureStyle();document.addEventListener('click',interceptLegacy,true);window.addEventListener('hashchange',onHash);window.addEventListener('komo:route-ready',onHash);window.addEventListener('komo:session-ready',()=>{cache=null;cacheAt=0;onHash()});document.querySelector('#refreshButton')?.addEventListener('click',()=>{cache=null;cacheAt=0;if(route()===ROUTE)setTimeout(()=>schedule(true),150);if(route()==='home')setTimeout(scheduleHome,180)});document.addEventListener('DOMContentLoaded',()=>{ensureNav();observe();onHash()});setTimeout(()=>{ensureNav();observe();onHash()},900);if(document.readyState!=='loading'){ensureNav();setTimeout(()=>{observe();onHash()},80)}
window.KomoKey={version:VERSION,open:()=>{location.hash=ROUTE},refresh:()=>{cache=null;cacheAt=0;return render(true)}};
