import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const VERSION='3.0.0';
const URL='https://uqlolefsiktbznnymriy.supabase.co';
const KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REM='komo_pulse_remember';
const BASE=['KOMO_BASELINE_CORE','KOMO_MOBILITY_25','KOMO_SLEEP_RECOVERY','KOMO_WELLBEING','KOMO_LIFESTYLE','KOMO_HEALTH_HISTORY'];
const META={
  KOMO_BASELINE_CORE:{n:'01',icon:'◎',title:'Contexte & santé',short:'Votre point de départ',desc:'Douleur, stabilité, sécurité et contexte général.',time:'3 min',tone:'dark'},
  KOMO_MOBILITY_25:{n:'02',icon:'↗',title:'Mobilité',short:'Comment vous bougez',desc:'25 situations du quotidien pour situer votre mobilité.',time:'4 min',tone:'sage'},
  KOMO_SLEEP_RECOVERY:{n:'03',icon:'☾',title:'Sommeil & récupération',short:'Votre capacité à récupérer',desc:'Sommeil, fatigue et récupération ressentie.',time:'2 min',tone:'cream'},
  KOMO_WELLBEING:{n:'04',icon:'◌',title:'Bien-être',short:'Comment vous vous sentez',desc:'Énergie, confort et perception de votre état actuel.',time:'2 min',tone:'sand'},
  KOMO_LIFESTYLE:{n:'05',icon:'⌁',title:'Mode de vie',short:'Votre quotidien en mouvement',desc:'Activité, habitudes et environnement de vie.',time:'2 min',tone:'cream'},
  KOMO_HEALTH_HISTORY:{n:'06',icon:'＋',title:'Antécédents',short:'Votre histoire de santé',desc:'Éléments utiles pour contextualiser le bilan Motion.',time:'3 min',tone:'dark2'}
};
const S={client:null,user:null,patient:null,assessment:null,registry:{},sessions:{},responses:{},loading:false,openCode:null,message:'',kind:''};

const route=()=>location.hash.replace(/^#/,'')||'home';
const storage=()=>localStorage.getItem(REM)==='1'?localStorage:sessionStorage;
const sb=()=>S.client||(S.client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const num=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const key=(sid,item)=>`${sid}:${item}`;

function style(){if(document.querySelector('#kmotionHubV3Style'))return;const x=document.createElement('style');x.id='kmotionHubV3Style';x.textContent=`
body.kmotion-v3 .main-shell{background:radial-gradient(circle at 10% 0%,rgba(73,106,82,.055),transparent 28%),linear-gradient(180deg,#f8f5ed,#f1ede4)!important}.kmv3{--ink:#21352a;--deep:#142119;--forest:#243b2d;--sage:#dfe9df;--cream:#f8f5ed;--sand:#eadfce;--line:rgba(32,53,41,.10);display:grid;gap:16px;padding-bottom:24px;color:var(--ink)}.kmv3 *{box-sizing:border-box}.kmv3-card{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:25px;background:rgba(255,255,255,.84);box-shadow:0 20px 54px rgba(27,43,33,.065)}.kmv3-kicker{font-size:7px;font-weight:800;letter-spacing:.15em;text-transform:uppercase;color:#7b877f}.kmv3 h2,.kmv3 h3{margin:0;font-family:Manrope,sans-serif;letter-spacing:-.045em}.kmv3 h2{font-size:clamp(34px,4.3vw,58px);line-height:.96}.kmv3 h3{font-size:21px;line-height:1.05}.kmv3 p{color:#727d75}.kmv3-btn{border:1px solid rgba(32,53,41,.13);border-radius:13px;background:#fff;color:#26392e;padding:10px 13px;font:700 9px 'DM Sans',sans-serif;cursor:pointer}.kmv3-btn.primary{background:#20352a;color:#fff;border-color:#20352a}.kmv3-btn:disabled{opacity:.45;cursor:not-allowed}
.kmv3-hero{padding:25px;min-height:250px;color:#fff;background:radial-gradient(circle at 88% 12%,rgba(139,192,149,.17),transparent 27%),linear-gradient(135deg,#111d16,#1d3024 55%,#31523d)}.kmv3-hero:after{content:'';position:absolute;width:370px;height:370px;border-radius:50%;right:-100px;top:-190px;border:1px solid rgba(255,255,255,.075);box-shadow:0 0 0 46px rgba(255,255,255,.018),0 0 0 92px rgba(255,255,255,.012)}.kmv3-hero-grid{position:relative;z-index:2;display:grid;grid-template-columns:1.2fr .8fr;gap:25px;align-items:end}.kmv3-hero .kmv3-kicker{color:rgba(255,255,255,.53)}.kmv3-hero p{max-width:650px;margin:12px 0 0;color:rgba(255,255,255,.65);font-size:10px;line-height:1.55}.kmv3-hero-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.kmv3-hero .kmv3-btn.primary{background:#f5f1e7;color:#1f3529;border-color:#f5f1e7}.kmv3-hero .kmv3-btn:not(.primary){background:rgba(255,255,255,.07);color:#fff;border-color:rgba(255,255,255,.12)}.kmv3-progress-panel{padding:18px;border-radius:21px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.075);backdrop-filter:blur(9px)}.kmv3-progress-top{display:flex;align-items:flex-end;justify-content:space-between;gap:12px}.kmv3-progress-top strong{font:500 42px/1 Manrope,sans-serif}.kmv3-progress-top span{font-size:8px;color:rgba(255,255,255,.55)}.kmv3-track{height:11px;margin-top:12px;border-radius:999px;background:rgba(255,255,255,.10);overflow:hidden}.kmv3-track i{display:block;height:100%;width:var(--p);border-radius:inherit;background:linear-gradient(90deg,#f1e9d9,#b8d1b9);transition:width .45s ease}.kmv3-progress-foot{display:flex;justify-content:space-between;margin-top:8px;font-size:7px;color:rgba(255,255,255,.54)}
.kmv3-intro{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:3px 3px 0}.kmv3-intro h3{font-size:25px}.kmv3-intro p{margin:7px 0 0;font-size:10px}.kmv3-intro span{font-size:8px;color:#7d8880}.kmv3-qgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.kmv3-qcard{min-height:225px;padding:18px;border:1px solid var(--line);border-radius:22px;background:#fff;display:flex;flex-direction:column;cursor:pointer;box-shadow:0 15px 42px rgba(28,43,33,.045);transition:transform .2s ease,box-shadow .2s ease,border-color .2s ease}.kmv3-qcard:hover{transform:translateY(-3px);box-shadow:0 22px 50px rgba(28,43,33,.085);border-color:rgba(70,104,79,.17)}.kmv3-qcard.dark,.kmv3-qcard.dark2{color:#f7f6f1;background:linear-gradient(145deg,#17261d,#294333);border-color:rgba(255,255,255,.055)}.kmv3-qcard.sage{background:linear-gradient(145deg,#dfe9df,#f6f8f3)}.kmv3-qcard.sand{background:linear-gradient(145deg,#e9ddca,#f7f0e5)}.kmv3-qcard-head{display:flex;justify-content:space-between;gap:10px}.kmv3-qicon{width:39px;height:39px;border-radius:13px;display:grid;place-items:center;background:rgba(40,67,49,.08);font-size:17px}.kmv3-qcard.dark .kmv3-qicon,.kmv3-qcard.dark2 .kmv3-qicon{background:rgba(255,255,255,.08)}.kmv3-qstatus{padding:6px 8px;border-radius:999px;background:rgba(40,67,49,.07);font-size:7px;font-weight:800;white-space:nowrap}.kmv3-qcard.dark .kmv3-qstatus,.kmv3-qcard.dark2 .kmv3-qstatus{background:rgba(255,255,255,.08);color:#edf2eb}.kmv3-qcopy{margin-top:18px}.kmv3-qcopy small{display:block;font-size:7px;letter-spacing:.1em;text-transform:uppercase;color:#7d8880}.kmv3-qcard.dark .kmv3-qcopy small,.kmv3-qcard.dark2 .kmv3-qcopy small{color:rgba(255,255,255,.48)}.kmv3-qcopy strong{display:block;margin-top:6px;font:600 19px/1.05 Manrope,sans-serif;letter-spacing:-.035em}.kmv3-qcopy p{margin:7px 0 0;font-size:8.5px;line-height:1.45}.kmv3-qcard.dark p,.kmv3-qcard.dark2 p{color:rgba(255,255,255,.56)}.kmv3-qfoot{margin-top:auto;padding-top:18px}.kmv3-mini-track{height:6px;border-radius:999px;background:rgba(39,63,48,.10);overflow:hidden}.kmv3-qcard.dark .kmv3-mini-track,.kmv3-qcard.dark2 .kmv3-mini-track{background:rgba(255,255,255,.10)}.kmv3-mini-track i{display:block;height:100%;width:var(--p);border-radius:inherit;background:#466850}.kmv3-qcard.dark .kmv3-mini-track i,.kmv3-qcard.dark2 .kmv3-mini-track i{background:#c8ddc7}.kmv3-qmeta{display:flex;justify-content:space-between;margin-top:8px;font-size:7px;color:#818b84}.kmv3-qcard.dark .kmv3-qmeta,.kmv3-qcard.dark2 .kmv3-qmeta{color:rgba(255,255,255,.48)}
.kmv3-safety{padding:15px 17px;border-radius:18px;background:#f0dfda;border:1px solid rgba(126,72,63,.10);color:#71483f;font-size:9px;line-height:1.45}.kmv3-onsite{padding:21px;background:linear-gradient(145deg,#efe7da,#fbf8f2)}.kmv3-onsite-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.kmv3-onsite-head p{margin:6px 0 0;font-size:9px;line-height:1.5}.kmv3-onsite-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:15px}.kmv3-onsite-item{padding:14px;border-radius:17px;background:rgba(255,255,255,.72);border:1px solid rgba(43,60,48,.06)}.kmv3-onsite-item i{display:grid;place-items:center;width:34px;height:34px;border-radius:12px;background:#e1e9df;font-style:normal}.kmv3-onsite-item strong{display:block;margin-top:10px;font-size:10px}.kmv3-onsite-item span{display:block;margin-top:4px;font-size:7.5px;line-height:1.35;color:#7c867e}
.kmv3-overlay{position:fixed;z-index:260;inset:0;background:rgba(18,27,21,.42);backdrop-filter:blur(7px);display:grid;place-items:center;padding:20px}.kmv3-modal{width:min(980px,96vw);height:min(780px,92vh);border-radius:27px;background:#fbfaf7;box-shadow:0 35px 110px rgba(16,27,20,.28);overflow:hidden;display:grid;grid-template-columns:250px 1fr}.kmv3-modal-side{padding:20px;color:#fff;background:linear-gradient(155deg,#16251c,#294435);display:flex;flex-direction:column}.kmv3-modal-side .kmv3-kicker{color:rgba(255,255,255,.5)}.kmv3-modal-side h3{margin-top:7px;font-size:25px}.kmv3-modal-side p{font-size:8.5px;line-height:1.5;color:rgba(255,255,255,.55)}.kmv3-chapter-list{display:grid;gap:6px;margin-top:20px}.kmv3-chapter-list button{border:0;border-radius:13px;background:rgba(255,255,255,.055);color:rgba(255,255,255,.64);padding:10px;text-align:left;font:inherit;cursor:pointer;display:grid;grid-template-columns:28px 1fr auto;align-items:center;gap:8px}.kmv3-chapter-list button.active{background:#f2eee4;color:#203329}.kmv3-chapter-list button.done:not(.active){color:#d9ead9}.kmv3-chapter-list button i{font-style:normal;font-size:8px}.kmv3-chapter-list button strong{font-size:8.5px}.kmv3-chapter-list button span{font-size:7px}.kmv3-modal-side-foot{margin-top:auto}.kmv3-modal-side-foot .kmv3-track{height:7px}.kmv3-modal-side-foot span{display:block;margin-top:7px;font-size:7px;color:rgba(255,255,255,.5)}
.kmv3-modal-main{min-width:0;display:grid;grid-template-rows:auto 1fr auto}.kmv3-modal-top{padding:15px 18px;border-bottom:1px solid rgba(35,52,41,.08);display:flex;justify-content:space-between;align-items:center}.kmv3-modal-top span{font-size:8px;color:#78837b}.kmv3-close{width:35px;height:35px;border:1px solid #e2ded6;border-radius:50%;background:#fff;font-size:18px;cursor:pointer}.kmv3-modal-scroll{overflow:auto;padding:22px}.kmv3-form-head h3{margin-top:6px;font-size:28px}.kmv3-form-head p{margin:7px 0 0;font-size:9px;line-height:1.5}.kmv3-list{display:grid;gap:10px;margin-top:18px}.kmv3-q{padding:14px;border:1px solid rgba(35,52,41,.08);border-radius:17px;background:#fff}.kmv3-q>span{display:block;margin-bottom:10px;font-size:9px;font-weight:700;line-height:1.4}.kmv3-choice-grid,.kmv3-multi{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.kmv3-choice{position:relative}.kmv3-choice input{position:absolute;opacity:0;pointer-events:none}.kmv3-choice span{display:block;padding:10px 11px;border:1px solid #e2ded6;border-radius:12px;background:#faf8f3;font-size:8.5px;cursor:pointer}.kmv3-choice input:checked+span{border-color:#355541;background:#e5eee4;color:#284333;font-weight:800}.kmv3-q input[type=text],.kmv3-q input[type=number],.kmv3-q input[type=date],.kmv3-q textarea{width:100%;border:1px solid #dedbd3;border-radius:12px;background:#faf9f5;padding:10px;font:inherit;font-size:9px}.kmv3-q textarea{min-height:90px;resize:vertical}.kmv3-suffix{display:flex;align-items:center;gap:8px}.kmv3-suffix b{font-size:8px;color:#7f8881}.kmv3-modal-foot{padding:14px 18px;border-top:1px solid rgba(35,52,41,.08);display:flex;justify-content:space-between;align-items:center;gap:12px}.kmv3-feedback{font-size:8px;color:#6e7971}.kmv3-feedback.error{color:#915a4e}.kmv3-feedback.ok{color:#466b52}.kmv3-modal-actions{display:flex;gap:7px}
@media(max-width:960px){.kmv3-hero-grid{grid-template-columns:1fr}.kmv3-qgrid{grid-template-columns:repeat(2,1fr)}.kmv3-onsite-grid{grid-template-columns:1fr 1fr}.kmv3-modal{grid-template-columns:210px 1fr}}
@media(max-width:700px){.kmv3{gap:11px}.kmv3-card{border-radius:20px}.kmv3-hero{padding:19px}.kmv3-qgrid{grid-template-columns:1fr 1fr;gap:9px}.kmv3-qcard{min-height:205px;padding:14px}.kmv3-qcopy strong{font-size:16px}.kmv3-onsite-grid{grid-template-columns:1fr}.kmv3-modal{height:94vh;grid-template-columns:1fr;grid-template-rows:auto 1fr}.kmv3-modal-side{padding:12px 14px;display:block}.kmv3-modal-side>p,.kmv3-modal-side h3{display:none}.kmv3-chapter-list{display:flex;overflow:auto;margin-top:8px}.kmv3-chapter-list button{min-width:145px}.kmv3-modal-side-foot{display:none}.kmv3-modal-scroll{padding:16px}.kmv3-choice-grid,.kmv3-multi{grid-template-columns:1fr}.kmv3-modal-foot{align-items:flex-start;flex-direction:column}.kmv3-modal-actions{width:100%}.kmv3-modal-actions .kmv3-btn{flex:1}}
@media(max-width:470px){.kmv3-qgrid{grid-template-columns:1fr}.kmv3-intro{display:block}.kmv3-intro span{display:block;margin-top:8px}}
@media(prefers-reduced-motion:reduce){.kmv3-qcard,.kmv3-track i{transition:none!important}}
`;document.head.appendChild(x)}

async function load(){if(S.loading)return;S.loading=true;try{const ses=await sb().auth.getSession();S.user=ses.data.session?.user||null;if(!S.user)throw new Error('Session Pulse expirée.');const p=await sb().from('patients').select('id,birth_date,first_name,last_name,organization_id').eq('patient_user_id',S.user.id).order('created_at',{ascending:false});if(p.error)throw p.error;const patients=p.data||[];S.patient=patients[0]||null;if(!patients.length){S.assessment=null;return render()}const a=await sb().from('assessments').select('id,patient_id,status,protocol_version,created_at,started_at,completed_at').in('patient_id',patients.map(x=>x.id)).eq('product_mode','motion').order('created_at',{ascending:false});if(a.error)throw a.error;S.assessment=a.data?.[0]||null;if(S.assessment)S.patient=patients.find(x=>x.id===S.assessment.patient_id)||S.patient;const r=await sb().from('instrument_registry').select('code,label,version,can_render,configuration').in('code',BASE).eq('can_render',true);if(r.error)throw r.error;S.registry={};(r.data||[]).forEach(x=>S.registry[x.code]=x);await loadQuestionnaires();render()}catch(e){console.error('[motion-hub-v3]',e);S.message=e.message||'Bilan Motion indisponible.';S.kind='error';render()}finally{S.loading=false;window.KomoMotionRouteGuard?.release?.()}}
async function loadQuestionnaires(){S.sessions={};S.responses={};if(!S.assessment)return;const q=await sb().from('questionnaire_sessions').select('*').eq('assessment_id',S.assessment.id).in('instrument_code',BASE);if(q.error)throw q.error;(q.data||[]).forEach(x=>S.sessions[x.instrument_code]=x);const ids=(q.data||[]).map(x=>x.id);if(!ids.length)return;const r=await sb().from('questionnaire_responses').select('*').in('questionnaire_session_id',ids);if(r.error)throw r.error;(r.data||[]).forEach(x=>S.responses[key(x.questionnaire_session_id,x.item_code)]=x)}
function progress(code){return clamp(Number(S.sessions[code]?.completeness||0))}
function overall(){return Math.round(BASE.reduce((sum,c)=>sum+progress(c),0)/BASE.length)}
function doneCount(){return BASE.filter(c=>progress(c)>=100).length}
function answer(code,item){const s=S.sessions[code];return s?S.responses[key(s.id,item)]?.raw_value:undefined}
function safety(){return['S01','S02','S03','S04','S05'].some(k=>answer('KOMO_BASELINE_CORE',k)===true)}
function nextCode(){return BASE.find(c=>progress(c)<100)||BASE[0]}

function render(){if(route()!=='motion')return;style();document.body.classList.add('kmotion-v3');const root=document.querySelector('#viewRoot');if(!root)return;const pe=document.querySelector('#pageEyebrow'),pt=document.querySelector('#pageTitle');if(pe)pe.textContent='KŌMØ PULSE · MOTION';if(pt)pt.textContent='Votre bilan, à votre rythme.';const ready=!!S.assessment,p=overall(),done=doneCount();root.innerHTML=`<section class="kmv3" data-motion-hub-v3>
<section class="kmv3-card kmv3-hero"><div class="kmv3-hero-grid"><div><div class="kmv3-kicker">KŌMØ MOTION · PRÉPARATION</div><h2>Un bilan clair.<br>Six chapitres.<br>Votre rythme.</h2><p>Ouvrez les questionnaires dans l’ordre que vous voulez. Chaque réponse est enregistrée dans votre dossier Motion et vous pourrez revenir la modifier avant le rendez-vous.</p><div class="kmv3-hero-actions"><button class="kmv3-btn primary" data-kmv3-open="${esc(nextCode())}" ${ready?'':'disabled'}>${p>0?'Continuer là où j’en suis':'Commencer mon pré-bilan'} →</button><button class="kmv3-btn" data-kmv3-route="documents">${ready?'Voir mon rendez-vous':'Réserver KŌMØ Motion'}</button></div></div><aside class="kmv3-progress-panel"><div class="kmv3-kicker" style="color:rgba(255,255,255,.48)">PRÉ-BILAN</div><div class="kmv3-progress-top"><strong>${p}%</strong><span>${done}/6 chapitres terminés</span></div><div class="kmv3-track" style="--p:${p}%"><i></i></div><div class="kmv3-progress-foot"><span>Vous pouvez faire une pause à tout moment</span><span>${p>=100?'Prêt pour le bilan':'En cours'}</span></div></aside></div></section>
${safety()?'<div class="kmv3-safety"><strong>Vérification avant les tests physiques.</strong> Une réponse de sécurité mérite d’être revue par un professionnel. Vous pouvez continuer vos questionnaires normalement.</div>':''}
<div class="kmv3-intro"><div><div class="kmv3-kicker">À FAIRE CHEZ VOUS</div><h3>Choisissez votre prochain chapitre.</h3><p>Aucun ordre imposé. Ouvrez, enregistrez, quittez et reprenez quand vous voulez.</p></div><span>${done===6?'Pré-bilan complet ✓':`${6-done} chapitre${6-done>1?'s':''} restant${6-done>1?'s':''}`}</span></div>
<section class="kmv3-qgrid">${BASE.map(c=>questionCard(c,ready)).join('')}</section>
<section class="kmv3-card kmv3-onsite"><div class="kmv3-onsite-head"><div><div class="kmv3-kicker">ENSUITE, AU CENTRE</div><h3>La mesure complète votre préparation.</h3><p>Les questionnaires contextualisent le bilan. Les tests et MyoCare apportent ensuite les mesures fonctionnelles et instrumentées nécessaires au Motion Score.</p></div><button class="kmv3-btn primary" data-kmv3-route="documents">Voir mon rendez-vous →</button></div><div class="kmv3-onsite-grid"><article class="kmv3-onsite-item"><i>↗</i><strong>Tests fonctionnels</strong><span>Two-Step, Chair Stand, vitesse de marche, équilibre et autres tests adaptés au protocole.</span></article><article class="kmv3-onsite-item"><i>│</i><strong>Posture</strong><span>Mesure SVA et contexte postural, avec interprétation adaptée à la méthode utilisée.</span></article><article class="kmv3-onsite-item"><i>◫</i><strong>Acquisition MyoCare</strong><span>Activation musculaire, symétrie et données de marche issues des capteurs Myodev.</span></article></div></section>
</section>`;bindRoot();window.KomoMotionRouteGuard?.release?.();if(S.openCode)openModal(S.openCode)}
function questionCard(code,ready){const m=META[code],pct=progress(code),status=pct>=100?'Terminé':pct>0?'À reprendre':'À commencer';return `<button type="button" class="kmv3-qcard ${m.tone}" data-kmv3-open="${code}" ${ready?'':'disabled'}><div class="kmv3-qcard-head"><span class="kmv3-qicon">${m.icon}</span><span class="kmv3-qstatus">${status}</span></div><div class="kmv3-qcopy"><small>CHAPITRE ${m.n} · ${m.time}</small><strong>${m.title}</strong><p>${m.desc}</p></div><div class="kmv3-qfoot"><div class="kmv3-mini-track" style="--p:${pct}%"><i></i></div><div class="kmv3-qmeta"><span>${pct}% complété</span><span>${pct>=100?'Relire →':pct>0?'Reprendre →':'Ouvrir →'}</span></div></div></button>`}
function bindRoot(){document.querySelectorAll('[data-kmv3-open]').forEach(b=>b.addEventListener('click',()=>{if(!S.assessment)return;openModal(b.dataset.kmv3Open)}));document.querySelectorAll('[data-kmv3-route]').forEach(b=>b.addEventListener('click',()=>location.hash=b.dataset.kmv3Route))}

function cfg(code){return S.registry[code]?.configuration||{}}
function required(code){const c=cfg(code),items=c.items||{};return(c.item_order||Object.keys(items)).filter(k=>items[k]?.required!==false)}
function options(code,item){const c=cfg(code),it=c.items?.[item]||{};return it.options||(['scale'].includes(it.type)?c.response_scale:null)||(['frequency'].includes(it.type)?c.frequency_options:null)||(['difficulty'].includes(it.type)?c.difficulty_options:null)||(['impact'].includes(it.type)?c.impact_options:null)||(['tri_state'].includes(it.type)?c.default_options:null)||[]}
function same(a,b){if(typeof a==='boolean')return String(a)===String(b)||((a===true&&b==='yes')||(a===false&&b==='no'));return String(a??'')===String(b??'')}
function visible(code,item,answers){if(code==='KOMO_BASELINE_CORE'&&item==='B04_INJURY')return answers.B04_COUNT&&answers.B04_COUNT!=='none';if(code==='KOMO_BASELINE_CORE'&&['B08_DATE','B08_DETAIL'].includes(item))return answers.B08===true||answers.B08==='yes';if(code==='KOMO_SLEEP_RECOVERY'&&item==='SR10_REASON')return answers.SR10===false||answers.SR10==='no';return true}
function answers(code){const out={},c=cfg(code),s=S.sessions[code];if(!s)return out;(c.item_order||Object.keys(c.items||{})).forEach(i=>{const r=S.responses[key(s.id,i)];if(r)out[i]=r.raw_value});return out}
function choice(code,item,current,multi=false){const o=options(code,item);if(multi){const arr=Array.isArray(current)?current:[];return `<div class="kmv3-multi">${o.map(x=>`<label class="kmv3-choice"><input type="checkbox" name="${item}" value="${esc(x.value)}" ${arr.map(String).includes(String(x.value))?'checked':''}><span>${esc(x.label)}</span></label>`).join('')}</div>`}return `<div class="kmv3-choice-grid">${o.map(x=>`<label class="kmv3-choice"><input type="radio" name="${item}" value="${esc(x.value)}" ${same(current,x.value)?'checked':''}><span>${esc(x.label)}</span></label>`).join('')}</div>`}
function control(code,item,it,current){if(it.type==='yes_no')return `<div class="kmv3-choice-grid"><label class="kmv3-choice"><input type="radio" name="${item}" value="yes" ${current===true?'checked':''}><span>Oui</span></label><label class="kmv3-choice"><input type="radio" name="${item}" value="no" ${current===false?'checked':''}><span>Non</span></label></div>`;if(['choice','scale','frequency','difficulty','impact','tri_state'].includes(it.type))return choice(code,item,current,false);if(it.type==='multi_choice')return choice(code,item,current,true);if(it.type==='number')return `<div class="kmv3-suffix"><input type="number" name="${item}" min="${it.min??''}" max="${it.max??''}" step="${it.step??'any'}" value="${current??''}"><b>${esc(it.suffix||'')}</b></div>`;if(it.type==='date')return `<input type="date" name="${item}" value="${esc(current||'')}">`;if(it.type==='text')return `<textarea name="${item}" placeholder="Votre réponse">${esc(current||'')}</textarea>`;return `<input type="text" name="${item}" value="${esc(current||'')}">`}
function formHtml(code){const r=S.registry[code],c=cfg(code),a=answers(code),order=c.item_order||Object.keys(c.items||{}),m=META[code];return `<div class="kmv3-form-head"><div class="kmv3-kicker">CHAPITRE ${m.n}</div><h3>${esc(c.display_label||r?.label||m.title)}</h3><p>${esc(c.intro||m.desc)}</p></div><form id="kmv3Form" class="kmv3-list">${order.map(item=>{const it=c.items?.[item]||{};return `<label class="kmv3-q" data-kmv3-item="${item}" style="${visible(code,item,a)?'':'display:none'}"><span>${esc(it.prompt||item)}${it.required!==false?' *':''}</span>${control(code,item,it,a[item])}</label>`}).join('')}</form>`}
function chapterNav(){return BASE.map(c=>{const m=META[c],pct=progress(c);return `<button type="button" data-kmv3-chapter="${c}" class="${c===S.openCode?'active':''} ${pct>=100?'done':''}"><i>${pct>=100?'✓':m.n}</i><strong>${m.title}</strong><span>${pct?`${pct}%`:''}</span></button>`}).join('')}
function modalHtml(code){const p=overall();return `<div class="kmv3-overlay" data-kmv3-overlay><section class="kmv3-modal"><aside class="kmv3-modal-side"><div class="kmv3-kicker">KŌMØ MOTION</div><h3>Pré-bilan.</h3><p>Chaque chapitre est indépendant. Vos réponses sont enregistrées dans le même dossier Motion.</p><div class="kmv3-chapter-list">${chapterNav()}</div><div class="kmv3-modal-side-foot"><div class="kmv3-track" style="--p:${p}%"><i></i></div><span>${p}% du pré-bilan complété</span></div></aside><main class="kmv3-modal-main"><header class="kmv3-modal-top"><span>Vous pouvez enregistrer un brouillon et revenir plus tard.</span><button type="button" class="kmv3-close" data-kmv3-close>×</button></header><div class="kmv3-modal-scroll">${formHtml(code)}</div><footer class="kmv3-modal-foot"><div id="kmv3Feedback" class="kmv3-feedback ${S.kind}">${esc(S.message)}</div><div class="kmv3-modal-actions"><button class="kmv3-btn" data-kmv3-draft>Enregistrer</button><button class="kmv3-btn primary" data-kmv3-finish>Enregistrer & terminer</button></div></footer></main></section></div>`}
function openModal(code){if(!BASE.includes(code)||!S.registry[code])return;S.openCode=code;S.message='';S.kind='';document.querySelector('[data-kmv3-overlay]')?.remove();const t=document.createElement('div');t.innerHTML=modalHtml(code);document.body.appendChild(t.firstElementChild);bindModal();refreshVisibility()}
function closeModal(){S.openCode=null;document.querySelector('[data-kmv3-overlay]')?.remove();render()}
function live(code,item,it){const f=document.querySelector('#kmv3Form');if(!f)return undefined;if(it.type==='multi_choice')return [...f.querySelectorAll(`[name="${item}"]:checked`)].map(x=>x.value);if(['choice','scale','frequency','difficulty','impact','tri_state','yes_no'].includes(it.type)){const x=f.querySelector(`[name="${item}"]:checked`);if(!x)return undefined;if(it.type==='yes_no')return x.value==='yes';if(['scale','frequency','difficulty','impact'].includes(it.type)&&!Number.isNaN(Number(x.value)))return Number(x.value);return x.value}const x=f.elements[item];if(!x)return undefined;if(it.type==='number')return x.value===''?undefined:Number(x.value);return x.value===''?undefined:x.value}
function collect(code){const c=cfg(code),out={...answers(code)};Object.entries(c.items||{}).forEach(([item,it])=>{const v=live(code,item,it);if(v!==undefined)out[item]=v});return out}
function refreshVisibility(){const code=S.openCode,f=document.querySelector('#kmv3Form');if(!code||!f)return;const a=collect(code),c=cfg(code);f.querySelectorAll('[data-kmv3-item]').forEach(el=>el.style.display=visible(code,el.dataset.kmv3Item,a)?'':'none')}
function bindModal(){document.querySelector('[data-kmv3-close]')?.addEventListener('click',closeModal);document.querySelectorAll('[data-kmv3-chapter]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.kmv3Chapter)));document.querySelector('#kmv3Form')?.addEventListener('change',refreshVisibility);document.querySelector('[data-kmv3-draft]')?.addEventListener('click',()=>save(false));document.querySelector('[data-kmv3-finish]')?.addEventListener('click',()=>save(true));document.querySelector('[data-kmv3-overlay]')?.addEventListener('click',e=>{if(e.target.matches('[data-kmv3-overlay]'))closeModal()})}
async function ensureSession(code){if(S.sessions[code])return S.sessions[code];const r=S.registry[code];if(!r||!S.assessment)throw new Error('Questionnaire indisponible.');const now=new Date().toISOString(),q=await sb().from('questionnaire_sessions').insert({assessment_id:S.assessment.id,instrument_code:code,instrument_version:r.version,status:'in_progress',score_status:'not_scored',completeness:0,started_at:now,created_by:S.user.id}).select().single();if(q.error){if(q.error.code==='23505'){await loadQuestionnaires();if(S.sessions[code])return S.sessions[code]}throw q.error}S.sessions[code]=q.data;return q.data}
async function save(finish){const code=S.openCode,c=cfg(code),form=document.querySelector('#kmv3Form');if(!code||!form)return;S.message='Enregistrement…';S.kind='';feedback();try{const sess=await ensureSession(code),a=collect(code),rows=[],missing=[],now=new Date().toISOString(),order=c.item_order||Object.keys(c.items||{});for(const item of order){const it=c.items?.[item]||{};if(!visible(code,item,a))continue;const raw=live(code,item,it);const answered=raw!==undefined&&raw!==null&&raw!==''&&(!Array.isArray(raw)||raw.length>0);if(it.required!==false&&!answered)missing.push(item);if(!answered)continue;rows.push({questionnaire_session_id:sess.id,item_code:item,response_code:typeof raw==='string'?raw:null,raw_value:raw,normalized_value:raw,source:'patient',clinician_verified:false,triggered_by:'MOTION_HUB_V3',completed_at:now,updated_at:now})}if(rows.length){const q=await sb().from('questionnaire_responses').upsert(rows,{onConflict:'questionnaire_session_id,item_code'});if(q.error)throw q.error}await loadQuestionnaires();const req=required(code),answered=req.filter(i=>{const v=answer(code,i);return v!==undefined&&v!==null&&v!==''&&(!Array.isArray(v)||v.length>0)}).length,pct=req.length?Math.round(100*answered/req.length):100,complete=pct>=100;let score=null,scoreStatus='not_scored';if(code==='KOMO_MOBILITY_25'&&complete){score=100-req.reduce((sum,i)=>sum+(num(answer(code,i))||0),0);scoreStatus='provisional'}const up=await sb().from('questionnaire_sessions').update({completeness:pct,status:complete?'completed':'in_progress',score,score_status:scoreStatus,completed_at:complete?now:null,updated_at:now}).eq('id',sess.id).select().single();if(up.error)throw up.error;S.sessions[code]=up.data;await loadQuestionnaires();window.dispatchEvent(new CustomEvent('komo:questionnaire-saved',{detail:{assessmentId:S.assessment.id,instrumentCode:code,completeness:pct}}));if(finish&&missing.length){S.message=`${missing.length} réponse${missing.length>1?'s':''} obligatoire${missing.length>1?'s':''} reste${missing.length>1?'nt':''} à compléter.`;S.kind='error';openModal(code);return}S.message=complete?'Chapitre terminé ✓':'Brouillon enregistré. Vous pourrez reprendre ici.';S.kind='ok';render();if(S.openCode)openModal(code)}catch(e){console.error('[motion-hub-v3:save]',e);S.message=e.message||'Enregistrement impossible.';S.kind='error';feedback()}}
function feedback(){const e=document.querySelector('#kmv3Feedback');if(e){e.textContent=S.message;e.className=`kmv3-feedback ${S.kind}`}}

function enter(force=false){if(route()!=='motion'){document.body.classList.remove('kmotion-v3');document.querySelector('[data-kmv3-overlay]')?.remove();return}render();setTimeout(()=>load(),force?0:30)}
window.addEventListener('hashchange',()=>enter(false));window.addEventListener('pageshow',()=>enter(false));window.addEventListener('komo:questionnaire-saved',()=>{if(route()==='motion')setTimeout(load,120)});document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>enter(false),550));setTimeout(()=>enter(false),1000);window.KomoMotionHubV3={version:VERSION,refresh:load};
