import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const URL='https://uqlolefsiktbznnymriy.supabase.co';
const KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REM='komo_pulse_remember';
const CONTRACT='myodev-contract-v0.3';
const PROTOCOL='motion-clinical-v0.6';
const ADAPTER='myodev-primary-7sessions-v0.6';
const state={assessmentId:null,parsed:null,busy:false};
let _client=null;

const MAP={EMG_MVC_REF_UV:['MVC_value','device_unit'],EMG_ACTIVATION_PCTMVC:['activation_pctMVC','%MVC'],EMG_ACTIVATION_RATE_PCT:['activation_rate_pct','%'],EMG_RMS_UV:['EMG_RMS_uV','microvolt'],EMG_LSI_PCT:['LSI_pct','%'],EMG_CCI_IC:['CCI_IC_pct','%'],EMG_CCI_CI:['CCI_CI_pct','%'],GAIT_CADENCE:['cadence_spm','steps/min'],GAIT_STEP_COUNT:['step_count','count'],GAIT_STANCE_TIME:['stance_time_s','s'],GAIT_SWING_TIME:['swing_time_s','s'],GAIT_STEP_TIME:['step_time_s','s'],GAIT_STEP_LENGTH:['step_length_m','m'],GAIT_DOUBLE_SUPPORT_PCT:['double_support_pct','%'],GAIT_STANCE_SYMMETRY_PCT:['gait_stance_symmetry_pct','%'],GAIT_STEP_LENGTH_SYMMETRY_PCT:['gait_step_length_symmetry_pct','%'],GAIT_SPEED:['gait_speed_m_s','m/s']};
const BILATERAL=new Set(['LSI_pct','asymmetry_pct']);
const GAIT_GLOBAL=new Set(['cadence_spm','double_support_pct','gait_stance_symmetry_pct','gait_step_length_symmetry_pct','gait_speed_m_s']);

function storage(){return localStorage.getItem(REM)==='1'?localStorage:sessionStorage}
function sb(){return window.KomoRuntime?.client||(_client||(_client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})))}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function h(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function num(v){if(v===null||v===undefined||v==='')return null;const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:null}
function iso(v){if(!v)return null;if(typeof v==='number'&&v>30000&&v<80000)return new Date(Math.round((v-25569)*86400*1000)).toISOString();const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function side(v){const x=h(v);if(['L','LEFT','GAUCHE','G'].includes(x))return'LEFT';if(['R','RIGHT','DROITE','D'].includes(x))return'RIGHT';if(['BILATERAL','BILAT'].includes(x))return'BILATERAL';return'NA'}
function muscle(v){const x=h(v);if(['VL','VM'].includes(x)||x.includes('VASTUS')||x.includes('QUADRICEPS'))return'VL';if(x==='BF'||x.includes('BICEPS_FEM')||x.includes('HAMSTRING')||x.includes('ISCHIO'))return'BF';if(x==='GM'||x.includes('GASTRO')||x.includes('CALF')||x.includes('MOLLET'))return'GM';return'NA'}
function qc(v){const x=h(v);if(['VALID','OK','GOOD','PASS','PASSED'].includes(x))return'VALID';if(['SUSPECT','WARNING','WARN','PARTIAL'].includes(x))return'SUSPECT';if(['INVALID','FAIL','FAILED','BAD','ARTIFACT'].includes(x))return'INVALID';return'MISSING'}
async function sha256(input){const b=input instanceof ArrayBuffer?input:new TextEncoder().encode(String(input));const d=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function flat(row){const out={};for(const[k,v]of Object.entries(row||{}))out[h(k)]=v;return out}
function csv(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'){if(quote&&next==='"'){cell+='"';i++}else quote=!quote}else if((c===','||c===';'||c==='\t')&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&next==='\n')i++;row.push(cell);cell='';if(row.some(x=>String(x).trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);if(rows.length<2)return[];const head=rows[0].map(String);return rows.slice(1).map(r=>Object.fromEntries(head.map((x,i)=>[x,r[i]??null])))}
function unitFromSource(r,fallback=''){const u=String(r.UNIT||r.METRIC_UNIT||fallback||'').trim();if(/^percent$/i.test(u))return'%';if(/^microvolt$/i.test(u))return'microvolt';return u||fallback||'unit'}
function sourceMetric(code,r){const x=h(code);if(MAP[x])return MAP[x];if(x.includes('CCI')&&x.endsWith('_IC'))return['CCI_IC_pct',unitFromSource(r,'%')];if(x.includes('CCI')&&x.endsWith('_CI'))return['CCI_CI_pct',unitFromSource(r,'%')];if(x==='CCI'||x.includes('COACTIVATION'))return['CCI_pct',unitFromSource(r,'%')];if(x.includes('FATIGUE')||x.includes('DRIFT'))return['fatigue_drift_pct',unitFromSource(r,'%')];if(x.includes('ASYMMETRY')||x.includes('ASYMETRIE'))return['asymmetry_pct',unitFromSource(r,'%')];return[x.toLowerCase(),unitFromSource(r)]}
function canonicalTask(r){const x=h(r.PROTOCOL_TEST_CODE||r.TASK_CODE||r.TEST_CODE||r.TEST||r.EXERCISE||'SEANCE_COMPLETE');if(x.includes('MVC')||x.includes('CALIB'))return'MVC';if(x.includes('GAIT')||x.includes('WALK')||x.includes('MARCHE'))return'GAIT_4M';if(x.includes('HEEL')||x.includes('CALF_RAISE'))return'HEEL_RAISE_SENSOR';if(x.includes('SINGLE_LEG')||x.includes('UNIPOD'))return'SINGLE_LEG_SENSOR';if(x.includes('CHAIR')||x.includes('SIT_TO_STAND'))return'SIT_TO_STAND_SENSOR';if(x.startsWith('ACTIVATION_'))return'ACTIVATION_SENSOR';return x||'SEANCE_COMPLETE'}
function calibrationMap(raw){const out=new Map();for(const row of raw){const r=flat(row),metric=h(r.METRIC_CODE||r.METRIC||r.PARAMETER);if(metric!=='EMG_MVC_REF_UV')continue;const session=String(r.EXTERNAL_SESSION_ID||r.SESSION_ID||'session').trim(),mu=muscle(r.MUSCLE),sd=side(r.SIDE),version=String(r.SOURCE_VERSION||'source');out.set(`${session}|${mu}|${sd}`,`myodev:${session}:mvc:${mu}:${sd}:${version}`)}return out}

async function normalize(raw){const cals=calibrationMap(raw),rows=[],warnings=[],preserved=[];for(let i=0;i<raw.length;i++){const r=flat(raw[i]),sourceCode=h(r.METRIC_CODE||r.METRIC||r.PARAMETER);if(!sourceCode)continue;const value=num(r.VALUE??r.METRIC_VALUE??r.RESULT);if(value===null){warnings.push(['NON_NUMERIC',`Ligne ${i+2}: valeur non numérique pour ${sourceCode}.`]);continue}const mapped=sourceMetric(sourceCode,r),metricCode=mapped[0],session=String(r.EXTERNAL_SESSION_ID||r.SESSION_ID||'').trim(),version=String(r.SOURCE_VERSION||r.SOFTWARE_VERSION||'').trim(),mu=muscle(r.MUSCLE),rawSide=side(r.SIDE);let sd=BILATERAL.has(metricCode)?'BILATERAL':rawSide,muscleCode=mu;if(GAIT_GLOBAL.has(metricCode)){sd='NA';muscleCode='NA'}let calibrationId=null;if(metricCode==='MVC_value')calibrationId=cals.get(`${session}|${mu}|${rawSide}`)||null;else if(['activation_pctMVC','CCI_pct','CCI_IC_pct','CCI_CI_pct','fatigue_drift_pct'].includes(metricCode))calibrationId=cals.get(`${session}|${mu}|${rawSide}`)||cals.get(`${session}|${mu}|LEFT`)||cals.get(`${session}|${mu}|RIGHT`)||null;let q=qc(r.QC_STATUS||r.QUALITY_STATUS||r.QC),reason=String(r.REASON_CODE||'').trim()||null;if(metricCode==='activation_pctMVC'&&!calibrationId){q=q==='INVALID'?'INVALID':'SUSPECT';reason=reason||'CALIBRATION_NOT_EXPORTED'}if(!MAP[sourceCode]&&!sourceCode.includes('CCI')&&!sourceCode.includes('FATIGUE')&&!sourceCode.includes('DRIFT')&&!sourceCode.includes('ASYMMETR'))preserved.push(sourceCode);const taskCode=canonicalTask(r),recordedAt=iso(r.RECORDED_AT||r.TIMESTAMP||r.DATE)||new Date().toISOString(),canonical={externalSessionId:session||`SOURCE-${i+1}`,sourceVersion:version||'MyoLab',recordedAt,taskCode,trialIndex:num(r.TRIAL_INDEX),muscleCode,side:sd,phaseWindow:null,metricCode,value,unit:mapped[1],directionality:'descriptive',qcStatus:q,qcReason:reason,protocolVersion:PROTOCOL,calibrationId,referenceSetId:null};canonical.rowHash=await sha256([canonical.externalSessionId,taskCode,sourceCode,rawSide,mu,version,value,i].join('|'));rows.push(canonical)}if(preserved.length)warnings.push(['SOURCE_METRICS_PRESERVED',`${new Set(preserved).size} type(s) de métrique non scorée conservé(s) comme données descriptives.`]);if(!rows.some(r=>r.metricCode==='LSI_pct'))warnings.push(['LSI_MISSING','Aucun LSI fournisseur trouvé : le Motion Score restera indisponible.']);return{rows,warnings}}
function rowsFromSheet(XLSX,sheet){const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:null,raw:false}),headerIndex=matrix.findIndex(row=>{const hs=(row||[]).map(h);return hs.includes('EXTERNAL_SESSION_ID')&&hs.includes('METRIC_CODE')&&hs.includes('VALUE')});if(headerIndex<0)return[];const head=matrix[headerIndex].map(v=>String(v??''));return matrix.slice(headerIndex+1).filter(r=>(r||[]).some(v=>v!==null&&String(v).trim()!=='')).map(r=>Object.fromEntries(head.map((k,i)=>[k,r[i]??null])))}
async function parse(file){const ext=(file.name.split('.').pop()||'').toLowerCase(),buf=await file.arrayBuffer(),fileHash=await sha256(buf);let raw=[],sheetName=null;if(ext==='json'){const j=JSON.parse(new TextDecoder().decode(buf));raw=Array.isArray(j)?j:Array.isArray(j.rows)?j.rows:Array.isArray(j.data)?j.data:[j]}else if(ext==='csv')raw=csv(new TextDecoder().decode(buf));else if(['xlsx','xls'].includes(ext)){const XLSX=await import('https://esm.sh/xlsx@0.18.5'),wb=XLSX.read(buf,{type:'array',cellDates:true}),candidates=[...wb.SheetNames].sort((a,b)=>{const score=n=>h(n)==='04_MYODEV_IMPORT'?100:h(n).includes('MYODEV_IMPORT')?90:h(n)==='MEASUREMENTS'?80:h(n).includes('MEASUREMENT')?70:0;return score(b)-score(a)});for(const name of candidates){const candidate=rowsFromSheet(XLSX,wb.Sheets[name]);if(candidate.length){raw=candidate;sheetName=name;break}}}else throw new Error('Format non supporté.');if(!raw.length)throw new Error('Aucune table de mesures Myodev reconnue. Utilisez le fichier global contenant la feuille 04_MYODEV_IMPORT.');const normalized=await normalize(raw),first=flat(raw[0]),sessions=[...new Set(raw.map(x=>String(flat(x).EXTERNAL_SESSION_ID||'').trim()).filter(Boolean))],patient=String(first.PATIENT_PSEUDONYM||'').trim();return{fileName:file.name,fileSize:file.size,fileHash,format:['xlsx','xls'].includes(ext)?'xlsx':ext,sheetName,rawCount:raw.length,columns:[...new Set(raw.flatMap(r=>Object.keys(r)))],sessions,...normalized,meta:{external_session_id:patient?`${patient}-GLOBAL`:`KOMO-GLOBAL-${fileHash.slice(0,12)}`,source_version:String(first.SOURCE_VERSION||first.SOFTWARE_VERSION||'MyoLab'),recorded_at:iso(first.RECORDED_AT||first.TIMESTAMP)||new Date().toISOString()},adapter:ADAPTER}}

function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,4600)}
function preview(){const p=state.parsed;if(!p)return'';const lsi=p.rows.filter(r=>r.metricCode==='LSI_pct'&&r.qcStatus==='VALID'),muscles=[...new Set(lsi.map(r=>r.muscleCode).filter(x=>x&&x!=='NA'))];return`<div class="clm-import-summary"><span>${p.rows.length}/${p.rawCount} mesures reconnues</span><span>${p.sessions.length} sessions</span><span>${muscles.length}/3 groupes LSI</span></div><div class="clm-note"><strong>${esc(p.sheetName||'Données source')}</strong> · ${esc(p.fileName)}. Les ${p.rows.length} mesures restent traçables ; seules les métriques validées prévues par Motion v0.6 participent au score.</div>${p.warnings.length?`<div class="clm-warning-list">${p.warnings.slice(0,8).map(([,m])=>`<div class="clm-warning">${esc(m)}</div>`).join('')}</div>`:''}<div class="clm-preview"><table><thead><tr><th>Session</th><th>Contexte capteur</th><th>Muscle</th><th>Métrique</th><th>Valeur</th><th>QC</th></tr></thead><tbody>${p.rows.slice(0,12).map(r=>`<tr><td>${esc(r.externalSessionId)}</td><td>${esc(r.taskCode)}</td><td>${esc(r.muscleCode)}</td><td>${esc(r.metricCode)}</td><td>${esc(r.value)} ${esc(r.unit)}</td><td>${esc(r.qcStatus)}</td></tr>`).join('')}</tbody></table></div>`}
function mount(){const box=document.querySelector('#clmImporter');if(!box||!state.assessmentId)return;const p=state.parsed;box.innerHTML=`<div class="clm-import"><div class="clm-drop"><strong>Importer l’export global Myodev</strong><span>Le fichier multi-session est reconnu automatiquement. Pulse conserve chaque mesure, contrôle la qualité puis calcule le Motion Score capteur.</span><input id="clmFile" type="file" accept=".xlsx,.xls,.csv,.json"><div class="clm-file">${p?`${esc(p.fileName)} · ${p.rows.length} mesures prêtes`:'Sélectionner le fichier global Myodev'}</div></div>${p?preview():''}<div class="clm-actions"><button id="clmImportBtn" class="clm-btn primary" type="button" ${!p||state.busy?'disabled':''}>${state.busy?'Import en cours…':'Importer et calculer'}</button></div></div>`;box.querySelector('#clmFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{toast('Lecture de l’export Myodev…');state.parsed=await parse(f);mount();toast(`${state.parsed.rows.length} mesures reconnues dans ${state.parsed.sessions.length} sessions.`)}catch(err){console.error('[myodev-import parse]',err);state.parsed=null;mount();toast(`Import impossible : ${err.message||err}`)}});box.querySelector('#clmImportBtn')?.addEventListener('click',run)}
async function run(){if(state.busy||!state.parsed||!state.assessmentId)return;state.busy=true;mount();try{const p=state.parsed;if(!p.rows.length)throw new Error('Aucune métrique exploitable.');const manifest={adapter:p.adapter,sourceSchema:'myodev-komo-1.0',sourceSheet:p.sheetName,sourceSessionCount:p.sessions.length,sourceSessionIds:p.sessions,rawRowCount:p.rawCount,normalizedRowCount:p.rows.length,protocolVersion:PROTOCOL,scorePolicy:'sensor_only_v0.6',questionnaireContribution:0},args={target_assessment_id:state.assessmentId,target_contract_code:CONTRACT,target_external_session_id:p.meta.external_session_id,target_source_product:'myolab',target_source_version:p.meta.source_version||'MyoLab',target_source_format:p.format,target_source_file_name:p.fileName,target_import_hash:p.fileHash,target_payload_manifest:manifest,target_device_set_id:null,target_recorded_at:p.meta.recorded_at,metric_batch:p.rows,import_warnings:p.warnings.map(([code,message])=>({code,message}))},c=sb(),imp=await c.rpc('import_pulse_myodev_result',args);if(imp.error)throw imp.error;const sc=await c.rpc('calculate_motion_v06',{p_assessment_id:state.assessmentId});if(sc.error)throw sc.error;const value=sc.data?.motion_score;toast(value==null?`Import accepté · ${p.rows.length} mesures. Score en attente de données LSI complètes.`:`Import accepté · Motion Score ${Number(value).toFixed(1)}/100.`);state.parsed=null;window.dispatchEvent(new CustomEvent('komo:myocare-imported',{detail:{assessmentId:state.assessmentId,import:imp.data}}));window.dispatchEvent(new CustomEvent('komo:motion-v06-calculated',{detail:sc.data||{}}))}catch(err){console.error('[myodev-import]',err);toast(`Import bloqué : ${err.message||err}`)}finally{state.busy=false;mount()}}
function attach(id){if(!id)return;if(state.assessmentId!==id){state.assessmentId=id;state.parsed=null}setTimeout(mount,0)}
window.addEventListener('komo:clinical-motion-render',e=>attach(e.detail?.assessmentId));
document.addEventListener('change',e=>{if(e.target?.id==='clmAssessment')attach(e.target.value)});
window.addEventListener('komo:myocare-open',()=>document.querySelector('#clmFile')?.click());
window.addEventListener('hashchange',()=>{if(location.hash!=='#clinical'){state.parsed=null;state.assessmentId=null}});
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{const id=document.querySelector('#clmAssessment')?.value;if(id)attach(id)},900));
window.KomoMyoCareImport={version:'0.6.0',contract:CONTRACT,protocol:PROTOCOL,adapter:ADAPTER,parseFile:parse};
