import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const URL='https://uqlolefsiktbznnymriy.supabase.co';
const KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REM='komo_pulse_remember';
const CONTRACT='myodev-contract-v0.2';
const PROTOCOL='motion-clinical-v0.6';
const ADAPTER='myocare-primary-v0.6';
const state={assessmentId:null,userId:null,parsed:null,busy:false};
let _client=null;

const METRICS={
  EMG_MVC_REF_UV:['MVC_value','microvolt'],
  EMG_ACTIVATION_PCTMVC:['activation_pctMVC','%MVC'],
  EMG_ACTIVATION_RATE_PCT:['activation_rate_pct','%'],
  EMG_RMS_UV:['EMG_RMS_uV','microvolt'],
  EMG_LSI_PCT:['LSI_pct','%'],
  EMG_CCI_IC_PCT:['CCI_pct','%'],
  EMG_CCI_CI_PCT:['CCI_pct','%'],
  GAIT_CADENCE:['cadence_spm','steps/min'],
  GAIT_STEP_COUNT:['step_count','count'],
  GAIT_STANCE_TIME:['stance_time_s','s'],
  GAIT_SWING_TIME:['swing_time_s','s'],
  GAIT_STEP_TIME:['step_time_s','s'],
  GAIT_STEP_LENGTH:['step_length_m','m'],
  GAIT_DOUBLE_SUPPORT_PCT:['double_support_pct','%'],
  GAIT_STANCE_SYMMETRY_PCT:['gait_stance_symmetry_pct','%'],
  GAIT_STEP_LENGTH_SYMMETRY_PCT:['gait_step_length_symmetry_pct','%'],
  GAIT_SPEED:['gait_speed_m_s','m/s']
};
const FUNCTIONAL_TASKS=['HEEL_RAISE','GAIT_4X2M','SINGLE_LEG_STANCE','CHAIR_STAND_30S'];
const SESSION_TASK={
  'MYO-6415':'ACTIVATION_VM',
  'MYO-6417':'ACTIVATION_BF',
  'MYO-6420':'ACTIVATION_GM',
  'MYO-6431':'HEEL_RAISE',
  'MYO-6432':'GAIT_4X2M',
  'MYO-6437':'SINGLE_LEG_STANCE',
  'MYO-6438':'CHAIR_STAND_30S'
};

function storage(){return localStorage.getItem(REM)==='1'?localStorage:sessionStorage}
function sb(){return window.KomoRuntime?.client||(_client||(_client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})))}
function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
function h(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function num(v){if(v===null||v===undefined||v==='')return null;const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:null}
function iso(v){if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString();const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function side(v){const x=h(v);if(['L','LEFT','GAUCHE','G'].includes(x))return'LEFT';if(['R','RIGHT','DROITE','D'].includes(x))return'RIGHT';if(['BILATERAL','BILAT'].includes(x))return'BILATERAL';return'NA'}
function muscle(v){const x=h(v);if(x==='VM'||x.includes('VASTUS_MED')||x.includes('VASTE_MED'))return'VM';if(x==='VL'||x.includes('VASTUS_LAT')||x.includes('VASTE_LAT'))return'VL';if(x==='BF'||x.includes('BICEPS_FEM')||x.includes('HAMSTRING')||x.includes('ISCHIO'))return'BF';if(x==='GM'||x.includes('GASTRO')||x.includes('CALF'))return'GM';if(x==='UN'||x==='UNKNOWN')return'UN';return x||'NA'}
function qc(v){const x=h(v);if(['VALID','OK','GOOD','PASS','PASSED'].includes(x))return'VALID';if(['SUSPECT','WARNING','WARN','PARTIAL','REVIEW'].includes(x))return'SUSPECT';if(['INVALID','FAIL','FAILED','BAD','ARTIFACT'].includes(x))return'INVALID';return'MISSING'}
async function sha256(textOrBuffer){const b=textOrBuffer instanceof ArrayBuffer?textOrBuffer:new TextEncoder().encode(String(textOrBuffer));const d=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function csv(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='\"'){if(quote&&n==='\"'){cell+='\"';i++}else quote=!quote}else if((c===','||c===';'||c==='\t')&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>String(x).trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);if(rows.length<2)return[];const head=rows[0].map(String);return rows.slice(1).map(r=>Object.fromEntries(head.map((x,i)=>[x,r[i]??null])))}
function flat(row){const out={};for(const[k,v]of Object.entries(row||{}))out[h(k)]=v;return out}
function objectsFromSheet(XLSX,sheet){const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:null,raw:false});const hi=matrix.findIndex(r=>r.some(c=>h(c)==='EXTERNAL_SESSION_ID')&&r.some(c=>h(c)==='METRIC_CODE')&&r.some(c=>h(c)==='VALUE'));if(hi<0)return[];const head=matrix[hi].map(x=>String(x??''));return matrix.slice(hi+1).filter(r=>r.some(v=>v!==null&&String(v).trim()!=='')).map(r=>Object.fromEntries(head.map((x,i)=>[x,r[i]??null])))}
function resolveTask(r){const sourceTask=h(r.TASK_CODE||r.TEST_CODE||r.TEST||r.EXERCISE);const session=String(r.EXTERNAL_SESSION_ID||r.SESSION_ID||'').trim();if(sourceTask==='MVC_CALIB'||sourceTask==='MVC'||sourceTask.includes('CALIB'))return'MVC_CALIB';if(sourceTask&&sourceTask!=='SEANCE_COMPLETE')return sourceTask;if(SESSION_TASK[session])return SESSION_TASK[session];if(sourceTask.includes('GAIT')||sourceTask.includes('WALK')||sourceTask.includes('MARCHE'))return'GAIT_4X2M';return sourceTask||'UNMAPPED_TASK'}
function metricMap(code){const x=h(code);if(METRICS[x])return METRICS[x];if(x==='CCI'||x.includes('COACTIVATION')||x.includes('COCONTRACTION'))return['CCI_pct','%'];if(x.includes('FATIGUE')||x.includes('DRIFT'))return['fatigue_drift_pct','%'];if(x.includes('ASYMMETRY')||x.includes('ASYMETRIE'))return['asymmetry_pct','%'];return null}
function calibrationKeys(raw){const out=new Set();for(const r0 of raw){const r=flat(r0);if(h(r.METRIC_CODE)!=='EMG_MVC_REF_UV'||qc(r.QC_STATUS)!=='VALID')continue;out.add(`${String(r.EXTERNAL_SESSION_ID||'').trim()}|${muscle(r.MUSCLE)}|${side(r.SIDE)}`)}return out}
async function normalize(raw){const rows=[],warnings=[],unknown=[],cals=calibrationKeys(raw);for(let i=0;i<raw.length;i++){const r=flat(raw[i]);const sourceCode=h(r.METRIC_CODE||r.METRIC||r.PARAMETER);const mapped=metricMap(sourceCode);if(!mapped){unknown.push(sourceCode||`ROW_${i+1}`);continue}const value=num(r.VALUE??r.METRIC_VALUE??r.RESULT);if(value===null){warnings.push(['NON_NUMERIC',`Ligne ${i+1}: valeur non numérique pour ${sourceCode}.`]);continue}const session=String(r.EXTERNAL_SESSION_ID||r.SESSION_ID||'').trim();const version=String(r.SOURCE_VERSION||r.SOFTWARE_VERSION||'').trim();const taskCode=resolveTask(r);const mu=muscle(r.MUSCLE);let sd=side(r.SIDE);const metricCode=mapped[0];if(['LSI_pct','asymmetry_pct'].includes(metricCode))sd='BILATERAL';if(metricCode.startsWith('gait_')||['cadence_spm','step_count','stance_time_s','swing_time_s','step_time_s','step_length_m','double_support_pct'].includes(metricCode))sd='NA';let q=qc(r.QC_STATUS||r.QUALITY_STATUS||r.QC);let reason=String(r.REASON_CODE||'').trim()||null;const sourceCal=String(r.CALIBRATION_ID||'').trim()||null;let calibrationId=sourceCal;if(metricCode==='MVC_value'&&!calibrationId)calibrationId=`myocare:${session}:mvc:${mu}:${sd}:${version||'source'}`;if(['activation_pctMVC','CCI_pct','fatigue_drift_pct'].includes(metricCode)){const hasRef=cals.has(`${session}|${mu}|${sd}`);if(!hasRef){q=q==='INVALID'?'INVALID':'SUSPECT';reason=reason||'CALIBRATION_REFERENCE_MISSING';warnings.push(['CALIBRATION_REVIEW',`${session} · ${mu} ${sd}: référence MVIC absente ou non valide.`])}}if(metricCode==='activation_pctMVC'&&value>150){q=q==='INVALID'?'INVALID':'SUSPECT';reason=reason||'NORMALIZATION_REVIEW_GT150';warnings.push(['NORMALIZATION_REVIEW',`${session} · ${mu} ${sd}: activation ${value}%MVC >150%, revue de normalisation.`])}const recordedAt=iso(r.RECORDED_AT||r.TIMESTAMP||r.DATE)||new Date().toISOString();const canonical={externalSessionId:session,sourceVersion:version,recordedAt,taskCode,trialIndex:num(r.TRIAL_INDEX),muscleCode:metricCode.startsWith('gait_')?'NA':mu,side:sd,phaseWindow:null,metricCode,value,unit:mapped[1],directionality:'descriptive',qcStatus:q,qcReason:reason,protocolVersion:PROTOCOL,calibrationId,referenceSetId:null};canonical.rowHash=await sha256([session,taskCode,sourceCode,sd,mu,version,value,i].join('|'));rows.push(canonical)}if(unknown.length)warnings.push(['UNMAPPED_DESCRIPTIVE',`${unknown.length} ligne(s) non importées: ${[...new Set(unknown)].slice(0,6).join(', ')}${unknown.length>6?'…':''}`]);if(!rows.some(r=>r.metricCode==='CCI_pct'))warnings.push(['CCI_NOT_EXPORTED','CCI absent : coordination conservée comme indisponible, sans bloquer le score technique.']);if(!rows.some(r=>r.metricCode.startsWith('gait_')))warnings.push(['GAIT_SPATIOTEMPORAL_MISSING','Aucun GAIT_* spatio-temporel : la marche est affichée comme analyse neuromusculaire uniquement.']);return{rows,warnings}}
function symmetrySummary(rows){const by={};for(const r of rows){if(r.metricCode!=='LSI_pct'||r.qcStatus!=='VALID'||!FUNCTIONAL_TASKS.includes(r.taskCode))continue;(by[r.taskCode]||(by[r.taskCode]=[])).push(r.value)}const taskMeans={};for(const[t,vals]of Object.entries(by))taskMeans[t]=vals.reduce((a,b)=>a+b,0)/vals.length;const vals=Object.values(taskMeans);return{taskMeans,count:vals.length,score:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}}
async function parse(file){const ext=(file.name.split('.').pop()||'').toLowerCase(),buf=await file.arrayBuffer(),fileHash=await sha256(buf);let raw=[],sheetName=null;if(ext==='json'){const j=JSON.parse(new TextDecoder().decode(buf));raw=Array.isArray(j)?j:Array.isArray(j.rows)?j.rows:Array.isArray(j.data)?j.data:[j]}else if(ext==='csv'){raw=csv(new TextDecoder().decode(buf))}else if(['xlsx','xls'].includes(ext)){const XLSX=await import('https://esm.sh/xlsx@0.18.5');const wb=XLSX.read(buf,{type:'array',cellDates:true});let best=[];for(const name of wb.SheetNames){const candidate=objectsFromSheet(XLSX,wb.Sheets[name]);if(candidate.length>best.length){best=candidate;sheetName=name}}raw=best}else throw new Error('Format non supporté.');if(!raw.length)throw new Error('Aucune table MyoDev long-format détectée.');const normalized=await normalize(raw);const f=flat(raw[0]);const sessions=[...new Set(raw.map(r=>String(flat(r).EXTERNAL_SESSION_ID||'').trim()).filter(Boolean))];const patient=String(f.PATIENT_PSEUDONYM||'').trim();const symmetry=symmetrySummary(normalized.rows);return{fileName:file.name,fileSize:file.size,fileHash,format:['xlsx','xls'].includes(ext)?'xlsx':ext,sheetName,rawCount:raw.length,columns:[...new Set(raw.flatMap(r=>Object.keys(r)))],sessions,patientPseudonym:patient,symmetry,...normalized,meta:{external_session_id:patient?`${patient}-GLOBAL`:(sessions[0]||`KOMO-${Date.now()}`),source_version:String(f.SOURCE_VERSION||f.SOFTWARE_VERSION||'MyoLab'),recorded_at:iso(f.RECORDED_AT||f.TIMESTAMP)||new Date().toISOString()},adapter:ADAPTER}}
function preview(){const p=state.parsed;if(!p)return'';const sym=p.symmetry.score;const taskLine=Object.entries(p.symmetry.taskMeans).map(([k,v])=>`${k.replaceAll('_',' ')} ${v.toFixed(1)}`).join(' · ');return`<div class=\"clm-import-summary\"><span>${p.rows.length}/${p.rawCount} métriques</span><span>${p.sessions.length} session(s)</span><span>${esc(p.sheetName||'source')}</span></div><div class=\"clm-import-summary\"><span>Patient technique ${esc(p.patientPseudonym||'—')}</span><span>Symétrie fonctionnelle ${sym==null?'—':sym.toFixed(1)+'/100'}</span></div>${taskLine?`<div class=\"clm-file\">${esc(taskLine)}</div>`:''}${p.warnings.length?`<div class=\"clm-warning-list\">${p.warnings.slice(0,12).map(([c,m])=>`<div class=\"clm-warning\">${esc(c)} · ${esc(m)}</div>`).join('')}</div>`:''}<div class=\"clm-preview\"><table><thead><tr><th>Session</th><th>Tâche</th><th>Muscle</th><th>Côté</th><th>Métrique</th><th>Valeur</th><th>QC</th></tr></thead><tbody>${p.rows.slice(0,12).map(r=>`<tr><td>${esc(r.externalSessionId)}</td><td>${esc(r.taskCode)}</td><td>${esc(r.muscleCode)}</td><td>${esc(r.side)}</td><td>${esc(r.metricCode)}</td><td>${esc(r.value)} ${esc(r.unit)}</td><td>${esc(r.qcStatus)}</td></tr>`).join('')}</tbody></table></div>`}
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,5200)}
function mount(){const box=document.querySelector('#clmImporter');if(!box||!state.assessmentId)return;const p=state.parsed;box.innerHTML=`<div class=\"clm-import\"><div class=\"clm-drop\"><strong>Importer l’analyse MyoCare / MyoLab</strong><span>Le classeur KŌMØ v0.6 est lu directement : sessions, calibration, activation, LSI et marche neuromusculaire.</span><input id=\"clmFile\" type=\"file\" accept=\".xlsx,.xls,.csv,.json\"><div class=\"clm-file\">${p?`${esc(p.fileName)} · ${p.rows.length} métriques prêtes`:'Aucun fichier sélectionné'}</div></div>${p?preview():''}<div class=\"clm-actions\"><button id=\"clmImportBtn\" class=\"clm-btn primary\" type=\"button\" ${!p||state.busy?'disabled':''}>${state.busy?'Import en cours…':'Importer et recalculer Motion'}</button></div></div>`;box.querySelector('#clmFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{toast('Analyse du classeur MyoDev…');state.parsed=await parse(f);mount();toast(`${state.parsed.rows.length} métriques reconnues · ${state.parsed.sessions.length} sessions · symétrie ${state.parsed.symmetry.score?.toFixed(1)??'—'}/100.`)}catch(err){console.error('[myocare-import parse]',err);toast(`Fichier MyoCare non lisible : ${err.message||err}`)}});box.querySelector('#clmImportBtn')?.addEventListener('click',run)}
async function run(){if(state.busy||!state.parsed||!state.assessmentId)return;state.busy=true;mount();try{const p=state.parsed;if(!p.rows.length)throw new Error('Aucune métrique exploitable après normalisation.');const manifest={adapter:p.adapter,sourceSchema:'myodev-komo-1.0',rawRowCount:p.rawCount,normalizedRowCount:p.rows.length,sourceColumns:p.columns,sourceSheet:p.sheetName,externalSessionIds:p.sessions,patientPseudonym:p.patientPseudonym,protocolVersion:PROTOCOL,functionalSymmetryPreview:p.symmetry,calibrationStrategy:'source_MVIC_reference',scorePolicy:'equal_mean_of_4_functional_tests',cciPolicy:'descriptive_when_exported',gaitPolicy:'neuromuscular_only_without_GAIT_metrics'};const args={target_assessment_id:state.assessmentId,target_contract_code:CONTRACT,target_external_session_id:p.meta.external_session_id,target_source_product:'myocare',target_source_version:p.meta.source_version||'MyoLab',target_source_format:p.format,target_source_file_name:p.fileName,target_import_hash:p.fileHash,target_payload_manifest:manifest,target_device_set_id:null,target_recorded_at:p.meta.recorded_at,metric_batch:p.rows,import_warnings:p.warnings.map(([code,message])=>({code,message}))};const c=sb();const imp=await c.rpc('import_pulse_myodev_result',args);if(imp.error)throw imp.error;const score=await c.rpc('calculate_motion_v05',{p_assessment_id:state.assessmentId});if(score.error)throw score.error;const sym=score.data?.domain_scores?.myocare_symmetry;toast(`Import accepté · ${p.rows.length} métriques · symétrie ${sym??p.symmetry.score?.toFixed(1)??'—'}/100${score.data?.motion_score!=null?` · Motion ${score.data.motion_score}/100`:' · Motion en attente du score Mobilité'}`);window.dispatchEvent(new CustomEvent('komo:myocare-imported',{detail:{assessmentId:state.assessmentId,importId:imp.data,score:score.data,normalizedRows:p.rows.length,sessions:p.sessions}}));state.parsed=null;mount()}catch(err){console.error('[myocare-import run]',err);const raw=String(err?.message||err);const msg=raw.includes('active_myodev_contract_required')?'Contrat MyoCare non actif.':raw.includes('assessment_locked')?'Ce bilan Motion est verrouillé. Créez ou rouvrez un bilan en brouillon.':raw;toast(`Import MyoCare impossible : ${msg}`)}finally{state.busy=false;mount()}}
window.addEventListener('komo:clinical-motion-render',e=>{state.assessmentId=e.detail?.assessmentId||null;state.userId=e.detail?.userId||null;state.parsed=null;mount()});
window.addEventListener('komo:myocare-open',()=>document.querySelector('#clmFile')?.click());
document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,100));
window.KomoMyoCareImport={version:'primary-v0.6',contract:CONTRACT,protocol:PROTOCOL,parseFile:parse};
