import { loadCanonicalResult } from './canonical-result-runtime.js';

const VERSION='3.0.0';
let busy=false,timer=0,lastKey='';
const route=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const memberMode=()=>{const b=document.querySelector('#modeSwitch button[data-mode="member"]');return !b||b.classList.contains('active')};
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const fmtDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short',year:'numeric'}).format(d).replace('.','')};
const go=r=>{location.hash=`#${r}`};
function openKomo(){const b=document.querySelector('#komoOperatorLauncher');if(b&&!b.hidden)b.click();else window.dispatchEvent(new CustomEvent('komo:operator-open'))}
function released(s){return['released','published'].includes(String(s?.release_status||s?.status||'').toLowerCase())}
function score(s){const v=n(s?.motion_score??s?.overall_score);return v===null?null:Math.round(v)}
function domains(s){const raw=s?.domain_scores??s?.subscores??{};const labels={mobility:'Mobilité',strength:'Force',balance:'Équilibre',posture:'Posture',gait:'Marche',muscle:'Muscle',recovery:'Récupération',reserve:'Réserve',performance:'Performance',muscle_control:'Contrôle musculaire',quality:'Qualité'};return Object.entries(raw||{}).map(([k,v])=>[labels[k]||k.replaceAll('_',' '),n(typeof v==='object'&&v!==null?(v.score??v.value):v)]).filter(([,v])=>v!==null)}
async function history(patientId){const c=window.KomoRuntime?.client;if(!c||!patientId)return[];const a=await c.from('assessments').select('id,completed_at,created_at').eq('patient_id',patientId).order('created_at',{ascending:false}).limit(20);if(a.error||!a.data?.length)return[];const ids=a.data.map(x=>x.id),dates=new Map(a.data.map(x=>[x.id,x.completed_at||x.created_at]));const q=await c.from('scores').select('*').in('assessment_id',ids).eq('release_status','released').order('calculated_at',{ascending:false}).limit(12);if(q.error)return[];return(q.data||[]).map(x=>({...x,_date:x.calculated_at||dates.get(x.assessment_id)||x.created_at})).filter(x=>score(x)!==null).sort((a,b)=>new Date(b._date||0)-new Date(a._date||0))}
async function nextAppointment(){try{const c=window.KomoRuntime?.client;if(!c)return null;const r=await c.functions.invoke('motion-journey-status',{body:{}});return r.error?null:r.data?.journey?.appointment||null}catch{return null}}
function changeText(cur,prev){if(cur===null)return{title:'Aucune référence publiée',copy:'Votre trajectoire commencera avec votre premier bilan Motion validé.',tone:'neutral'};if(prev===null)return{title:'Première référence',copy:'Ce score devient votre point de départ. La prochaine mesure permettra enfin de parler d’évolution.',tone:'neutral'};const d=Math.round(cur-prev);if(Math.abs(d)<1)return{title:'Stable',copy:'Votre Motion Score est très proche de la référence précédente.',tone:'neutral'};return{title:`${d>0?'+':''}${d} point${Math.abs(d)>1?'s':''}`,copy:`Votre Motion Score est ${d>0?'plus élevé':'plus bas'} que lors de la mesure précédente.`,tone:d>0?'good':'watch'}}
function domainChanges(cur,prev){if(!cur||!prev)return[];const a=new Map(domains(cur)),b=new Map(domains(prev));return[...a.entries()].filter(([k])=>b.has(k)).map(([k,v])=>({label:k,current:v,previous:b.get(k),delta:v-b.get(k)})).sort((x,y)=>Math.abs(y.delta)-Math.abs(x.delta)).slice(0,4)}
function styles(){if(document.querySelector('#ktrv3Style'))return;const s=document.createElement('style');s.id='ktrv3Style';s.textContent=`
body.ktrajectory-v1{--kt-bg:#070907;--kt-panel:#101411;--kt-line:rgba(244,241,234,.085);--kt-text:#f2f0e9;--kt-muted:#89928b;--kt-ivory:#eeeae1;--kt-ink:#172019;background:var(--kt-bg)!important}body.ktrajectory-v1 #appShell,body.ktrajectory-v1 .main-shell{background:radial-gradient(850px 500px at 92% -8%,rgba(115,150,124,.08),transparent 62%),linear-gradient(180deg,#090b09,#060806)!important;color:var(--kt-text)!important}body.ktrajectory-v1 #viewRoot{width:min(calc(100% - 40px),1240px)!important;max-width:1240px!important;margin:0 auto!important;padding:30px 0 120px!important;background:transparent!important}body.ktrajectory-v1 #viewRoot>:not([data-ktrajectory-v1]){display:none!important}
.ktr{display:grid;gap:18px;font-family:'DM Sans',Manrope,sans-serif;color:var(--kt-text)}.ktr button{font:inherit}.ktr-head{display:flex;align-items:flex-end;justify-content:space-between;gap:26px}.ktr-head span,.ktr-kicker{display:block;color:#768079;font-size:9px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.ktr-head h2{margin:9px 0 0;font:600 clamp(34px,4vw,52px)/.96 Manrope,sans-serif;letter-spacing:-.055em}.ktr-head p{margin:9px 0 0;color:var(--kt-muted);font-size:12px}.ktr-komo{display:flex;align-items:center;gap:9px;min-height:44px;padding:0 15px;border:1px solid var(--kt-line);border-radius:14px;background:#101411;color:#d7dbd5;cursor:pointer}.ktr-komo span{color:#aab8ab;font-size:18px}.ktr-komo strong{font-size:10px}
.ktr-hero{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(330px,.9fr);overflow:hidden;border-radius:29px}.ktr-current{padding:34px 38px;background:linear-gradient(145deg,#f1eee6,#e4e0d7);color:var(--kt-ink)}.ktr-current>span{color:#617067;font-size:9px;font-weight:850;letter-spacing:.14em}.ktr-current-main{display:flex;align-items:flex-end;gap:8px;margin:32px 0 14px}.ktr-current-main strong{font:600 clamp(82px,9vw,120px)/.78 Manrope,sans-serif;letter-spacing:-.09em}.ktr-current-main small{padding-bottom:10px;color:#667169;font-size:14px}.ktr-current h3{margin:0;font:600 22px/1.08 Manrope,sans-serif;letter-spacing:-.04em}.ktr-current p{max-width:590px;margin:11px 0 0;color:#657068;font-size:11px;line-height:1.6}.ktr-compare{display:flex;flex-direction:column;justify-content:center;padding:34px;background:linear-gradient(145deg,#1b3024,#294735)}.ktr-compare .ktr-kicker{color:#a5b7a8}.ktr-change{display:inline-flex;align-items:baseline;gap:10px;margin:17px 0 8px}.ktr-change strong{font:600 45px/1 Manrope,sans-serif;letter-spacing:-.055em}.ktr-change.good strong{color:#dce8dd}.ktr-change.watch strong{color:#e7c9bd}.ktr-change.neutral strong{color:#ecebe5}.ktr-compare h3{margin:0;color:#eef0eb;font:600 20px/1.1 Manrope,sans-serif}.ktr-compare p{margin:9px 0 0;color:#a9b5ab;font-size:10px;line-height:1.6}.ktr-compare button{align-self:flex-start;margin-top:22px;border:0;background:transparent;color:#d3ddd5;font-size:10px;font-weight:800;cursor:pointer}
.ktr-section{display:grid;gap:12px}.ktr-section-head h3{margin:0;font:600 22px/1 Manrope,sans-serif;letter-spacing:-.04em}.ktr-section-head p{margin:6px 0 0;color:#7e8780;font-size:10px}.ktr-domain-changes{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ktr-domain{padding:19px;border:1px solid var(--kt-line);border-radius:20px;background:#101411}.ktr-domain>span{color:#89928b;font-size:9px;font-weight:750}.ktr-domain strong{display:block;margin-top:18px;font:600 26px/1 Manrope,sans-serif}.ktr-domain strong.good{color:#afc4b2}.ktr-domain strong.watch{color:#d3b5a9}.ktr-domain p{margin:7px 0 0;color:#768078;font-size:9px}.ktr-domain small{display:block;margin-top:12px;color:#69726b;font-size:8px}
.ktr-history{padding:25px;border:1px solid var(--kt-line);border-radius:24px;background:#0f1310}.ktr-history-row{display:grid;grid-template-columns:110px 70px 1fr;align-items:center;gap:16px;min-height:62px;border-top:1px solid rgba(255,255,255,.055)}.ktr-history-row:first-child{border-top:0}.ktr-history-row time{color:#79827b;font-size:9px}.ktr-history-row strong{font:600 22px/1 Manrope,sans-serif}.ktr-history-row strong small{color:#6f7871;font-size:8px}.ktr-bar{height:5px;border-radius:99px;background:#202621;overflow:hidden}.ktr-bar i{display:block;width:var(--v);height:100%;border-radius:inherit;background:#a9bbaa}
.ktr-next{display:flex;align-items:center;justify-content:space-between;gap:26px;padding:26px 28px;border-radius:23px;background:linear-gradient(135deg,#d7dfd4,#b9c9bb);color:#172019}.ktr-next h3{margin:8px 0 0;font:600 23px/1.05 Manrope,sans-serif;letter-spacing:-.04em}.ktr-next p{margin:8px 0 0;color:#56645b;font-size:10px}.ktr-next button{min-height:44px;padding:0 14px;border:0;border-radius:13px;background:#18281d;color:#f0eee8;font-size:9px;font-weight:800;cursor:pointer;white-space:nowrap}.ktr-empty{padding:28px;border:1px solid var(--kt-line);border-radius:22px;background:#101411;color:#8b948d;font-size:11px;line-height:1.6}
@media(max-width:900px){.ktr-hero{grid-template-columns:1fr}.ktr-domain-changes{grid-template-columns:1fr 1fr}.ktr-next{align-items:flex-start;flex-direction:column}}@media(max-width:767px){body.ktrajectory-v1 #viewRoot{width:100%!important;padding:14px 14px calc(96px + env(safe-area-inset-bottom))!important}.ktr{gap:14px}.ktr-head{display:grid;gap:13px}.ktr-head h2{font-size:34px}.ktr-komo{justify-self:start}.ktr-current,.ktr-compare{padding:25px 21px}.ktr-current-main strong{font-size:86px}.ktr-domain-changes{grid-template-columns:1fr}.ktr-history{padding:18px}.ktr-history-row{grid-template-columns:88px 60px 1fr;gap:10px}.ktr-next{padding:22px 20px}}
`;document.head.appendChild(s)}
function markup(result,rows,appt){const current=rows[0]||null,previous=rows[1]||null,cur=score(current),prev=score(previous),chg=changeText(cur,prev),dc=domainChanges(current,previous);const next=appt?.scheduled_start?`Prochaine mesure prévue le ${fmtDate(appt.scheduled_start)}.`:'Aucune prochaine mesure n’est encore planifiée.';return `<section class="ktr" data-ktrajectory-v1><header class="ktr-head"><div><span>KŌMØ PULSE · TRAJECTOIRE</span><h2>Est-ce que votre mobilité change ?</h2><p>Une seule mission : comparer des références validées dans le temps.</p></div><button class="ktr-komo" type="button" data-ktr-komo><span aria-hidden="true">ōø</span><strong>Demander à Komo</strong></button></header>${cur===null?`<div class="ktr-empty"><strong>Votre trajectoire n’a pas encore commencé.</strong><br>Elle apparaîtra après la publication de votre première référence Motion.</div>`:`<section class="ktr-hero"><article class="ktr-current"><span>RÉFÉRENCE ACTUELLE</span><div class="ktr-current-main"><strong>${cur}</strong><small>/100</small></div><h3>${fmtDate(current._date)}</h3><p>Cette valeur est votre dernier Motion Score publié. Elle ne prend son vrai sens qu’en comparaison avec vos références précédentes.</p></article><aside class="ktr-compare"><span class="ktr-kicker">DEPUIS LA MESURE PRÉCÉDENTE</span><div class="ktr-change ${chg.tone}"><strong>${esc(chg.title)}</strong></div><h3>${prev===null?'Nous construisons votre baseline.':'Votre évolution globale'}</h3><p>${esc(chg.copy)}</p><button type="button" data-ktr-komo>Pourquoi ? Demander à Komo →</button></aside></section>`}${dc.length?`<section class="ktr-section"><div class="ktr-section-head"><h3>Ce qui a le plus changé</h3><p>Les variations les plus visibles entre vos deux dernières références publiées.</p></div><div class="ktr-domain-changes">${dc.map(x=>`<article class="ktr-domain"><span>${esc(x.label)}</span><strong class="${x.delta>=0?'good':'watch'}">${x.delta>=0?'+':''}${Math.round(x.delta)} pts</strong><p>${Math.round(x.previous)} → ${Math.round(x.current)}/100</p><small>À interpréter avec le contexte du bilan.</small></article>`).join('')}</div></section>`:''}${rows.length?`<section class="ktr-section"><div class="ktr-section-head"><h3>Vos références</h3><p>Seuls les résultats publiés sont utilisés dans cette trajectoire.</p></div><div class="ktr-history">${rows.slice(0,8).map((x,i)=>{const v=score(x);return`<div class="ktr-history-row"><time>${fmtDate(x._date)}</time><strong>${v}<small>/100</small></strong><div class="ktr-bar"><i style="--v:${Math.max(0,Math.min(100,v))}%"></i></div></div>`}).join('')}</div></section>`:''}<section class="ktr-next"><div><span class="ktr-kicker">PROCHAINE RÉFÉRENCE</span><h3>${prev===null?'La prochaine mesure créera votre première comparaison.':'Continuez à mesurer avec le même protocole.'}</h3><p>${esc(next)}</p></div><button type="button" data-ktr-route="agenda">Voir mon agenda →</button></section></section>`}
function bind(host){host.querySelectorAll('[data-ktr-komo]').forEach(b=>b.addEventListener('click',openKomo));host.querySelectorAll('[data-ktr-route]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.ktrRoute||'home')))}
function tune(){document.body.classList.add('ktrajectory-v1');const e=document.querySelector('#pageEyebrow'),t=document.querySelector('#pageTitle');if(e)e.textContent='KŌMØ PULSE · TRAJECTOIRE';if(t)t.textContent='Votre évolution'}function untune(){document.body.classList.remove('ktrajectory-v1')}
async function mount(force=false){if(route()!=='path'||!memberMode()){untune();return}if(busy)return;const root=document.querySelector('#viewRoot');if(!root)return;busy=true;try{styles();tune();const result=await loadCanonicalResult({force});const [rows,appt]=await Promise.all([history(result?.patientId),nextAppointment()]);const key=`${rows.map(x=>x.id).join(':')}:${appt?.id||''}`;if(key===lastKey&&root.querySelector('[data-ktrajectory-v1]'))return;root.querySelector('[data-ktrajectory-v1]')?.remove();const h=document.createElement('div');h.innerHTML=markup(result,rows,appt);const node=h.firstElementChild;root.prepend(node);bind(node);lastKey=key}catch(e){console.error('[trajectory-v1]',e)}finally{busy=false}}
function schedule(force=false,ms=180){clearTimeout(timer);timer=setTimeout(()=>mount(force),ms)}
['hashchange','pageshow','komo:route-ready','komo:canonical-result-ready','komo:data-ready','komo:motion-v05-release'].forEach(e=>window.addEventListener(e,()=>schedule(e==='komo:data-ready'||e==='komo:motion-v05-release')));document.addEventListener('DOMContentLoaded',()=>schedule(true,1000));const obs=new MutationObserver(()=>{if(route()==='path'&&memberMode()&&!document.querySelector('[data-ktrajectory-v1]'))schedule(false,120)});obs.observe(document.body,{subtree:true,childList:true});setTimeout(()=>schedule(true,50),1800);window.KomoTrajectoryV1={version:VERSION,refresh:()=>schedule(true,40)};
