import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const URL='https://uqlolefsiktbznnymriy.supabase.co';
const KEY='sb_publishable_3sUsinfJ_nMFI44OXozkKQ_jmGG8w7n';
const REM='komo_pulse_remember';
let client=null,busy=false,timer=null;
function storage(){return localStorage.getItem(REM)==='1'?localStorage:sessionStorage}
function sb(){return window.KomoRuntime?.client||(client||(client=createClient(URL,KEY,{auth:{storage:storage(),persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})))}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmt(v){if(!v)return'À programmer';return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Paris'}).format(new Date(v))}
function n(v){const x=Number(v);return Number.isFinite(x)?x:null}
function memberMode(){const b=document.querySelector('#modeSwitch button[data-mode="member"]');return !b||b.classList.contains('active')}
function apptLabel(v){return v==='clinical'?'KŌMØ Clinical':v==='motion'?'KŌMØ Motion':'Consultation KŌMØ'}
async function readData(){const c=sb(),ctx=window.KomoRuntime?.getContext?.(),session=ctx?.session||(await c.auth.getSession()).data?.session;if(!session?.user)return null;const p=await c.from('patients').select('id').eq('patient_user_id',session.user.id);const pids=(p.data||[]).map(x=>x.id);if(!pids.length)return{priorities:[],appointments:[],score:null};const ar=await c.from('assessments').select('id,created_at').in('patient_id',pids).order('created_at',{ascending:false});const aids=(ar.data||[]).map(x=>x.id);const [pr,ap,sc]=await Promise.all([aids.length?c.from('priorities').select('*').in('assessment_id',aids).eq('validation_status','validated').order('rank',{ascending:true}):Promise.resolve({data:[]}),c.from('organization_appointments').select('id,appointment_type,scheduled_start,status,organization_id').in('patient_id',pids).in('status',['scheduled','confirmed','arrived','in_progress']).order('scheduled_start',{ascending:true}),aids.length?c.from('scores').select('motion_score,domain_scores,calculated_at').in('assessment_id',aids).eq('release_status','released').order('calculated_at',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null})]);return{priorities:pr.data||[],appointments:ap.data||[],score:sc.data||null}}
function weakest(score){const d=score?.domain_scores||{},rows=[['Mobilité',n(d.mobility)],['Symétrie musculaire',n(d.myocare_symmetry)],['Performance',n(d.performance)],['Équilibre',n(d.balance)]].filter(([,v])=>v!==null);return rows.sort((a,b)=>a[1]-b[1])[0]||null}
function therapyCard(x,i){return `<article class="kth-care"><div class="kth-care-top"><span>${String(x.rank||i+1).padStart(2,'0')}</span><b>Validé</b></div><h3>${esc(x.patient_wording||x.category||'Axe KŌMØ')}</h3><p>${esc(x.category||'Priorité issue de votre évaluation et validée par votre professionnel.')}</p><div class="kth-care-foot"><span>Plan de soins KŌMØ</span><strong>À suivre</strong></div></article>`}
function appointmentCard(a){return `<article class="kth-appt"><div><small>${esc(a.status==='scheduled'?'EN ATTENTE DE VALIDATION':'CONSULTATION VALIDÉE')}</small><h3>${esc(apptLabel(a.appointment_type))}</h3><p>${esc(fmt(a.scheduled_start))}</p></div><button type="button" data-route="documents">Agenda et réseau →</button></article>`}
function render(d){const root=document.querySelector('#viewRoot');if(!root)return;const focus=weakest(d.score),next=d.appointments[0]||null,validated=d.priorities.slice(0,6);document.querySelector('#pageEyebrow').textContent='KŌMØ THERAPY';document.querySelector('#pageTitle').textContent='Votre plan de soins et vos rappels.';root.innerHTML=`<div class="kth-page" data-therapy-page><section class="kth-hero"><div><p class="eyebrow">KŌMØ THERAPY</p><h2>Mesurer.<br><em>Agir. Réévaluer.</em></h2><p>Vos résultats servent à structurer les priorités de prise en charge. Le plan affiché ici ne contient que les axes validés par votre professionnel.</p><div class="kth-tags"><span>${d.score?.motion_score!=null?`Motion Score ${Math.round(Number(d.score.motion_score))}%`:'Motion Score en attente'}</span>${focus?`<span>Point d’attention · ${esc(focus[0])} ${Math.round(focus[1])}%</span>`:''}</div></div><aside><small>PROCHAINE CONSULTATION</small><strong>${next?fmt(next.scheduled_start):'À programmer'}</strong><span>${next?apptLabel(next.appointment_type):'Votre prochain rendez-vous apparaîtra ici.'}</span><button type="button" data-route="documents">Ouvrir Agenda et réseau →</button></aside></section><section class="kth-section"><div class="kth-head"><div><p class="eyebrow">PLAN DE SOINS</p><h2>Vos priorités actuelles.</h2></div><p>Les recommandations sont construites à partir de vos résultats puis validées humainement. Pulse n’invente pas de traitement en dehors de cette validation.</p></div>${validated.length?`<div class="kth-care-grid">${validated.map(therapyCard).join('')}</div>`:`<div class="kth-empty"><strong>Votre plan de soins est en préparation.</strong><p>Après validation de vos résultats, le professionnel pourra définir les axes de prise en charge et les objectifs de réévaluation.</p><button type="button" data-route="path">Voir My KŌMØ Score →</button></div>`}</section><section class="kth-section"><div class="kth-head"><div><p class="eyebrow">RAPPELS</p><h2>Vos consultations à venir.</h2></div><p>Motion, Clinical et réévaluations sont regroupés dans votre agenda.</p></div>${d.appointments.length?`<div class="kth-appt-grid">${d.appointments.slice(0,4).map(appointmentCard).join('')}</div>`:`<div class="kth-empty compact"><strong>Aucune consultation programmée.</strong><button type="button" data-route="documents">Trouver un centre →</button></div>`}</section><section class="kth-loop"><div><span>01</span><strong>Évaluer</strong><p>Start, Motion et Clinical.</p></div><i>→</i><div><span>02</span><strong>Prioriser</strong><p>Axes validés avec le professionnel.</p></div><i>→</i><div><span>03</span><strong>Agir</strong><p>Plan de soins et accompagnement.</p></div><i>→</i><div><span>04</span><strong>Réévaluer</strong><p>Nouveau score et trajectoire.</p></div></section></div>`}
async function mount(){if(location.hash!=='#plan'||!memberMode()||busy)return;busy=true;try{const d=await readData();if(d)render(d)}catch(e){console.error('[therapy-page]',e)}finally{busy=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(mount,150)}
window.addEventListener('hashchange',schedule);window.addEventListener('komo:route-ready',schedule);window.addEventListener('komo:motion-v05-release',schedule);document.querySelector('#refreshButton')?.addEventListener('click',()=>setTimeout(schedule,220));const vr=document.querySelector('#viewRoot');if(vr)new MutationObserver(()=>{if(location.hash==='#plan'&&!document.querySelector('[data-therapy-page]'))schedule()}).observe(vr,{childList:true,subtree:true});setTimeout(schedule,1200);
