import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { TwinCore, SOURCE_CATALOG } from '../v04/twin-core.js';

const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const canvas=$('#world-canvas');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0xaeb3a7); scene.fog=new THREE.Fog(0xaeb3a7,78,180);
const camera=new THREE.PerspectiveCamera(46,1,.1,360), clock=new THREE.Clock(), core=new TwinCore();

const C={stone:0xcdbda2,stone2:0xab9d86,sage:0x829582,sage2:0xa9b9a5,sand:0xdcc7a5,bronze:0x78614c,dark:0x121914,water:0x6e8580,rock:0x77776c,green:0xaac7a2,warn:0xd0a76f,arena:0xd7b678,arenaDark:0x251b10};
const mat=(color,rough=.76,metal=.02)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});
const glow=(color,intensity=.8,opacity=1)=>new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:intensity,transparent:opacity<1,opacity,depthWrite:opacity===1});
const glass=(color=C.sage2,opacity=.35)=>new THREE.MeshPhysicalMaterial({color,roughness:.2,metalness:.03,transparent:true,opacity,transmission:.24,depthWrite:true});
const box=(w,h,d,m,x=0,y=0,z=0)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o};
const cyl=(r1,r2,h,seg,m,x=0,y=0,z=0)=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,seg),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o};
function label(text,{sx=4,sy=.72,font=26,bg='rgba(18,25,20,.78)',color='#f4efe5'}={}){const c=document.createElement('canvas');c.width=720;c.height=140;const x=c.getContext('2d');x.fillStyle=bg;x.beginPath();x.roundRect?.(45,20,630,100,28);x.fill();x.strokeStyle='rgba(255,255,255,.14)';x.stroke();x.font=`500 ${font}px Arial`;x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.fillText(text,360,70);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(sx,sy,1);return s}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}

scene.add(new THREE.HemisphereLight(0xfff5e6,0x314235,2.2));
const sun=new THREE.DirectionalLight(0xffe9cf,3.25);sun.position.set(-28,46,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;scene.add(sun);
const fill=new THREE.DirectionalLight(0xc8d8ca,1.1);fill.position.set(32,20,-28);scene.add(fill);

// ---------- persistent player / controls ----------
const defaults={preset:'wasd',bindings:{forward:'w',backward:'s',left:'a',right:'d',sprint:'shift',interact:'e'},camera:{sensX:1,sensY:1,distance:21,invertY:false}};
const clone=v=>JSON.parse(JSON.stringify(v));
function loadSettings(){try{const s=JSON.parse(localStorage.getItem('komo_world_controls_v08')||'null');return s?{...clone(defaults),...s,bindings:{...defaults.bindings,...s.bindings},camera:{...defaults.camera,...s.camera}}:clone(defaults)}catch{return clone(defaults)}}
let settings=loadSettings();
const presetBindings={wasd:{forward:'w',backward:'s',left:'a',right:'d'},zqsd:{forward:'z',backward:'s',left:'q',right:'d'},arrows:{forward:'arrowup',backward:'arrowdown',left:'arrowleft',right:'arrowright'}};
function saveSettings(){localStorage.setItem('komo_world_controls_v08',JSON.stringify(settings));applySettings()}
function applySettings(){document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===settings.preset));$('#sens-x').value=settings.camera.sensX;$('#sens-y').value=settings.camera.sensY;$('#camera-distance').value=settings.camera.distance;$('#invert-y').checked=settings.camera.invertY}
$$('[data-preset]').forEach(b=>b.onclick=()=>{settings.preset=b.dataset.preset;settings.bindings={...settings.bindings,...presetBindings[b.dataset.preset]};saveSettings()});
['sens-x','sens-y','camera-distance'].forEach(id=>$('#'+id).oninput=()=>{settings.camera.sensX=Number($('#sens-x').value);settings.camera.sensY=Number($('#sens-y').value);settings.camera.distance=Number($('#camera-distance').value);saveSettings()});
$('#invert-y').onchange=()=>{settings.camera.invertY=$('#invert-y').checked;saveSettings()}; applySettings();

// ---------- world ----------
const water=new THREE.Mesh(new THREE.CircleGeometry(165,192),new THREE.MeshPhysicalMaterial({color:C.water,roughness:.22,transparent:true,opacity:.9,transmission:.05}));water.rotation.x=-Math.PI/2;water.position.y=-1.35;scene.add(water);
const island=cyl(61,65,2.4,160,mat(0x505d4c,.98),0,-1.22,0);scene.add(island);const islandTop=new THREE.Mesh(new THREE.CircleGeometry(60.7,160),mat(0x748069,.97));islandTop.rotation.x=-Math.PI/2;islandTop.position.y=-.02;scene.add(islandTop);
for(let i=0;i<64;i++){const a=i/64*Math.PI*2,r=60.6+Math.sin(i*2.6)*.9,s=.52+(i%5)*.12;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(s),mat(i%3?C.rock:0x686e63,.94));rock.position.set(Math.cos(a)*r,-.25,Math.sin(a)*r);rock.scale.set(1.5,.72,1);scene.add(rock)}
function tree(x,z,s=.85){const g=new THREE.Group();g.add(cyl(.16*s,.23*s,2.5*s,9,mat(0x64503e,.95),0,1.25*s,0));const c=new THREE.Mesh(new THREE.IcosahedronGeometry(1.35*s,2),mat(C.sage,.98));c.scale.set(.9,1.34,.9);c.position.y=3.15*s;c.castShadow=true;g.add(c);g.position.set(x,0,z);scene.add(g)}
[[-16,36],[16,36],[-22,25],[22,25],[-31,8],[31,8],[-36,-13],[36,-13],[-26,-34],[26,-34],[-6,-49],[8,-50]].forEach((p,i)=>tree(...p,.72+(i%4)*.08));
const plaza=cyl(19,19,.2,100,mat(C.stone,.91),0,.06,34);scene.add(plaza);scene.add(box(11,.14,49,mat(0xb8aa92,.93),0,.07,10));
const spawnRing=new THREE.Mesh(new THREE.RingGeometry(2.2,2.55,72),new THREE.MeshBasicMaterial({color:C.sand,transparent:true,opacity:.55,side:THREE.DoubleSide}));spawnRing.rotation.x=-Math.PI/2;spawnRing.position.set(0,.16,43);scene.add(spawnRing);

// Hall
const hall=new THREE.Group();hall.position.set(0,0,-10);scene.add(hall);hall.add(box(48,.35,32,mat(0xb9ad96,.9),0,.18,0));hall.add(box(.55,9.5,32,mat(0xb5a98f,.87),-23.7,4.75,0));hall.add(box(.55,9.5,32,mat(0xb5a98f,.87),23.7,4.75,0));
[[-18,7],[-6,5],[6,5],[18,7]].forEach(([x,w])=>hall.add(box(w,9.5,.55,mat(0xb5a98f,.87),x,4.75,-15.7)));
for(let z=-10;z<=10;z+=5)hall.add(box(49,.22,.34,mat(C.bronze,.5,.38),0,9.3,z));const roofGlass=new THREE.Mesh(new THREE.PlaneGeometry(47,22),glass(C.sage2,.22));roofGlass.rotation.x=Math.PI/2;roofGlass.position.y=9.25;hall.add(roofGlass);const hallSign=label('THE KŌMØ HALL',{sx:5.6,sy:1,font:31});hallSign.position.set(0,8.2,15.5);hall.add(hallSign);

// desk + NPC
hall.add(box(9,1.55,1.7,mat(0x6e6557,.54,.18),0,.78,5));hall.add(box(9.4,.18,2,mat(0xd8c4a4,.65),0,1.62,5));const deskLabel=label('KŌMØ DESK',{sx:2.7,sy:.58,font:23});deskLabel.position.set(0,3.25,5);hall.add(deskLabel);
function humanoid({body=0x889784,skin=0xbc8869,holo=false,scale=1}={}){const g=new THREE.Group();const bm=holo?new THREE.MeshPhysicalMaterial({color:body,roughness:.22,transparent:true,opacity:.48,transmission:.16,emissive:0x314b38,emissiveIntensity:.36}):mat(body,.7);const sm=holo?bm:mat(skin,.68);const pelvis=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.48,6,14),bm);pelvis.position.y=2.05;g.add(pelvis);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.2,8,18),bm);torso.position.y=3.05;torso.scale.set(1,.92,.75);g.add(torso);const chest=new THREE.Mesh(new THREE.SphereGeometry(.59,22,16),bm);chest.scale.set(1,.7,.72);chest.position.y=3.5;g.add(chest);const neck=cyl(.16,.18,.28,12,sm,0,4.05,0);g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.46,24,18),sm);head.position.y=4.45;head.scale.set(.9,1.08,.88);g.add(head);const limbs={};[['la',-.7],['ra',.7]].forEach(([n,x])=>{const p=new THREE.Group();p.position.set(x,3.55,0);const upper=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.72,5,10),sm);upper.position.y=-.43;p.add(upper);const fore=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.68,5,10),sm);fore.position.y=-1.13;p.add(fore);g.add(p);limbs[n]=p});[['ll',-.29],['rl',.29]].forEach(([n,x])=>{const p=new THREE.Group();p.position.set(x,2.0,0);const thigh=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.78,6,12),bm);thigh.position.y=-.5;p.add(thigh);const calf=new THREE.Mesh(new THREE.CapsuleGeometry(.17,.78,6,12),bm);calf.position.y=-1.42;p.add(calf);g.add(p);limbs[n]=p});g.userData.limbs=limbs;g.scale.setScalar(scale);return g}
const concierge=humanoid({body:0x716f62,scale:.9});concierge.position.set(0,.05,-6.2);concierge.rotation.y=Math.PI;scene.add(concierge);const cLabel=label('KŌMØ CONCIERGE',{sx:2.5,sy:.52,font:20});cLabel.position.set(0,4.9,-6.2);scene.add(cLabel);

function doorway(name,x,z,color,rot=0,sx=2.55){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);const fm=mat(color,.54,.15);g.add(box(.3,5,.4,fm,-1.7,2.5,0));g.add(box(.3,5,.4,fm,1.7,2.5,0));g.add(box(3.7,.3,.4,fm,0,4.86,0));const p1=box(1.52,4.2,.07,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.09}),-.8,2.35,0),p2=p1.clone();p2.position.x=.8;g.add(p1,p2);const l=label(name,{sx,sy:.58,font:21});l.position.y=5.55;g.add(l);return{g,p1,p2,open:0}}
const doors={twin:doorway('01 · TWIN LAB',-11,-25.55,C.sand),rehab:doorway('02 · REHAB',11,-25.55,C.sage2),library:doorway('03 · LIBRARY',-23.45,-11.5,C.sage,Math.PI/2),theatre:doorway('04 · AMPHITHEATRE',23.45,-12.5,C.stone2,-Math.PI/2),store:doorway('05 · STORE',23.45,-4,C.bronze,-Math.PI/2)};

// Monumental Arena entrance on the right front wing
const arenaGate=new THREE.Group();arenaGate.position.set(23.2,0,2.8);arenaGate.rotation.y=-Math.PI/2;scene.add(arenaGate);const arenaM=mat(C.arena,.38,.32);arenaGate.add(box(.6,7.6,.8,arenaM,-3.4,3.8,0));arenaGate.add(box(.6,7.6,.8,arenaM,3.4,3.8,0));arenaGate.add(box(7.4,.65,.8,arenaM,0,7.2,0));const inner=new THREE.Mesh(new THREE.TorusGeometry(3.1,.12,12,80,Math.PI),glow(C.arena,1.1));inner.rotation.z=Math.PI;inner.position.y=3.85;arenaGate.add(inner);const gateGlow=new THREE.PointLight(0xf0c77f,28,20,2);gateGlow.position.set(0,4,1);arenaGate.add(gateGlow);const arenaLabel=label('KŌMØ ARENA',{sx:4.1,sy:.8,font:27,bg:'rgba(35,25,14,.84)',color:'#f3d9a6'});arenaLabel.position.set(0,8.45,0);arenaGate.add(arenaLabel);const dailyLabel=label('DAILY · BALANCE HOLD',{sx:3.25,sy:.5,font:18,bg:'rgba(35,25,14,.76)',color:'#e8cf9f'});dailyLabel.position.set(0,6.35,.2);arenaGate.add(dailyLabel);

// Twin Lab
const twinLab=new THREE.Group();twinLab.position.set(-11,0,-34);scene.add(twinLab);const tf=new THREE.Mesh(new THREE.CircleGeometry(11.2,80),mat(0x242e27,.88));tf.rotation.x=-Math.PI/2;tf.position.y=.04;twinLab.add(tf);const tr=new THREE.Mesh(new THREE.RingGeometry(4.1,4.42,96),new THREE.MeshBasicMaterial({color:C.sand,transparent:true,opacity:.48,side:THREE.DoubleSide}));tr.rotation.x=-Math.PI/2;tr.position.y=.08;twinLab.add(tr);
const twin=humanoid({body:C.sage2,holo:true,scale:1.12});twin.position.y=.12;twinLab.add(twin);const twinLabel=label('FUNCTIONAL DIGITAL TWIN',{sx:4.3,sy:.76,font:25});twinLabel.position.set(0,6.6,0);twinLab.add(twinLabel);
const bodyAxis=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,5.2,8),new THREE.MeshBasicMaterial({color:C.sand,transparent:true,opacity:.45}));bodyAxis.position.y=2.55;twinLab.add(bodyAxis);
const leftQuadGlow=new THREE.Mesh(new THREE.CapsuleGeometry(.25,.68,8,14),glow(C.warn,1.5,.46));leftQuadGlow.position.set(-.33,1.35,.03);twinLab.add(leftQuadGlow);const rightQuadGlow=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.68,8,14),glow(C.green,.6,.18));rightQuadGlow.position.set(.33,1.35,.03);twinLab.add(rightQuadGlow);
const postureLine=new THREE.Mesh(new THREE.TorusGeometry(1.65,.018,8,64,Math.PI),new THREE.MeshBasicMaterial({color:C.sage2,transparent:true,opacity:.42}));postureLine.rotation.z=Math.PI/2;postureLine.position.set(.95,3.05,0);twinLab.add(postureLine);
const haloA=new THREE.Mesh(new THREE.TorusGeometry(2.35,.024,8,96),new THREE.MeshBasicMaterial({color:C.green,transparent:true,opacity:.46}));haloA.position.y=2.8;haloA.rotation.x=Math.PI/2;twinLab.add(haloA);const haloB=haloA.clone();haloB.rotation.set(0,Math.PI/2,0);twinLab.add(haloB);
const bodyRegions={left_thigh:leftQuadGlow,trunk:postureLine,strength:rightQuadGlow,gait:haloA};
const baselineGhost=humanoid({body:C.sand,holo:true,scale:.9});baselineGhost.position.set(-4.2,.12,0);baselineGhost.visible=false;twinLab.add(baselineGhost);const todayGhost=humanoid({body:C.sage2,holo:true,scale:.9});todayGhost.position.set(4.2,.12,0);todayGhost.visible=false;twinLab.add(todayGhost);
const sourceVisuals=new Map();SOURCE_CATALOG.forEach((s,i)=>{const a=i/SOURCE_CATALOG.length*Math.PI*2,g=new THREE.Group();g.position.set(Math.cos(a)*8,1.1,Math.sin(a)*8);const o=new THREE.Mesh(new THREE.IcosahedronGeometry(.28,2),glow(i%2?C.sand:C.sage2,.35));g.add(o);const l=label(s.label,{sx:1.95,sy:.4,font:17});l.position.y=.72;g.add(l);twinLab.add(g);sourceVisuals.set(s.id,{g,o,phase:a,baseY:g.position.y})});

// Arena room beyond gate
const arenaRoom=new THREE.Group();arenaRoom.position.set(38,0,-7);scene.add(arenaRoom);const af=new THREE.Mesh(new THREE.CircleGeometry(15.5,96),mat(0x292319,.84,.08));af.rotation.x=-Math.PI/2;af.position.y=.03;arenaRoom.add(af);const aring=new THREE.Mesh(new THREE.RingGeometry(11.8,12.15,96),new THREE.MeshBasicMaterial({color:C.arena,transparent:true,opacity:.38,side:THREE.DoubleSide}));aring.rotation.x=-Math.PI/2;aring.position.y=.07;arenaRoom.add(aring);const podium=cyl(3.2,3.6,.6,64,mat(0x5f4a2f,.46,.22),0,.3,1);arenaRoom.add(podium);const station=cyl(2.2,2.4,.18,64,mat(0xd6bb88,.52,.14),0,.1,-2.5);arenaRoom.add(station);const arenaTitle=label('KŌMØ ARENA · SEASON 01',{sx:5.2,sy:.8,font:26,bg:'rgba(35,25,14,.84)',color:'#f3d9a6'});arenaTitle.position.set(0,7.2,-5);arenaRoom.add(arenaTitle);
for(let i=0;i<3;i++){const h=2.1-i*.38,p=box(2.1,h,2.1,mat(i===0?0xb7955a:i===1?0x8a8176:0x775b45,.5,.2),(i-1)*2.8,h/2,3.8);arenaRoom.add(p)}
const board=box(8,4.7,.3,mat(0x191712,.38,.2),0,4.1,7.2);arenaRoom.add(board);const boardLight=new THREE.PointLight(0xf0c77f,20,16,2);boardLight.position.set(0,4,4);arenaRoom.add(boardLight);

// Player
let avatar={};try{avatar=JSON.parse(localStorage.getItem('komo_world_avatar_v02')||'{}')}catch{}const player=humanoid({body:avatar.outfit==='sand'?0xcdb995:0x879783,skin:avatar.skin==='brown'?0x79503b:avatar.skin==='deep'?0x4f332a:avatar.skin==='light'?0xe3c0a8:0xbc8869,scale:.94});player.position.set(0,0,43);player.rotation.y=Math.PI;scene.add(player);

// ---------- interactions / states ----------
let labMode=false,arenaMode=false,quest=0,currentInteraction=null,selectedSource=null;
const interactions=[];const addInteraction=(id,x,z,r,title,copy,action)=>interactions.push({id,x,z,r,title,copy,action});
addInteraction('desk',0,-2,4.4,'Talk to KŌMØ Concierge','Orientation · Twin · Arena',openDesk);
addInteraction('twinDoor',-11,-24.8,3.7,'Enter Twin Lab','Your body across time',enterTwinLab);
addInteraction('arenaGate',22.1,-7.2,5.4,'Enter KŌMØ Arena','Daily Challenge · leaderboard',enterArena);
addInteraction('rehab',11,-24.8,3.6,'Enter Rehab','Coach Agent · next build',()=>openPanel('REHAB','Coach Agent wing','The Rehab wing remains reserved for deficit-driven sessions connected to the Functional Twin.'));
addInteraction('library',-22,-11.5,3.8,'Enter Library','Knowledge · planned',()=>openPanel('LIBRARY','Knowledge space','Scientific collections, expert content and the future Librarian Agent.'));
addInteraction('frontier',43,18,4.8,'Inspect Riviera Frontier','Locked until partner nodes open',()=>openPanel('RIVIERA FRONTIER','Riviera is forming.','This border will unlock when real partner nodes are operational.'));
addInteraction('twinCore',-11,-34,6,'Inspect Twin','Body · timeline · provenance',()=>selectTwinView('body'));
addInteraction('arenaStation',38,-9.5,5,'Start Daily Challenge','Balance Hold · 60 seconds',startChallenge);

function nearestInteraction(){if(labMode){const i=interactions.find(x=>x.id==='twinCore');return Math.hypot(player.position.x-i.x,player.position.z-i.z)<i.r?i:null}if(arenaMode){const i=interactions.find(x=>x.id==='arenaStation');return Math.hypot(player.position.x-i.x,player.position.z-i.z)<i.r?i:null}let best=null,d=Infinity;for(const i of interactions){if(['twinCore','arenaStation'].includes(i.id))continue;const q=Math.hypot(player.position.x-i.x,player.position.z-i.z);if(q<i.r&&q<d){best=i;d=q}}return best}
function refreshInteraction(){currentInteraction=nearestInteraction();const e=$('#interaction');if(!currentInteraction){e.classList.remove('show');$('#mobile-action').textContent='ACTION';return}$('#interaction-title').textContent=currentInteraction.title;$('#interaction-copy').textContent=currentInteraction.copy;e.classList.add('show');$('#mobile-action').textContent=currentInteraction.id==='desk'?'TALK':currentInteraction.id==='arenaStation'?'START':'ENTER'}
function runInteraction(){currentInteraction?.action()}
function openPanel(kicker,title,copy){$('#panel-kicker').textContent=kicker;$('#panel-title').textContent=title;$('#panel-body').innerHTML=`<p>${copy}</p>`;$('#panel').classList.add('open')}
$('#panel-close').onclick=()=>$('#panel').classList.remove('open');
function openDesk(){if(quest===0){quest=1;$('#quest-copy').textContent='02 · Inspect your Functional Digital Twin';toast('Objective updated · Twin Lab')}const snap=core.current();openPanel('KŌMØ CONCIERGE','Your next move.',`Motion Score ${snap.motion_score}. Motion Age ${snap.motion_age}. Your current private priority is the left quadriceps. Inspect the Twin, then try today’s Arena challenge.`);}
function enterTwinLab(){labMode=true;arenaMode=false;$('#panel').classList.remove('open');player.position.set(-11,0,-27.2);yaw=Math.PI;$('#twin-hud').classList.add('open');$('#arena-hud').classList.remove('open');$('#location-name').textContent='FUNCTIONAL DIGITAL TWIN LAB';quest=Math.max(quest,2);$('#quest-copy').textContent='03 · Explore the Twin, then enter KŌMØ Arena';toast('Twin Lab · truth layer')}
function leaveTwinLab(){labMode=false;player.position.set(-8.5,0,-22.5);$('#twin-hud').classList.remove('open');$('#location-name').textContent='KŌMØ HALL · ATRIUM';selectTwinView('overview')}
$('#twin-exit').onclick=leaveTwinLab;$('#go-arena').onclick=()=>{leaveTwinLab();toast('Arena highlighted · right wing')};
function enterArena(){arenaMode=true;labMode=false;$('#twin-hud').classList.remove('open');$('#panel').classList.remove('open');player.position.set(38,0,-2.5);yaw=Math.PI;$('#arena-hud').classList.add('open');$('#location-name').textContent='KŌMØ ARENA · SEASON 01';renderArena();quest=Math.max(quest,3);$('#quest-copy').textContent='04 · Complete today’s Balance Hold';toast('KŌMØ Arena · Daily Challenge')}
function leaveArena(){arenaMode=false;player.position.set(20.5,0,-6);$('#arena-hud').classList.remove('open');$('#location-name').textContent='KŌMŌ HALL · ATRIUM'}
$('#arena-exit').onclick=leaveArena;

// ---------- Twin UI ----------
const baseline=core.snapshots[0];const fmt=(v,d=0,s='')=>`${v>0?'+':''}${Number(v).toFixed(d)}${s}`;const formatDate=iso=>new Date(iso).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).toUpperCase();
const domains=[['muscle','Muscle'],['mobility','Mobility'],['balance','Balance'],['posture','Posture'],['endurance','Endurance']];
function priorityFor(s){const q=s.metrics.quadriceps_symmetry,int=s.overlays?.left_thigh?.intensity??0;if(q<80||int>.45)return{state:'ATTENTION',copy:'Activation asymmetry remains the main modifiable limitation.'};if(q<90||int>.2)return{state:'WATCH',copy:'Residual asymmetry persists, with clear longitudinal improvement.'};return{state:'STABLE',copy:'No major asymmetry is highlighted in the current snapshot.'}}
function renderTwin(index=core.activeIndex){core.setTimeIndex(index,'v08-ui');const s=core.current(),cmp=core.compare(baseline.snapshot_id,s.snapshot_id,'v08-ui'),p=priorityFor(s);$('#hud-motion').textContent=s.motion_score;$('#twin-snapshot').textContent=s.label.toUpperCase();$('#twin-date').textContent=formatDate(s.captured_at);$('#twin-score-large').textContent=s.motion_score;$('#twin-age-large').textContent=s.motion_age;$('#twin-score-delta').textContent=`${fmt(cmp.motion_score_delta)} since baseline`;$('#twin-age-delta').textContent=`${fmt(cmp.motion_age_delta)} years`;$('#priority-state').textContent=p.state;$('#priority-copy').textContent=p.copy;$('#priority-value').textContent=`${s.metrics.quadriceps_symmetry}%`;$('#priority-delta').textContent=`${fmt(s.metrics.quadriceps_symmetry-baseline.metrics.quadriceps_symmetry)} pts`;$('#callout-quad').textContent=`${s.metrics.quadriceps_symmetry}%`;$('#callout-gait').textContent=s.metrics.gait_speed.toFixed(2);$('#callout-posture').textContent=s.metrics.posture_index;$('#callout-strength').textContent=s.metrics.strength_index;$('#timeline-current-label').textContent=s.label.toUpperCase();
 $('#domain-bars').innerHTML=domains.map(([id,l])=>{const v=s.domains[id]??0,d=v-(baseline.domains[id]??v);return`<div class="domain-row"><span>${l}</span><div class="domain-track"><div class="domain-fill" style="width:${v}%"></div></div><div class="domain-value"><b>${v}</b><small>${fmt(d)}</small></div></div>`}).join('');
 const signals=[['Gait speed',`${s.metrics.gait_speed.toFixed(2)} m/s`,fmt(s.metrics.gait_speed-baseline.metrics.gait_speed,2,' m/s')],['Strength',`${s.metrics.strength_index}/100`,fmt(s.metrics.strength_index-baseline.metrics.strength_index)],['Sleep',`${Math.floor(s.metrics.sleep_minutes/60)}h ${String(s.metrics.sleep_minutes%60).padStart(2,'0')}`,fmt(s.metrics.sleep_minutes-baseline.metrics.sleep_minutes,0,' min')],['Activity',`${s.metrics.steps.toLocaleString()} steps`,fmt(s.metrics.steps-baseline.metrics.steps)],['Rehab',`${s.metrics.rehab_adherence}%`,fmt(s.metrics.rehab_adherence-baseline.metrics.rehab_adherence,'',' pts')],['Quad symmetry',`${s.metrics.quadriceps_symmetry}%`,fmt(s.metrics.quadriceps_symmetry-baseline.metrics.quadriceps_symmetry,0,' pts')]];$('#key-signals').innerHTML=signals.map(([l,v,d])=>`<div class="signal-card"><span>${l}</span><b>${v}</b><small>${d}</small></div>`).join('');
 $('#compare-grid').innerHTML=[['Motion Score',baseline.motion_score,s.motion_score,fmt(cmp.motion_score_delta)],['Motion Age',baseline.motion_age,s.motion_age,fmt(cmp.motion_age_delta,0,' yr')],['Quad symmetry',baseline.metrics.quadriceps_symmetry,s.metrics.quadriceps_symmetry,fmt(cmp.metric_delta.quadriceps_symmetry,0,' pts')],['Gait speed',baseline.metrics.gait_speed.toFixed(2),s.metrics.gait_speed.toFixed(2),fmt(cmp.metric_delta.gait_speed,2,' m/s')],['Strength',baseline.metrics.strength_index,s.metrics.strength_index,fmt(cmp.metric_delta.strength_index)],['Posture',baseline.metrics.posture_index,s.metrics.posture_index,fmt(cmp.metric_delta.posture_index)]].map(([l,a,b,d])=>`<div class="compare-card"><span>${l}</span><b>${a} → ${b}</b><small>${d}</small></div>`).join('');
 $$('[data-time]').forEach(b=>b.classList.toggle('active',Number(b.dataset.time)===index));const intensity=s.overlays?.left_thigh?.intensity??.3;leftQuadGlow.material.opacity=.18+intensity*.55;leftQuadGlow.material.emissiveIntensity=.45+intensity*2.2;baselineGhost.visible=false;todayGhost.visible=false;twin.visible=true;
}
function selectTwinView(v){$('#twin-hud').dataset.view=v;$$('[data-twin-view]').forEach(b=>b.classList.toggle('active',b.dataset.twinView===v));$('#compare-layer').classList.toggle('open',v==='compare');$('#source-inspector').classList.toggle('open',v==='sources');if(v==='compare'){baselineGhost.visible=true;todayGhost.visible=true;twin.visible=false}else{baselineGhost.visible=false;todayGhost.visible=false;twin.visible=true}}
$$('[data-twin-view]').forEach(b=>b.onclick=()=>selectTwinView(b.dataset.twinView));$$('[data-time]').forEach(b=>b.onclick=()=>renderTwin(Number(b.dataset.time)));$('#compare-now').onclick=()=>selectTwinView('compare');$('#compare-close').onclick=()=>selectTwinView('overview');$('#source-close').onclick=()=>selectTwinView('overview');
$('#twin-sources').innerHTML=SOURCE_CATALOG.map(s=>`<button data-source="${s.id}">${s.label}</button>`).join('');$$('[data-source]').forEach(b=>b.onclick=()=>{const id=b.dataset.source,s=core.current(),meta=s.sources[id]||{},src=SOURCE_CATALOG.find(x=>x.id===id);selectedSource=id;$$('[data-source]').forEach(x=>x.classList.toggle('active',x.dataset.source===id));sourceVisuals.forEach((v,k)=>{v.o.material.emissiveIntensity=k===id?1.8:.35;v.o.scale.setScalar(k===id?1.4:1)});$('#source-title').textContent=src.label;$('#source-content').innerHTML=`<div class="source-meta"><div><span>Snapshot</span><b>${s.label}</b></div><div><span>Status</span><b>${meta.status||'available'}</b></div><div><span>Quality</span><b>${meta.quality?Math.round(meta.quality*100)+'%':'—'}</b></div><div><span>Method</span><b>${meta.method||'—'}</b></div><div><span>Version</span><b>${s.provenance_version}</b></div><div><span>Layer</span><b>${src.group}</b></div></div><p class="source-note">The AI layer may explain this dated value but cannot silently rewrite the underlying measurement.</p>`;selectTwinView('sources')});
$$('[data-region]').forEach(b=>b.onclick=()=>{selectTwinView('body');const id=b.dataset.region;Object.entries(bodyRegions).forEach(([k,o])=>{const active=k===id;o.material.opacity=active?.65:(o===postureLine?.28:.14);if(o.material.emissiveIntensity!==undefined)o.material.emissiveIntensity=active?2:.5});toast(`${b.querySelector('span').textContent} · body focus`)});renderTwin(2);

// ---------- Arena data / leaderboard ----------
const baseLeaders=[{name:'Maya',club:'Riviera Club',score:948},{name:'Noah',club:'Performance',score:921},{name:'Léa',club:'Running Club',score:904},{name:'Alex',club:'KŌMØ Core',score:881},{name:'Sofia',club:'Riviera Club',score:856},{name:'Hugo',club:'Performance',score:834}];
function loadArena(){try{return JSON.parse(localStorage.getItem('komo_arena_v08')||'null')||{points:2480,xp:0,best:null,streak:0,lastDay:null}}catch{return{points:2480,xp:0,best:null,streak:0,lastDay:null}}}let arenaData=loadArena();function saveArena(){localStorage.setItem('komo_arena_v08',JSON.stringify(arenaData));$('#hud-points').textContent=arenaData.points.toLocaleString()}
function leaderboardData(){const arr=[...baseLeaders];if(arenaData.best!==null)arr.push({name:'You',club:'KŌMØ Core',score:arenaData.best,me:true});return arr.sort((a,b)=>b.score-a.score).map((x,i)=>({...x,rank:i+1}))}
function renderArena(){const rows=leaderboardData();$('#leaderboard').innerHTML=rows.map(r=>`<div class="leader-row ${r.me?'me':''}"><div class="leader-rank">${String(r.rank).padStart(2,'0')}</div><div class="leader-name"><b>${r.name}</b><span>${r.club}</span></div><div class="leader-score"><b>${r.score}</b><span>pts</span></div></div>`).join('');const me=rows.find(x=>x.me);$('#your-best').textContent=arenaData.best===null?'—':arenaData.best;$('#your-rank').textContent=me?`Rank #${me.rank}`:'Unranked';$('#arena-streak').textContent=`${arenaData.streak} day${arenaData.streak===1?'':'s'}`;$('#arena-xp').textContent=arenaData.xp;$('#hud-points').textContent=arenaData.points.toLocaleString()}
renderArena();

// Challenge physics: keep marker centered using left/right control while drift/noise moves it.
let challengeRunning=false,challengeStart=0,challengeLast=0,markerX=0,velocity=0,correctionsCount=0,stabilityAcc=0,challengeFrames=0,lastInput=0;
function startChallenge(){if(challengeRunning)return;challengeRunning=true;$('#arena-hud').classList.remove('open');$('#challenge').classList.add('open');$('#result').classList.remove('open');challengeStart=performance.now();challengeLast=challengeStart;markerX=0;velocity=0;correctionsCount=0;stabilityAcc=0;challengeFrames=0;lastInput=0;toast('3 · 2 · 1 · GO')}
$('#challenge-start').onclick=startChallenge;$('#challenge-cancel').onclick=()=>finishChallenge(true);
function challengeInput(){const left=keys.has(settings.bindings.left),right=keys.has(settings.bindings.right);let x=(right?1:0)-(left?1:0);if(Math.abs(joy.x)>.08)x+=joy.x;return THREE.MathUtils.clamp(x,-1,1)}
function updateChallenge(now){if(!challengeRunning)return;const dt=Math.min((now-challengeLast)/1000,.05);challengeLast=now;const elapsed=(now-challengeStart)/1000,remain=Math.max(0,60-elapsed);const input=challengeInput();const drift=Math.sin(now*.0013)*.17+Math.sin(now*.0029+1.2)*.08;velocity+=drift*dt+input*.95*dt;velocity*=Math.pow(.36,dt);markerX+=velocity*dt;markerX=THREE.MathUtils.clamp(markerX,-1.15,1.15);if(Math.sign(input)!==Math.sign(lastInput)&&Math.abs(input)>.08&&Math.abs(lastInput)>.08)correctionsCount++;if(Math.abs(input)>.08)lastInput=input;const stability=Math.max(0,1-Math.abs(markerX)/1.15);stabilityAcc+=stability;challengeFrames++;const live=Math.round(elapsed*10*stability + stabilityAcc/challengeFrames*400);$('#balance-marker').style.left=`${50+markerX*39}%`;$('#challenge-time').textContent=remain.toFixed(1);$('#stability-score').textContent=Math.round(stability*100);$('#corrections').textContent=correctionsCount;$('#live-score').textContent=live;if(remain<=0||Math.abs(markerX)>=1.14)finishChallenge(false)}
function finishChallenge(cancelled=false){if(!challengeRunning)return;challengeRunning=false;const elapsed=Math.min(60,(performance.now()-challengeStart)/1000),stability=challengeFrames?stabilityAcc/challengeFrames:0;const score=cancelled?Math.round(elapsed*8*stability):Math.round(elapsed*10*stability+stability*400-Math.min(correctionsCount,20)*3);const oldBest=arenaData.best;const newBest=oldBest===null||score>oldBest;if(!cancelled){arenaData.best=Math.max(oldBest??0,score);arenaData.points+=85;arenaData.xp+=40;const today=new Date().toISOString().slice(0,10);if(arenaData.lastDay!==today){arenaData.streak+=1;arenaData.lastDay=today}saveArena()}$('#challenge').classList.remove('open');$('#result-title').textContent=cancelled?'Challenge ended.':newBest?'New personal best.':'Challenge complete.';$('#result-score').textContent=score;$('#result-time').textContent=`${elapsed.toFixed(1)}s`;$('#result-stability').textContent=`${Math.round(stability*100)}%`;$('#result-points').textContent=cancelled?'+0':'+85';renderArena();const me=leaderboardData().find(x=>x.me);$('#result-rank').textContent=me?`#${me.rank}`:'—';$('#result').classList.add('open')}
$('#result-close').onclick=()=>{$('#result').classList.remove('open');$('#arena-hud').classList.add('open')};

// ---------- movement / camera / mobile ----------
const keys=new Set();let yaw=0,pitch=.11,drag=false,last={x:0,y:0};const norm=e=>e.key===' '?' ':e.key.toLowerCase();window.addEventListener('keydown',e=>{const k=norm(e);keys.add(k);if(!challengeRunning&&k===settings.bindings.interact){e.preventDefault();runInteraction()}if(k==='escape')$('#settings').classList.toggle('open')});window.addEventListener('keyup',e=>keys.delete(norm(e)));
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag=true;last={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;yaw+=dx*.0034*settings.camera.sensX;const sign=settings.camera.invertY?-1:1;pitch=THREE.MathUtils.clamp(pitch+sign*dy*.0022*settings.camera.sensY,-.12,.48);last={x:e.clientX,y:e.clientY}});
const joy={x:0,y:0,p:null};const joyZone=$('#joystick-zone'),joyKnob=$('#joystick-knob');function updateJoy(e){const r=joyZone.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=42;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy);if(l>max){dx=dx/l*max;dy=dy/l*max}joy.x=dx/max;joy.y=dy/max;joyKnob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}joyZone.addEventListener('pointerdown',e=>{joy.p=e.pointerId;joyZone.setPointerCapture?.(e.pointerId);updateJoy(e)});joyZone.addEventListener('pointermove',e=>{if(e.pointerId===joy.p)updateJoy(e)});function resetJoy(e){if(joy.p===null||e.pointerId===joy.p){joy.p=null;joy.x=joy.y=0;joyKnob.style.transform='translate(-50%,-50%)'}}joyZone.addEventListener('pointerup',resetJoy);joyZone.addEventListener('pointercancel',resetJoy);
const lookZone=$('#look-zone');let lookP=null,lookLast=null;lookZone.addEventListener('pointerdown',e=>{lookP=e.pointerId;lookLast={x:e.clientX,y:e.clientY};lookZone.setPointerCapture?.(e.pointerId)});lookZone.addEventListener('pointermove',e=>{if(e.pointerId!==lookP||challengeRunning)return;const dx=e.clientX-lookLast.x,dy=e.clientY-lookLast.y;yaw+=dx*.0041*settings.camera.sensX;const sign=settings.camera.invertY?-1:1;pitch=THREE.MathUtils.clamp(pitch+sign*dy*.0028*settings.camera.sensY,-.12,.48);lookLast={x:e.clientX,y:e.clientY}});lookZone.addEventListener('pointerup',e=>{if(e.pointerId===lookP){lookP=null;lookLast=null}});lookZone.addEventListener('pointercancel',e=>{if(e.pointerId===lookP){lookP=null;lookLast=null}});$('#mobile-action').onclick=()=>challengeRunning?null:runInteraction();
$('#settings-open').onclick=()=>$('#settings').classList.add('open');$('#settings-close').onclick=()=>$('#settings').classList.remove('open');$('#intro-enter').onclick=()=>$('#intro').classList.add('hidden');

function zoneName(){if(labMode)return'FUNCTIONAL DIGITAL TWIN LAB';if(arenaMode)return'KŌMŌ ARENA · SEASON 01';if(player.position.z>23)return'ARRIVAL PLAZA';if(player.position.x>28)return'ARENA DISTRICT';if(player.position.z<-22)return'KŌMŌ HALL · INNER WING';return'KŌMŌ HALL · ATRIUM'}
const desired=new THREE.Vector3(),target=new THREE.Vector3();function movement(dt){if(challengeRunning)return;const fwd=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const m=new THREE.Vector3();if(keys.has(settings.bindings.forward))m.add(fwd);if(keys.has(settings.bindings.backward))m.sub(fwd);if(keys.has(settings.bindings.left))m.sub(right);if(keys.has(settings.bindings.right))m.add(right);if(Math.abs(joy.x)>.04||Math.abs(joy.y)>.04){m.addScaledVector(right,joy.x);m.addScaledVector(fwd,-joy.y)}const moving=m.lengthSq()>.002,sprint=keys.has(settings.bindings.sprint),speed=sprint?7.2:4.4;if(moving){m.normalize();player.position.addScaledVector(m,speed*dt);player.rotation.y=Math.atan2(m.x,m.z)}if(labMode){player.position.x=THREE.MathUtils.clamp(player.position.x,-20,-2);player.position.z=THREE.MathUtils.clamp(player.position.z,-43,-26)}else if(arenaMode){player.position.x=THREE.MathUtils.clamp(player.position.x,25,52);player.position.z=THREE.MathUtils.clamp(player.position.z,-21,7)}else{const r=Math.hypot(player.position.x,player.position.z);if(r>58){player.position.multiplyScalar(58/r);player.position.y=0}}
 const t=performance.now()*.012,s=moving?Math.sin(t)*.43:0;player.userData.limbs.ll.rotation.x=s;player.userData.limbs.rl.rotation.x=-s;player.userData.limbs.la.rotation.x=-s*.7;player.userData.limbs.ra.rotation.x=s*.7;const d=settings.camera.distance;desired.set(player.position.x+Math.sin(yaw)*d,6.9+pitch*8,player.position.z+Math.cos(yaw)*d);target.set(player.position.x,2.6,player.position.z);camera.position.lerp(desired,1-Math.pow(.0025,dt));camera.lookAt(target);const deg=((THREE.MathUtils.radToDeg(yaw)%360)+360)%360;$('#heading').textContent=deg<45||deg>=315?'N':deg<135?'E':deg<225?'S':'W';$('#location-name').textContent=zoneName();refreshInteraction()}
function animate(){const dt=Math.min(clock.getDelta(),.05),now=performance.now();movement(dt);updateChallenge(now);const t=now*.001;spawnRing.material.opacity=.43+Math.sin(t*1.8)*.12;water.material.roughness=.2+Math.sin(t*.25)*.02;haloA.rotation.z+=dt*.12;haloB.rotation.x+=dt*.08;twin.rotation.y=Math.sin(t*.35)*.08;leftQuadGlow.scale.y=.96+Math.sin(t*2.3)*.05;sourceVisuals.forEach(v=>{v.g.position.y=v.baseY+Math.sin(t*1.15+v.phase)*.11;v.o.rotation.y+=dt*.45});inner.rotation.y+=dt*.1;gateGlow.intensity=27+Math.sin(t*1.4)*3;renderer.render(scene,camera);requestAnimationFrame(animate)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();camera.position.set(0,7.2,65);camera.lookAt(0,2.6,43);saveArena();animate();toast('KŌMØ World V0.8 · Twin + Arena');